pub mod common;
pub mod jit;

pub use jit::JITCodegen;

use crate::mir::{
    self, CallArg, IntrinsicOp, Local, LocalKind, MIRType, MirBinOp, MirConstant, MirFunction,
};
use std::collections::{HashMap, HashSet};

pub struct Codegen {
    ir: String,
    indent: usize,
    declarations: String,
    /// 字符串常量
    strings: Vec<String>,
    /// 字符串计数器
    string_counter: usize,
    /// 预计算的 local 名称缓存：local.id → 名称字符串
    pub(crate) name_cache: Vec<String>,
    /// MIR 类型到 LLVM 类型字符串的缓存
    type_str_cache: HashMap<MIRType, String>,
    /// load 指令计数器，确保 SSA 名称唯一
    load_counter: usize,
}

impl Codegen {
    pub fn new() -> Self {
        let mut cg = Self {
            ir: String::new(),
            indent: 0,
            declarations: String::new(),
            strings: Vec::new(),
            string_counter: 0,
            name_cache: Vec::new(),
            type_str_cache: HashMap::new(),
            load_counter: 0,
        };
        cg.emit_header();
        cg.declare_runtime_functions();
        cg
    }

    fn emit_header(&mut self) {
        // target triple 放在 declarations 最前面，确保它是 IR 的第一行
        self.declarations.push_str("; Sengoo LLVM IR\n");
        self.declarations
            .push_str("; Generated by Sengoo Compiler\n\n");

        // 设置 target triple 避免 clang 的 -Woverride-module 警告
        if cfg!(target_os = "windows") {
            self.declarations
                .push_str("target triple = \"x86_64-pc-windows-msvc\"\n\n");
        } else if cfg!(target_os = "macos") {
            self.declarations
                .push_str("target triple = \"x86_64-apple-macosx\"\n\n");
        } else {
            self.declarations
                .push_str("target triple = \"x86_64-unknown-linux-gnu\"\n\n");
        }
    }

    /// 声明运行时函数（外部 C 函数）
    fn declare_runtime_functions(&mut self) {
        self.declarations
            .push_str("; External C library functions\n");
        self.declarations.push_str("declare i32 @puts(i8*)\n");
        self.declarations
            .push_str("declare i32 @printf(i8*, ...)\n");
        self.declarations.push_str("\n");

        // Sengoo runtime print functions
        self.declarations
            .push_str("; Sengoo runtime print functions\n");
        self.declarations
            .push_str("declare void @sengoo_print_i64(i64)\n");
        self.declarations
            .push_str("declare void @sengoo_print_bool(i64)\n");
        self.declarations
            .push_str("declare void @sengoo_print_f64(double)\n");
        self.declarations
            .push_str("declare void @sengoo_print_str(i8*)\n");
        self.declarations.push_str("\n");

        // Sengoo runtime string functions
        self.declarations
            .push_str("; Sengoo runtime string functions\n");
        self.declarations
            .push_str("declare i64 @sengoo_str_len(i8*)\n");
        self.declarations
            .push_str("declare i8* @sengoo_str_concat(i8*, i8*)\n");
        self.declarations
            .push_str("declare i64 @sengoo_str_eq(i8*, i8*)\n");
        self.declarations.push_str("\n");
    }

    /// 发射字符串常量
    fn emit_string_constants(&mut self) {
        if !self.strings.is_empty() {
            self.declarations.push_str("; String Constants\n");
            for (i, s) in self.strings.iter().enumerate() {
                // 转义字符串
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
                self.declarations.push_str(&format!(
                    "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\"\n",
                    i,
                    s.len() + 1,
                    escaped
                ));
            }
            self.declarations.push_str("\n");
        }
    }

    /// 添加字符串常量，返回其引用名
    fn add_string(&mut self, s: &str) -> String {
        let idx = self.string_counter;
        self.string_counter += 1;
        self.strings.push(s.to_string());
        format!("@.str.{}", idx)
    }

    /// 扫描所有 MIR 函数，收集结构体类型并生成 LLVM named struct type 声明
    fn emit_struct_types(&mut self, mir_fns: &[MirFunction]) {
        let mut seen = HashSet::new();
        for func in mir_fns {
            for (_, ty) in &func.locals {
                self.collect_struct_types(ty, &mut seen);
            }
        }
    }

    /// 递归收集结构体类型，生成 LLVM named type 声明
    fn collect_struct_types(&mut self, ty: &MIRType, seen: &mut HashSet<String>) {
        match ty {
            MIRType::Struct { name, fields } => {
                if seen.insert(name.clone()) {
                    // 先递归收集嵌套的结构体类型
                    for (_, ft) in fields {
                        self.collect_struct_types(ft, seen);
                    }
                    let field_types: Vec<String> = fields
                        .iter()
                        .map(|(_, ft)| self.mir_type_to_llvm_cached(ft))
                        .collect();
                    self.declarations.push_str(&format!(
                        "%{} = type {{ {} }}\n",
                        name,
                        field_types.join(", ")
                    ));
                }
            }
            // Recurse into composite types that may contain structs
            MIRType::Array(elem, _) | MIRType::Ptr(elem) | MIRType::Ref(elem) => {
                self.collect_struct_types(elem, seen);
            }
            MIRType::Tuple(types) => {
                for t in types {
                    self.collect_struct_types(t, seen);
                }
            }
            _ => {}
        }
    }

    /// Estimate the IR buffer capacity based on MIR function metrics.
    /// This avoids repeated reallocations during IR generation.
    fn estimate_ir_capacity(mir_fns: &[MirFunction]) -> usize {
        let mut estimate = 1024; // Base overhead for header, runtime declarations, etc.
        for func in mir_fns {
            // Each local ~30 bytes (alloca declaration)
            estimate += func.locals.len() * 30;
            // Each basic block ~20 bytes (label)
            estimate += func.basic_blocks.len() * 20;
            // Each instruction ~60 bytes of IR text
            for bb in &func.basic_blocks {
                estimate += bb.instructions.len() * 60;
                // Terminator ~40 bytes
                if bb.terminator.is_some() {
                    estimate += 40;
                }
            }
            // Function header/footer overhead (~80 bytes for define, params, closing brace)
            estimate += 80;
        }
        estimate
    }

    pub fn codegen(&mut self, mir_fns: &[MirFunction]) -> Result<String, String> {
        // Pre-allocate IR buffer based on MIR size estimate to reduce reallocations
        let capacity = Self::estimate_ir_capacity(mir_fns);
        self.ir.reserve(capacity);

        // 首先收集所有字符串常量
        for mir_fn in mir_fns {
            self.collect_string_constants(mir_fn);
        }
        // 发射字符串常量声明
        self.emit_string_constants();

        // 扫描所有 MIR 函数，收集并生成结构体类型声明
        self.emit_struct_types(mir_fns);

        // 生成函数代码
        for mir_fn in mir_fns {
            self.codegen_function(mir_fn)?;
        }
        let mut result = self.declarations.clone();
        result.push_str(&self.ir);
        Ok(result)
    }

    /// 从函数中收集字符串常量
    fn collect_string_constants(&mut self, mir_fn: &MirFunction) {
        for bb in &mir_fn.basic_blocks {
            for inst in &bb.instructions {
                if let mir::Instruction::Assign {
                    value: mir::MirConstant::String(s),
                    ..
                } = inst
                {
                    self.add_string(s);
                }
            }
        }
    }

    fn codegen_function(&mut self, mir_fn: &MirFunction) -> Result<(), String> {
        // Pre-compute all local names for O(1) lookup
        self.build_name_cache(mir_fn);
        // Reset load counter per function for clean SSA naming
        self.load_counter = 0;

        self.ir.push_str("\n");
        self.ir.push_str(&format!("; Function: {}\n", mir_fn.name));
        let return_type = self.mir_type_to_llvm_cached(&mir_fn.return_type);
        self.ir
            .push_str(&format!("define {} @{}(", return_type, mir_fn.name));
        for (i, ty) in mir_fn.params.iter().enumerate() {
            let param_name = format!("%l_{}", i + 1);
            if i > 0 {
                self.ir.push_str(", ");
            }
            let param_ty = self.mir_type_to_llvm_cached(ty);
            self.ir.push_str(&format!("{} {}", param_ty, param_name));
        }
        self.ir.push_str(") {\n");
        self.indent += 1;

        // Track which locals need alloca (user variables only)
        let user_locals: Vec<_> = mir_fn
            .locals
            .iter()
            .filter(|(l, _)| l.kind == LocalKind::User)
            .collect();

        for bb in &mir_fn.basic_blocks {
            let allocas: Vec<(Local, MIRType)> = if bb.id == 0 {
                user_locals.iter().map(|(l, t)| (*l, t.clone())).collect()
            } else {
                vec![]
            };
            self.codegen_basic_block(mir_fn, bb, &allocas)?;
        }
        self.indent -= 1;
        self.ir.push_str("}\n");
        Ok(())
    }

    fn codegen_basic_block(
        &mut self,
        mir_fn: &MirFunction,
        bb: &mir::BasicBlock,
        allocas: &[(Local, MIRType)],
    ) -> Result<(), String> {
        self.ir.push_str(&format!("bb_{}:\n", bb.id));
        self.indent += 1;

        // Emit allocas at the start of the entry block (before any instructions)
        for (local, ty) in allocas {
            let local_name = self.local_name(*local);
            let llvm_ty = self.mir_type_to_llvm_cached(ty);
            self.emit_indent();
            self.ir
                .push_str(&format!("{} = alloca {}\n", local_name, llvm_ty));
        }

        for inst in &bb.instructions {
            self.codegen_instruction(inst, mir_fn)?;
        }
        if let Some(terminator) = &bb.terminator {
            self.codegen_terminator(terminator, mir_fn)?;
        }
        self.indent -= 1;
        Ok(())
    }

    fn codegen_instruction(
        &mut self,
        inst: &mir::Instruction,
        mir_fn: &MirFunction,
    ) -> Result<(), String> {
        match inst {
            mir::Instruction::Nop => {}
            mir::Instruction::Assign { destination, value } => {
                let dest = self.local_name(*destination);
                self.emit_indent();
                match value {
                    mir::MirConstant::Int(n) => {
                        self.ir.push_str(&format!("{} = add i64 0, {}\n", dest, n));
                    }
                    mir::MirConstant::Uint(n) => {
                        self.ir.push_str(&format!("{} = add i64 0, {}\n", dest, n));
                    }
                    mir::MirConstant::Bool(b) => {
                        self.ir.push_str(&format!(
                            "{} = add i1 0, {}\n",
                            dest,
                            if *b { 1 } else { 0 }
                        ));
                    }
                    mir::MirConstant::Float(f) => {
                        self.ir
                            .push_str(&format!("{} = fadd double 0.0, {}\n", dest, f));
                    }
                    mir::MirConstant::Char(c) => {
                        self.ir
                            .push_str(&format!("{} = add i8 0, {}\n", dest, *c as i8));
                    }
                    mir::MirConstant::String(s) => {
                        // 查找字符串常量的索引
                        let str_idx = self.strings.iter().position(|x| x == s).unwrap_or(0);
                        let str_ref = format!("@.str.{}", str_idx);
                        self.ir.push_str(&format!(
                            "{} = bitcast [{} x i8]* {} to i8*\n",
                            dest,
                            s.len() + 1,
                            str_ref
                        ));
                    }
                    mir::MirConstant::Bytes(_) => {
                        self.ir.push_str(&format!("{} = add i64 0, 0\n", dest));
                    }
                    mir::MirConstant::GlobalRef(name) => {
                        self.ir
                            .push_str(&format!("{} = bitcast i64* @{} to i64\n", dest, name));
                    }
                    mir::MirConstant::Unit => {
                        self.ir.push_str(&format!("{} = add i8 0, 0\n", dest));
                    }
                }
            }
            mir::Instruction::Unary {
                destination,
                op,
                operand,
            } => {
                let dest = self.local_name(*destination);
                let src_val = self.operand_value(*operand, mir_fn);
                self.emit_indent();
                match op {
                    mir::MirUnOp::Neg => {
                        self.ir
                            .push_str(&format!("{} = sub i64 0, {}\n", dest, src_val));
                    }
                    mir::MirUnOp::Not => {
                        self.ir
                            .push_str(&format!("{} = xor i1 {}, true\n", dest, src_val));
                    }
                    mir::MirUnOp::BitNot => {
                        self.ir
                            .push_str(&format!("{} = xor i64 {}, -1\n", dest, src_val));
                    }
                }
            }
            mir::Instruction::Binary {
                destination,
                op,
                left,
                right,
            } => {
                let dest = self.local_name(*destination);
                // 如果操作数是用户变量，需要先 load
                let left_val = self.operand_value(*left, mir_fn);
                let right_val = self.operand_value(*right, mir_fn);
                self.emit_indent();
                match op {
                    mir::MirBinOp::Add => {
                        self.ir
                            .push_str(&format!("{} = add i64 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::Sub => {
                        self.ir
                            .push_str(&format!("{} = sub i64 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::Mul => {
                        self.ir
                            .push_str(&format!("{} = mul i64 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::Div => {
                        self.ir.push_str(&format!(
                            "{} = sdiv i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::Rem => {
                        self.ir.push_str(&format!(
                            "{} = srem i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::Eq => {
                        self.ir.push_str(&format!(
                            "{} = icmp eq i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::Ne => {
                        self.ir.push_str(&format!(
                            "{} = icmp ne i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::Lt => {
                        self.ir.push_str(&format!(
                            "{} = icmp slt i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::Le => {
                        self.ir.push_str(&format!(
                            "{} = icmp sle i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::Gt => {
                        self.ir.push_str(&format!(
                            "{} = icmp sgt i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::Ge => {
                        self.ir.push_str(&format!(
                            "{} = icmp sge i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::BitAnd => {
                        self.ir
                            .push_str(&format!("{} = and i64 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::BitOr => {
                        self.ir
                            .push_str(&format!("{} = or i64 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::BitXor => {
                        self.ir
                            .push_str(&format!("{} = xor i64 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::Shl => {
                        self.ir
                            .push_str(&format!("{} = shl i64 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::Shr => {
                        self.ir.push_str(&format!(
                            "{} = ashr i64 {}, {}\n",
                            dest, left_val, right_val
                        ));
                    }
                    mir::MirBinOp::LogAnd => {
                        self.ir
                            .push_str(&format!("{} = and i1 {}, {}\n", dest, left_val, right_val));
                    }
                    mir::MirBinOp::LogOr => {
                        self.ir
                            .push_str(&format!("{} = or i1 {}, {}\n", dest, left_val, right_val));
                    }
                }
            }
            mir::Instruction::Load {
                destination,
                source,
            } => {
                let dest = self.local_name(*destination);
                // 使用 id 直接索引，O(1) 查找
                let (local_info, src_ty) = &mir_fn.locals[source.id];

                self.emit_indent();
                // 需要判断是否需要真的 load：
                // 1. 用户变量（alloca）总是需要 load
                // 2. 指针类型的临时变量也需要 load（从地址加载值）
                let needs_load = local_info.kind == LocalKind::User
                    || matches!(src_ty, MIRType::Ptr(_) | MIRType::Ref(_));

                if needs_load {
                    let src = self.local_name(*source);
                    let llvm_ty = self.mir_type_to_llvm_cached(src_ty);
                    // 对于指针类型，需要获取指向的类型
                    let load_ty = match src_ty {
                        MIRType::Ptr(inner) | MIRType::Ref(inner) => {
                            self.mir_type_to_llvm_cached(inner)
                        }
                        _ => llvm_ty,
                    };
                    self.ir.push_str(&format!(
                        "{} = load {}, {}* {}\n",
                        dest, load_ty, load_ty, src
                    ));
                } else {
                    // 临时变量已经是值，直接复制（使用 add 0, value 模拟 mov）
                    let src = self.local_name(*source);
                    self.ir
                        .push_str(&format!("{} = add i64 0, {}\n", dest, src));
                }
            }
            mir::Instruction::Store { destination, value } => {
                if destination == value {
                    // Redundant self-writeback (`store x -> x`) does not change program state.
                    return Ok(());
                }
                let dest = self.local_name(*destination);
                let val = self.operand_value(*value, mir_fn);
                let ty = self.get_local_type(mir_fn, *value);
                let llvm_ty = self.mir_type_to_llvm_cached(&ty);
                self.emit_indent();
                self.ir.push_str(&format!(
                    "store {} {}, {}* {}\n",
                    llvm_ty, val, llvm_ty, dest
                ));
            }
            mir::Instruction::IndexAddr {
                destination,
                base,
                index,
            } => {
                let dest = self.local_name(*destination);
                let base_reg = self.local_name(*base);

                // 使用 id 直接索引检查是否是用户变量
                let idx_local_info = &mir_fn.locals[index.id].0;

                self.emit_indent();
                if idx_local_info.kind == LocalKind::User {
                    // 用户变量需要先 load
                    let idx_reg = self.local_name(*index);
                    let idx_temp = format!("%idx.{}", destination.id);
                    self.ir
                        .push_str(&format!("{} = load i64, i64* {}\n", idx_temp, idx_reg));
                    self.emit_indent();
                    self.ir.push_str(&format!(
                        "{} = getelementptr i64, i64* {}, i64 {}\n",
                        dest, base_reg, idx_temp
                    ));
                } else {
                    // 临时变量直接使用
                    let idx_reg = self.local_name(*index);
                    self.ir.push_str(&format!(
                        "{} = getelementptr i64, i64* {}, i64 {}\n",
                        dest, base_reg, idx_reg
                    ));
                }
            }
            mir::Instruction::Aggregate {
                destination,
                fields,
                ty,
            } => {
                // 数组/结构体初始化
                let dest = self.local_name(*destination);

                match ty {
                    MIRType::Array(elem_ty, len) => {
                        // 数组初始化：为每个元素生成 store 指令
                        let elem_llvm_ty = self.mir_type_to_llvm_cached(elem_ty);
                        for (i, field_local) in fields.iter().enumerate() {
                            // 获取元素地址
                            let elem_ptr = format!("{}.elem.{}", dest, i);
                            self.emit_indent();
                            self.ir.push_str(&format!(
                                "{} = getelementptr {}, {}* {}, i64 {}\n",
                                elem_ptr, elem_llvm_ty, elem_llvm_ty, dest, i
                            ));

                            // 存储 element 值
                            let field_val = self.operand_value(*field_local, mir_fn);
                            self.emit_indent();
                            self.ir.push_str(&format!(
                                "store {} {}, {}* {}\n",
                                elem_llvm_ty, field_val, elem_llvm_ty, elem_ptr
                            ));
                        }
                    }
                    MIRType::Struct { .. } => {
                        // 结构体初始化：使用 insertvalue 链逐字段构建
                        let llvm_ty = self.mir_type_to_llvm_cached(ty);
                        if fields.is_empty() {
                            self.emit_indent();
                            self.ir
                                .push_str(&format!("{} = alloca {}\n", dest, llvm_ty));
                        } else {
                            let mut current = "undef".to_string();
                            for (i, field_local) in fields.iter().enumerate() {
                                let field_val = self.operand_value(*field_local, mir_fn);
                                let field_ty = self.get_local_type(mir_fn, *field_local);
                                let field_llvm = self.mir_type_to_llvm_cached(&field_ty);
                                let temp = if i < fields.len() - 1 {
                                    format!("{}.f{}", dest, i)
                                } else {
                                    dest.clone()
                                };
                                self.emit_indent();
                                self.ir.push_str(&format!(
                                    "{} = insertvalue {} {}, {} {}, {}\n",
                                    temp, llvm_ty, current, field_llvm, field_val, i
                                ));
                                current = temp;
                            }
                        }
                    }
                    _ => {
                        // 其他类型暂时跳过
                    }
                }
            }
            mir::Instruction::AddrOf {
                destination,
                source,
            } => {
                // 获取变量的地址（& 操作）
                let dest = self.local_name(*destination);
                let src = self.local_name(*source);
                self.emit_indent();
                self.ir
                    .push_str(&format!("{} = bitcast i64* {} to i64\n", dest, src));
            }
            mir::Instruction::Call {
                destination,
                func,
                args,
            } => {
                // 函数调用
                let dest = self.local_name(*destination);
                let dest_ty = self.get_local_type(mir_fn, *destination);
                let ret_ty = self.mir_type_to_llvm_cached(&dest_ty);

                // 检查是否是内置函数 print
                let is_print = func == "print";
                let actual_func = if is_print { "puts" } else { func };

                // 处理参数 — 用户变量需要先 load 再传递
                let mut arg_strs: Vec<String> = Vec::new();
                for arg in args {
                    let arg_local = *arg;
                    let arg_ty = self.get_local_type(mir_fn, arg_local);
                    let llvm_arg_ty = self.mir_type_to_llvm_cached(&arg_ty);
                    let val = self.operand_value(arg_local, mir_fn);
                    arg_strs.push(format!("{} {}", llvm_arg_ty, val));
                }

                self.emit_indent();
                if is_print {
                    // print 函数调用 puts，返回 i32，但我们忽略返回值
                    self.ir
                        .push_str(&format!("call i32 @puts({})\n", arg_strs.join(", ")));
                    // print 返回 ()，所以我们需要设置 dest 为 unit 值
                    self.ir.push_str(&format!("{} = add i8 0, 0\n", dest));
                } else if ret_ty == "void" {
                    self.ir.push_str(&format!(
                        "call void @{}({})\n",
                        actual_func,
                        arg_strs.join(", ")
                    ));
                } else {
                    self.ir.push_str(&format!(
                        "{} = call {} @{}({})\n",
                        dest,
                        ret_ty,
                        actual_func,
                        arg_strs.join(", ")
                    ));
                }
            }
            mir::Instruction::Discriminant {
                destination,
                source,
            } => {
                // 获取枚举的判别值
                // 在 LLVM 中，枚举表示为 { 判别值, 载荷 } 的结构体
                // 判别值通常是第一个字段（索引 0）
                let dest = self.local_name(*destination);
                let src = self.local_name(*source);

                // 使用 extractvalue 提取判别值
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = extractvalue {{ i64, i64 }} {}, 0\n",
                    dest, src
                ));
            }
            mir::Instruction::EnumConstruct {
                destination,
                discriminant,
                payload,
                enum_type: _,
            } => {
                // 构造枚举值
                // 在 LLVM 中表示为 { 判别值, 载荷 }
                let dest = self.local_name(*destination);

                // 首先插入判别值
                let discr_value = format!("{}.discr", dest);
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = insertvalue {{ i64, i64 }} undef, i64 {}, 0\n",
                    discr_value, discriminant
                ));

                // 然后插入载荷（如果有）
                if let Some(payload_local) = payload {
                    let payload_val = self.operand_value(*payload_local, mir_fn);
                    self.emit_indent();
                    self.ir.push_str(&format!(
                        "{} = insertvalue {{ i64, i64 }} {}, i64 {}, 1\n",
                        dest, discr_value, payload_val
                    ));
                } else {
                    // 没有载荷，载荷字段为未定义
                    self.emit_indent();
                    self.ir.push_str(&format!(
                        "{} = insertvalue {{ i64, i64 }} {}, i64 undef, 1\n",
                        dest, discr_value
                    ));
                }
            }
            mir::Instruction::ExtractPayload {
                destination,
                source,
            } => {
                // 从枚举中提取载荷
                let dest = self.local_name(*destination);
                let src = self.local_name(*source);

                // 载荷是第二个字段（索引 1）
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = extractvalue {{ i64, i64 }} {}, 1\n",
                    dest, src
                ));
            }
            mir::Instruction::Cast {
                destination,
                value,
                to,
            } => {
                let dest = self.local_name(*destination);
                let src_val = self.operand_value(*value, mir_fn);
                let src_ty = self.get_local_type(mir_fn, *value);
                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);
                let dst_llvm = self.mir_type_to_llvm_cached(to);

                self.emit_indent();
                match (&src_ty, to) {
                    // Int → Int: sext (sign-extend) for widening, trunc for narrowing
                    (MIRType::Int(a), MIRType::Int(b)) if a < b => {
                        self.ir.push_str(&format!(
                            "{} = sext {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    (MIRType::Int(a), MIRType::Int(b)) if a > b => {
                        self.ir.push_str(&format!(
                            "{} = trunc {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    // Float → Float: fpext for widening, fptrunc for narrowing
                    (MIRType::Float(a), MIRType::Float(b)) if a < b => {
                        self.ir.push_str(&format!(
                            "{} = fpext {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    (MIRType::Float(a), MIRType::Float(b)) if a > b => {
                        self.ir.push_str(&format!(
                            "{} = fptrunc {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    // Int → Float: sitofp (signed int to floating point)
                    (MIRType::Int(_), MIRType::Float(_)) => {
                        self.ir.push_str(&format!(
                            "{} = sitofp {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    // Float → Int: fptosi (floating point to signed int)
                    (MIRType::Float(_), MIRType::Int(_)) => {
                        self.ir.push_str(&format!(
                            "{} = fptosi {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    // Bool → Int: zext (zero-extend i1 to iN)
                    (MIRType::Bool, MIRType::Int(_)) => {
                        self.ir.push_str(&format!(
                            "{} = zext {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    // Int → Bool: trunc (iN to i1)
                    (MIRType::Int(_), MIRType::Bool) => {
                        self.ir.push_str(&format!(
                            "{} = trunc {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                    // Same type or unsupported: bitcast as fallback
                    _ => {
                        self.ir.push_str(&format!(
                            "{} = bitcast {} {} to {}\n",
                            dest, src_llvm, src_val, dst_llvm
                        ));
                    }
                }
            }
            mir::Instruction::FieldAddr {
                destination,
                base,
                field,
            } => {
                let dest = self.local_name(*destination);
                let base_reg = self.local_name(*base);
                let base_ty = self.get_local_type(mir_fn, *base);
                let base_llvm = self.mir_type_to_llvm_cached(&base_ty);
                self.emit_indent();
                // FieldAddr gets a pointer to a field within an aggregate type
                // Use getelementptr to compute the field address
                self.ir.push_str(&format!(
                    "{} = getelementptr inbounds {}, {}* {}, i32 0, i32 {}\n",
                    dest, base_llvm, base_llvm, base_reg, field
                ));
            }
            mir::Instruction::Extract {
                destination,
                value,
                index,
            } => {
                let dest = self.local_name(*destination);
                let src_val = self.operand_value(*value, mir_fn);
                let src_ty = self.get_local_type(mir_fn, *value);
                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = extractvalue {} {}, {}\n",
                    dest, src_llvm, src_val, index
                ));
            }
            mir::Instruction::Insert {
                destination,
                value,
                field,
                new_value,
            } => {
                let dest = self.local_name(*destination);
                let src_val = self.operand_value(*value, mir_fn);
                let src_ty = self.get_local_type(mir_fn, *value);
                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);
                let new_val = self.operand_value(*new_value, mir_fn);
                let new_ty = self.get_local_type(mir_fn, *new_value);
                let new_llvm = self.mir_type_to_llvm_cached(&new_ty);
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = insertvalue {} {}, {} {}, {}\n",
                    dest, src_llvm, src_val, new_llvm, new_val, field
                ));
            }
            mir::Instruction::Intrinsic {
                destination,
                intrinsic,
                args,
            } => {
                // Generate inline code for intrinsic operations
                match intrinsic {
                    mir::IntrinsicOp::AddWithOverflow => {
                        if args.len() >= 2 {
                            let left_val = self.operand_value(args[0], mir_fn);
                            let right_val = self.operand_value(args[1], mir_fn);
                            if let Some(dest) = destination {
                                let dest_name = self.local_name(*dest);
                                self.emit_indent();
                                self.ir.push_str(&format!(
                                    "{} = add i64 {}, {}\n",
                                    dest_name, left_val, right_val
                                ));
                            }
                        }
                    }
                    mir::IntrinsicOp::SubWithOverflow => {
                        if args.len() >= 2 {
                            let left_val = self.operand_value(args[0], mir_fn);
                            let right_val = self.operand_value(args[1], mir_fn);
                            if let Some(dest) = destination {
                                let dest_name = self.local_name(*dest);
                                self.emit_indent();
                                self.ir.push_str(&format!(
                                    "{} = sub i64 {}, {}\n",
                                    dest_name, left_val, right_val
                                ));
                            }
                        }
                    }
                    mir::IntrinsicOp::MulWithOverflow => {
                        if args.len() >= 2 {
                            let left_val = self.operand_value(args[0], mir_fn);
                            let right_val = self.operand_value(args[1], mir_fn);
                            if let Some(dest) = destination {
                                let dest_name = self.local_name(*dest);
                                self.emit_indent();
                                self.ir.push_str(&format!(
                                    "{} = mul i64 {}, {}\n",
                                    dest_name, left_val, right_val
                                ));
                            }
                        }
                    }
                    mir::IntrinsicOp::Copy { size, .. } => {
                        if args.len() >= 2 {
                            let dest_ptr = self.operand_value(args[0], mir_fn);
                            let src_ptr = self.operand_value(args[1], mir_fn);
                            self.emit_indent();
                            self.ir.push_str(&format!("call void @llvm.memcpy.p0i8.p0i8.i64(i8* {}, i8* {}, i64 {}, i1 false)\n", dest_ptr, src_ptr, size));
                        }
                    }
                    mir::IntrinsicOp::Compare { size, .. } => {
                        if args.len() >= 2 {
                            let left_ptr = self.operand_value(args[0], mir_fn);
                            let right_ptr = self.operand_value(args[1], mir_fn);
                            if let Some(dest) = destination {
                                let dest_name = self.local_name(*dest);
                                self.emit_indent();
                                self.ir.push_str(&format!(
                                    "{} = call i32 @memcmp(i8* {}, i8* {}, i64 {})\n",
                                    dest_name, left_ptr, right_ptr, size
                                ));
                            }
                        }
                    }
                    mir::IntrinsicOp::MemMove { size, .. } => {
                        if args.len() >= 2 {
                            let dest_ptr = self.operand_value(args[0], mir_fn);
                            let src_ptr = self.operand_value(args[1], mir_fn);
                            self.emit_indent();
                            self.ir.push_str(&format!("call void @llvm.memmove.p0i8.p0i8.i64(i8* {}, i8* {}, i64 {}, i1 false)\n", dest_ptr, src_ptr, size));
                        }
                    }
                }
            }
            mir::Instruction::Phi {
                destination,
                incoming,
            } => {
                let dest = self.local_name(*destination);
                let ty = self.get_local_type(mir_fn, *destination);
                let is_void_like = match &ty {
                    MIRType::Unit | MIRType::Never => true,
                    MIRType::Tuple(fields) if fields.is_empty() => true,
                    _ => false,
                };
                if is_void_like {
                    // LLVM does not allow `phi void`.
                    return Ok(());
                }
                let llvm_ty = self.mir_type_to_llvm_cached(&ty);

                let entries: Vec<String> = incoming
                    .iter()
                    .map(|(local, block_idx)| {
                        let val = self.local_name(*local);
                        format!("[ {}, %bb_{} ]", val, block_idx)
                    })
                    .collect();

                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = phi {} {}\n",
                    dest,
                    llvm_ty,
                    entries.join(", ")
                ));
            }
        }
        Ok(())
    }

    fn codegen_terminator(
        &mut self,
        terminator: &mir::Terminator,
        mir_fn: &MirFunction,
    ) -> Result<(), String> {
        match terminator {
            mir::Terminator::Return(value) => {
                if let Some(v) = value {
                    let ty = self.get_local_type(mir_fn, *v);
                    // 特殊处理：main 函数返回 unit 类型时，返回 0 而不是 unit 值
                    let is_main_returning_unit =
                        mir_fn.name == "main" && matches!(ty, MIRType::Unit);

                    if is_main_returning_unit {
                        self.emit_indent();
                        self.ir.push_str("ret i64 0\n");
                    } else {
                        // 检查是否是用户变量，如果是则需要先 load
                        let reg = self.operand_value(*v, mir_fn);
                        // 对于 unit 类型，使用 i8 而不是 void
                        let llvm_ty = if matches!(ty, MIRType::Unit) {
                            "i8".to_string()
                        } else {
                            self.mir_type_to_llvm_cached(&ty)
                        };
                        self.emit_indent();
                        self.ir.push_str(&format!("ret {} {}\n", llvm_ty, reg));
                    }
                } else {
                    // 对于 main 函数，默认返回 0
                    if mir_fn.name == "main" {
                        self.emit_indent();
                        self.ir.push_str("ret i64 0\n");
                    } else {
                        self.emit_indent();
                        self.ir.push_str("ret void\n");
                    }
                }
            }
            mir::Terminator::Goto(target) => {
                self.emit_indent();
                self.ir.push_str(&format!("br label %bb_{}\n", target));
            }
            mir::Terminator::If {
                cond: condition,
                then_block,
                else_block,
            } => {
                self.emit_indent();
                let cond_reg = self.local_name(*condition);
                self.ir.push_str(&format!(
                    "br i1 {}, label %bb_{}, label %bb_{}\n",
                    cond_reg, then_block, else_block
                ));
            }
            mir::Terminator::Switch {
                discr,
                targets,
                otherwise,
            } => {
                self.emit_indent();
                let discr_reg = self.local_name(*discr);

                // 生成 switch 指令
                self.ir.push_str(&format!(
                    "switch i64 {}, label %bb_{} [",
                    discr_reg, otherwise
                ));

                // 添加每个 case
                for (value, target) in targets {
                    self.ir.push_str(&format!("\n"));
                    self.emit_indent();
                    self.ir
                        .push_str(&format!("  i64 {}, label %bb_{}", value, target));
                }

                self.ir.push_str(&format!("\n"));
                self.emit_indent();
                self.ir.push_str("]\n");
            }
            mir::Terminator::Break { target } => {
                self.emit_indent();
                self.ir.push_str(&format!("br label %bb_{}\n", target));
            }
            mir::Terminator::Continue { target } => {
                self.emit_indent();
                self.ir.push_str(&format!("br label %bb_{}\n", target));
            }
            mir::Terminator::Unreachable => {
                self.emit_indent();
                self.ir.push_str("unreachable\n");
            }
            mir::Terminator::Call {
                func,
                args,
                destination,
                target,
            } => {
                let dest = self.local_name(*destination);
                let dest_ty = self.get_local_type(mir_fn, *destination);
                let ret_ty = self.mir_type_to_llvm_cached(&dest_ty);

                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|arg| match arg {
                        mir::CallArg::Local(local) => {
                            let arg_ty = self.get_local_type(mir_fn, *local);
                            let llvm_arg_ty = self.mir_type_to_llvm_cached(&arg_ty);
                            let val = self.operand_value(*local, mir_fn);
                            format!("{} {}", llvm_arg_ty, val)
                        }
                        mir::CallArg::Constant(constant) => match constant {
                            MirConstant::Int(n) => format!("i64 {}", n),
                            MirConstant::Bool(b) => format!("i1 {}", if *b { 1 } else { 0 }),
                            MirConstant::Float(f) => format!("double {}", f),
                            MirConstant::String(s) => format!(
                                "i8* @.str.{}",
                                self.strings.iter().position(|x| x == s).unwrap_or(0)
                            ),
                            _ => "i64 0".to_string(),
                        },
                    })
                    .collect();

                self.emit_indent();
                if ret_ty == "void" {
                    self.ir
                        .push_str(&format!("call void @{}({})\n", func, arg_strs.join(", ")));
                } else {
                    self.ir.push_str(&format!(
                        "{} = call {} @{}({})\n",
                        dest,
                        ret_ty,
                        func,
                        arg_strs.join(", ")
                    ));
                }
                self.emit_indent();
                self.ir.push_str(&format!("br label %bb_{}\n", target));
            }
        }
        Ok(())
    }

    /// 在 codegen_function 开始时，预计算所有 local 的名称
    pub(crate) fn build_name_cache(&mut self, mir_fn: &MirFunction) {
        self.name_cache.clear();
        // Find the maximum local id to size the cache
        let max_id = mir_fn.locals.iter().map(|(l, _)| l.id).max().unwrap_or(0);
        // Pre-fill with empty strings up to max_id + 1
        self.name_cache.resize(max_id + 1, String::new());
        for (local, _ty) in &mir_fn.locals {
            // Delegate to shared utility for name generation
            self.name_cache[local.id] = common::local_name(*local);
        }
    }

    fn local_name(&self, local: Local) -> String {
        if local.id < self.name_cache.len() && !self.name_cache[local.id].is_empty() {
            self.name_cache[local.id].clone()
        } else {
            // Fallback to shared utility when cache isn't available
            common::local_name(local)
        }
    }

    fn emit_indent(&mut self) {
        common::emit_indent(&mut self.ir, self.indent);
    }

    /// 带缓存的类型转换：检查缓存后再计算，避免重复转换相同的 MIR 类型
    fn mir_type_to_llvm_cached(&mut self, ty: &MIRType) -> String {
        if let Some(cached) = self.type_str_cache.get(ty) {
            return cached.clone();
        }
        // Delegate to shared utility for cache misses
        let result = common::mir_type_to_llvm_str(ty);
        self.type_str_cache.insert(ty.clone(), result.clone());
        result
    }

    fn get_local_type(&self, mir_fn: &MirFunction, local: Local) -> MIRType {
        // 使用 id 直接索引，而不是比较 Local 对象
        mir_fn
            .locals
            .get(local.id)
            .map(|(_, ty)| ty.clone())
            .unwrap_or(MIRType::Int(64))
    }

    /// 获取操作数的值寄存器
    /// 如果操作数是用户变量（alloca），则生成 load 指令并返回临时寄存器名
    /// 否则直接返回寄存器名
    fn operand_value(&mut self, local: Local, mir_fn: &MirFunction) -> String {
        // 使用 id 直接索引，O(1) 查找 local 的类型信息
        let local_info = &mir_fn.locals[local.id].0;

        match local_info.kind {
            LocalKind::User => {
                // 用户变量需要先 load — 使用实际 MIR 类型而非硬编码 i64
                let ty = self.get_local_type(mir_fn, local);
                let llvm_ty = self.mir_type_to_llvm_cached(&ty);
                let temp_reg = format!("%load.{}", self.load_counter);
                self.load_counter += 1;
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = load {}, {}* {}\n",
                    temp_reg,
                    llvm_ty,
                    llvm_ty,
                    self.local_name(local)
                ));
                temp_reg
            }
            _ => {
                // 参数、临时变量等直接使用寄存器名
                self.local_name(local)
            }
        }
    }
}
