pub mod common;

pub mod jit;



pub use jit::JITCodegen;



use crate::mir::{self, Local, LocalKind, MIRType, MirConstant, MirFunction, MIR_I64};

use std::collections::{HashMap, HashSet};

use std::io::Write;



#[derive(Debug, Clone)]

pub struct ExternDecl {

    pub name: String,

    pub abi: String,

    pub link_name: Option<String>,

    pub params: Vec<MIRType>,

    pub ret: MIRType,

}



#[derive(Debug, Clone)]

pub struct ExportSymbol {

    pub internal_name: String,

    pub export_name: String,

}



#[derive(Debug, Clone, Default)]

pub struct FfiCodegenConfig {

    pub extern_decls: Vec<ExternDecl>,

    pub export_symbols: Vec<ExportSymbol>,

}



pub struct Codegen {

    ir: String,

    indent: usize,

    declarations: String,

    ffi: FfiCodegenConfig,

    /// 字符串常量池。
    strings: Vec<String>,

    /// 字符串常量计数器。

    string_counter: usize,

    /// 按 `local.id` 缓存生成好的局部变量名，避免重复拼接。
    pub(crate) name_cache: Vec<String>,

    /// 缓存 MIR 类型到 LLVM 类型字符串的映射。

    type_str_cache: HashMap<MIRType, String>,

    /// 为 `load` 指令生成唯一的 SSA 临时寄存器名。

    load_counter: usize,

}



impl Codegen {

    pub fn new() -> Self {

        Self::with_ffi(FfiCodegenConfig::default())

    }



    pub fn with_ffi(ffi: FfiCodegenConfig) -> Self {

        let mut cg = Self {

            ir: String::new(),

            indent: 0,

            declarations: String::new(),

            ffi,

            strings: Vec::new(),

            string_counter: 0,

            name_cache: Vec::new(),

            type_str_cache: HashMap::new(),

            load_counter: 0,

        };

        cg.emit_header();

        cg.declare_runtime_functions();

        cg

    }



    fn emit_header(&mut self) {

        // 模块级头信息先写入 declarations 缓冲区，保证位于函数 IR 之前。
        self.declarations.push_str("; Sengoo LLVM IR\n");

        self.declarations

            .push_str("; Generated by Sengoo Compiler\n\n");



        // 根据目标平台设置 target triple，避免 clang 报 `-Woverride-module`。

        if cfg!(target_os = "windows") {

            self.declarations

                .push_str("target triple = \"x86_64-pc-windows-msvc\"\n\n");

        } else if cfg!(target_os = "macos") {

            self.declarations

                .push_str("target triple = \"x86_64-apple-macosx\"\n\n");

        } else {

            self.declarations

                .push_str("target triple = \"x86_64-unknown-linux-gnu\"\n\n");

        }

    }



    /// 声明运行时和外部 C 函数。
    fn declare_runtime_functions(&mut self) {

        self.declarations

            .push_str("; External C library functions\n");

        self.declarations.push_str("declare i32 @puts(i8*)\n");

        self.declarations

            .push_str("declare i32 @printf(i8*, ...)\n");

        self.declarations.push_str("\n");



        // Sengoo runtime print functions

        self.declarations

            .push_str("; Sengoo runtime print functions\n");

        self.declarations

            .push_str("declare void @sengoo_print_i64(i64)\n");

        self.declarations

            .push_str("declare void @sengoo_print_bool(i64)\n");

        self.declarations

            .push_str("declare void @sengoo_print_f64(double)\n");

        self.declarations

            .push_str("declare void @sengoo_print_str(i8*)\n");

        self.declarations.push_str("\n");



        // Sengoo runtime string functions

        self.declarations

            .push_str("; Sengoo runtime string functions\n");

        self.declarations

            .push_str("declare i64 @sengoo_str_len(i8*)\n");

        self.declarations

            .push_str("declare i8* @sengoo_str_concat(i8*, i8*)\n");

        self.declarations

            .push_str("declare i64 @sengoo_str_eq(i8*, i8*)\n");

        self.declarations.push_str("\n");



        self.declarations
            .push_str("; Sengoo async runtime functions\n");
        self.declarations
            .push_str("declare i64 @sengoo_async_frame_alloc(i64)\n");
        self.declarations
            .push_str("declare void @sengoo_async_frame_free(i64)\n");
        self.declarations
            .push_str("declare void @sengoo_async_frame_store(i64, i64, i64)\n");
        self.declarations
            .push_str("declare i64 @sengoo_async_frame_load(i64, i64)\n");
        self.declarations
            .push_str("declare i64 @sengoo_async_run_main_i64(i64)\n");
        self.declarations.push_str("\n");

        self.declare_user_extern_functions();

    }



    fn declare_user_extern_functions(&mut self) {

        if self.ffi.extern_decls.is_empty() {

            return;

        }



        self.declarations

            .push_str("; User-declared extern FFI functions\n");

        let mut seen = HashSet::new();

        let extern_decls = self.ffi.extern_decls.clone();



        for decl in extern_decls {

            if !seen.insert(decl.name.clone()) {

                continue;

            }



            if let Some(link_name) = &decl.link_name {

                self.declarations

                    .push_str(&format!("; link(name = \"{}\")\n", link_name));

            }

            self.declarations

                .push_str(&format!("; ABI: {}\n", decl.abi.as_str()));



            let ret = self.mir_type_to_llvm_cached(&decl.ret);

            let params = decl

                .params

                .iter()

                .map(|p| self.mir_type_to_llvm_cached(p))

                .collect::<Vec<_>>()

                .join(", ");

            self.declarations

                .push_str(&format!("declare {} @{}({})\n", ret, decl.name, params));

        }



        self.declarations.push_str("\n");

    }



    /// 输出字符串常量定义。
    fn emit_string_constants(&mut self) {

        if !self.strings.is_empty() {

            self.declarations.push_str("; String Constants\n");

            for (i, s) in self.strings.iter().enumerate() {

                // 转义反斜杠和双引号。
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");

                self.declarations.push_str(&format!(

                    "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\"\n",

                    i,

                    s.len() + 1,

                    escaped

                ));

            }

            self.declarations.push_str("\n");

        }

    }



    /// 注册字符串常量并返回其全局符号名。

    fn add_string(&mut self, s: &str) -> String {

        let idx = self.string_counter;

        self.string_counter += 1;

        self.strings.push(s.to_string());

        format!("@.str.{}", idx)

    }



    /// 扫描 MIR 中出现的结构体类型，并预先生成 LLVM named struct type。

    fn emit_struct_types(&mut self, mir_fns: &[MirFunction]) {

        let mut seen = HashSet::new();

        for func in mir_fns {

            for (_, ty) in &func.locals {

                self.collect_struct_types(ty, &mut seen);

            }

        }

    }



    /// 递归收集结构体字段中嵌套的 LLVM named type。

    fn collect_struct_types(&mut self, ty: &MIRType, seen: &mut HashSet<String>) {

        match ty {

            MIRType::Struct { name, fields } => {

                if seen.insert(name.clone()) {

                    // 先递归处理字段里的嵌套结构体类型。

                    for (_, ft) in fields {

                        self.collect_struct_types(ft, seen);

                    }

                    let field_types: Vec<String> = fields

                        .iter()

                        .map(|(_, ft)| self.mir_type_to_llvm_cached(ft))

                        .collect();

                    self.declarations.push_str(&format!(

                        "%{} = type {{ {} }}\n",

                        name,

                        field_types.join(", ")

                    ));

                }

            }

            // Recurse into composite types that may contain structs

            MIRType::Array(elem, _) | MIRType::Ptr(elem) | MIRType::Ref(elem) => {

                self.collect_struct_types(elem, seen);

            }

            MIRType::Tuple(types) => {

                for t in types {

                    self.collect_struct_types(t, seen);

                }

            }

            _ => {}

        }

    }



    /// Estimate the IR buffer capacity based on MIR function metrics.

    /// This avoids repeated reallocations during IR generation.

    fn estimate_ir_capacity(mir_fns: &[MirFunction]) -> usize {

        let mut estimate = 1024; // Base overhead for header, runtime declarations, etc.

        for func in mir_fns {

            // Each local ~30 bytes (alloca declaration)

            estimate += func.locals.len() * 30;

            // Each basic block ~20 bytes (label)

            estimate += func.basic_blocks.len() * 20;

            // Each instruction ~60 bytes of IR text

            for bb in &func.basic_blocks {

                estimate += bb.instructions.len() * 60;

                // Terminator ~40 bytes

                if bb.terminator.is_some() {

                    estimate += 40;

                }

            }

            // Function header/footer overhead (~80 bytes for define, params, closing brace)

            estimate += 80;

        }

        estimate

    }



    fn prepare_codegen_buffers(&mut self) {

        self.ir.clear();

        self.declarations.clear();

        self.strings.clear();

        self.string_counter = 0;

        self.name_cache.clear();

        self.type_str_cache.clear();

        self.load_counter = 0;

        self.emit_header();

        self.declare_runtime_functions();

    }



    fn emit_module_ir(&mut self, mir_fns: &[MirFunction]) -> Result<(), String> {

        self.prepare_codegen_buffers();

        // Pre-allocate IR buffer based on MIR size estimate to reduce reallocations

        let capacity = Self::estimate_ir_capacity(mir_fns);

        self.ir.reserve(capacity);



        // 棣栧厛鏀堕泦鎵€鏈夊瓧绗︿覆甯搁噺

        for mir_fn in mir_fns {

            self.collect_string_constants(mir_fn);

        }

        // 输出收集到的字符串常量。
        self.emit_string_constants();



        // 输出 MIR 中引用到的结构体类型定义。
        self.emit_struct_types(mir_fns);



        // 为模块中的每个函数生成 LLVM IR。

        for mir_fn in mir_fns {

            self.codegen_function(mir_fn)?;

        }

        self.emit_export_symbol_wrappers(mir_fns);

        Ok(())

    }



    fn emit_export_symbol_wrappers(&mut self, mir_fns: &[MirFunction]) {

        if self.ffi.export_symbols.is_empty() {

            return;

        }



        let mut emitted = HashSet::new();

        let export_symbols = self.ffi.export_symbols.clone();

        for export in export_symbols {

            if export.export_name == export.internal_name {

                continue;

            }

            if !emitted.insert(export.export_name.clone()) {

                continue;

            }



            let Some(target) = mir_fns.iter().find(|f| f.name == export.internal_name) else {

                continue;

            };



            let ret_ty = self.mir_type_to_llvm_cached(&target.return_type);

            let params = target

                .params

                .iter()

                .enumerate()

                .map(|(idx, ty)| {

                    let llvm = self.mir_type_to_llvm_cached(ty);

                    format!("{} %arg_{}", llvm, idx)

                })

                .collect::<Vec<_>>();

            let args = target

                .params

                .iter()

                .enumerate()

                .map(|(idx, ty)| {

                    let llvm = self.mir_type_to_llvm_cached(ty);

                    format!("{} %arg_{}", llvm, idx)

                })

                .collect::<Vec<_>>();



            self.ir.push_str("\n");

            self.ir.push_str(&format!(

                "; Export wrapper: {} -> {}\n",

                export.internal_name, export.export_name

            ));

            self.ir.push_str(&format!(

                "define {} @{}({}) {{\n",

                ret_ty,

                export.export_name,

                params.join(", ")

            ));

            self.indent += 1;

            self.emit_indent();

            if ret_ty == "void" {

                self.ir.push_str(&format!(

                    "call void {}({})\n",

                    export.internal_name,

                    args.join(", ")

                ));

                self.emit_indent();

                self.ir.push_str("ret void\n");

            } else {

                self.ir.push_str(&format!(

                    "%export_ret = call {} @{}({})\n",

                    ret_ty,

                    export.internal_name,

                    args.join(", ")

                ));

                self.emit_indent();

                self.ir.push_str(&format!("ret {} %export_ret\n", ret_ty));

            }

            self.indent -= 1;

            self.ir.push_str("}\n");

        }

    }



    pub fn codegen(&mut self, mir_fns: &[MirFunction]) -> Result<String, String> {

        self.emit_module_ir(mir_fns)?;

        let mut result = String::with_capacity(self.declarations.len() + self.ir.len());

        result.push_str(&self.declarations);

        result.push_str(&self.ir);

        Ok(result)

    }



    pub fn codegen_to_writer<W: Write>(

        &mut self,

        mir_fns: &[MirFunction],

        writer: &mut W,

    ) -> Result<(), String> {

        self.emit_module_ir(mir_fns)?;

        writer

            .write_all(self.declarations.as_bytes())

            .map_err(|e| format!("failed to write declarations: {}", e))?;

        writer

            .write_all(self.ir.as_bytes())

            .map_err(|e| format!("failed to write function IR: {}", e))?;

        writer

            .flush()

            .map_err(|e| format!("failed to flush LLVM IR output: {}", e))?;

        Ok(())

    }



    /// 收集函数中使用到的字符串常量。
    fn collect_string_constants(&mut self, mir_fn: &MirFunction) {

        for bb in &mir_fn.basic_blocks {

            for inst in mir_fn.block_instructions(bb) {

                if let mir::Instruction::Assign {

                    value: mir::MirConstant::String(s),

                    ..

                } = inst

                {

                    self.add_string(s);

                }

            }

        }

    }



    fn codegen_function(&mut self, mir_fn: &MirFunction) -> Result<(), String> {

        // Pre-compute all local names for O(1) lookup

        self.build_name_cache(mir_fn);

        // Reset load counter per function for clean SSA naming

        self.load_counter = 0;



        self.ir.push_str("\n");

        self.ir.push_str(&format!("; Function: {}\n", mir_fn.name));

        let return_type = self.mir_type_to_llvm_cached(&mir_fn.return_type);

        self.ir

            .push_str(&format!("define {} @{}(", return_type, mir_fn.name));

        for (i, ty) in mir_fn.params.iter().enumerate() {

            let param_name = format!("%l_{}", i + 1);

            if i > 0 {

                self.ir.push_str(", ");

            }

            let param_ty = self.mir_type_to_llvm_cached(ty);

            self.ir.push_str(&format!("{} {}", param_ty, param_name));

        }

        self.ir.push_str(") {\n");

        self.indent += 1;



        // Track which locals need alloca (user variables only)

        let user_locals: Vec<_> = mir_fn

            .locals

            .iter()

            .filter(|(l, _)| l.kind == LocalKind::User)

            .collect();



        for bb in &mir_fn.basic_blocks {

            let allocas: Vec<(Local, MIRType)> = if bb.id == 0 {

                user_locals.iter().map(|(l, t)| (*l, t.clone())).collect()

            } else {

                vec![]

            };

            self.codegen_basic_block(mir_fn, bb, &allocas)?;

        }

        self.indent -= 1;

        self.ir.push_str("}\n");

        Ok(())

    }



    fn codegen_basic_block(

        &mut self,

        mir_fn: &MirFunction,

        bb: &mir::BasicBlock,

        allocas: &[(Local, MIRType)],

    ) -> Result<(), String> {

        self.ir.push_str(&format!("bb_{}:\n", bb.id));

        self.indent += 1;



        // Emit allocas at the start of the entry block (before any instructions)

        for (local, ty) in allocas {

            let local_name = self.local_name(*local);

            let llvm_ty = self.mir_type_to_llvm_cached(ty);

            self.emit_indent();

            self.ir

                .push_str(&format!("{} = alloca {}\n", local_name, llvm_ty));

        }



        for inst_id in &bb.instructions {

            let inst = mir_fn.instruction(*inst_id);

            self.codegen_instruction(inst, mir_fn)?;

        }

        if let Some(terminator) = &bb.terminator {

            self.codegen_terminator(terminator, mir_fn)?;

        }

        self.indent -= 1;

        Ok(())

    }



    fn codegen_instruction(

        &mut self,

        inst: &mir::Instruction,

        mir_fn: &MirFunction,

    ) -> Result<(), String> {

        match inst {

            mir::Instruction::Nop => {}

            mir::Instruction::Assign { destination, value } => {

                let dest = self.local_name(*destination);

                self.emit_indent();

                match value {

                    mir::MirConstant::Int(n) => {

                        self.ir.push_str(&format!("{} = add i64 0, {}\n", dest, n));

                    }

                    mir::MirConstant::Uint(n) => {

                        self.ir.push_str(&format!("{} = add i64 0, {}\n", dest, n));

                    }

                    mir::MirConstant::Bool(b) => {

                        self.ir.push_str(&format!(

                            "{} = add i1 0, {}\n",

                            dest,

                            if *b { 1 } else { 0 }

                        ));

                    }

                    mir::MirConstant::Float(f) => {

                        self.ir

                            .push_str(&format!("{} = fadd double 0.0, {}\n", dest, f));

                    }

                    mir::MirConstant::Char(c) => {

                        self.ir

                            .push_str(&format!("{} = add i8 0, {}\n", dest, *c as i8));

                    }

                    mir::MirConstant::String(s) => {

                        // 将字符串常量映射到已注册的全局字符串符号。

                        let str_idx = self.strings.iter().position(|x| x == s).unwrap_or(0);

                        let str_ref = format!("@.str.{}", str_idx);

                        self.ir.push_str(&format!(

                            "{} = bitcast [{} x i8]* {} to i8*\n",

                            dest,

                            s.len() + 1,

                            str_ref

                        ));

                    }

                    mir::MirConstant::Bytes(_) => {

                        self.ir.push_str(&format!("{} = add i64 0, 0\n", dest));

                    }

                    mir::MirConstant::GlobalRef(name) => {
                        let dest_ty = self.get_local_type(mir_fn, *destination);
                        let llvm_dest_ty = self.mir_type_to_llvm_cached(&dest_ty);
                        if matches!(dest_ty, MIRType::Fn { .. }) {
                            self.ir.push_str(&format!(
                                "{} = bitcast {} @{} to {}
",
                                dest, llvm_dest_ty, name, llvm_dest_ty
                            ));
                        } else {
                            self.ir
                                .push_str(&format!("{} = bitcast i64* @{} to i64
", dest, name));
                        }
                    }

                    mir::MirConstant::Unit => {

                        self.ir.push_str(&format!("{} = add i8 0, 0\n", dest));

                    }

                }

            }

            mir::Instruction::Unary {

                destination,

                op,

                operand,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*operand, mir_fn);

                self.emit_indent();

                match op {

                    mir::MirUnOp::Neg => {

                        self.ir

                            .push_str(&format!("{} = sub i64 0, {}\n", dest, src_val));

                    }

                    mir::MirUnOp::Not => {

                        self.ir

                            .push_str(&format!("{} = xor i1 {}, true\n", dest, src_val));

                    }

                    mir::MirUnOp::BitNot => {

                        self.ir

                            .push_str(&format!("{} = xor i64 {}, -1\n", dest, src_val));

                    }

                }

            }

            mir::Instruction::Binary {

                destination,

                op,

                left,

                right,

            } => {

                let dest = self.local_name(*destination);

                // 濡傛灉鎿嶄綔鏁版槸鐢ㄦ埛鍙橀噺锛岄渶瑕佸厛 load

                let left_val = self.operand_value(*left, mir_fn);

                let right_val = self.operand_value(*right, mir_fn);

                self.emit_indent();

                match op {

                    mir::MirBinOp::Add => {

                        self.ir

                            .push_str(&format!("{} = add i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Sub => {

                        self.ir

                            .push_str(&format!("{} = sub i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Mul => {

                        self.ir

                            .push_str(&format!("{} = mul i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Div => {

                        self.ir.push_str(&format!(

                            "{} = sdiv i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Rem => {

                        self.ir.push_str(&format!(

                            "{} = srem i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Eq => {

                        self.ir.push_str(&format!(

                            "{} = icmp eq i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Ne => {

                        self.ir.push_str(&format!(

                            "{} = icmp ne i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Lt => {

                        self.ir.push_str(&format!(

                            "{} = icmp slt i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Le => {

                        self.ir.push_str(&format!(

                            "{} = icmp sle i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Gt => {

                        self.ir.push_str(&format!(

                            "{} = icmp sgt i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Ge => {

                        self.ir.push_str(&format!(

                            "{} = icmp sge i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::BitAnd => {

                        self.ir

                            .push_str(&format!("{} = and i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::BitOr => {

                        self.ir

                            .push_str(&format!("{} = or i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::BitXor => {

                        self.ir

                            .push_str(&format!("{} = xor i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Shl => {

                        self.ir

                            .push_str(&format!("{} = shl i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Shr => {

                        self.ir.push_str(&format!(

                            "{} = ashr i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::LogAnd => {

                        self.ir

                            .push_str(&format!("{} = and i1 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::LogOr => {

                        self.ir

                            .push_str(&format!("{} = or i1 {}, {}\n", dest, left_val, right_val));

                    }

                }

            }

            mir::Instruction::Load {

                destination,

                source,

            } => {

                let dest = self.local_name(*destination);

                // 浣跨敤 id 鐩存帴绱㈠紩锛孫(1) 鏌ユ壘

                let (local_info, src_ty) = &mir_fn.locals[source.index()];



                self.emit_indent();

                // 根据源 local 的 kind 和类型判断这一条是否需要真正发出 load。
                // 1. 用户变量通常对应 alloca，读取时需要 load。

                // 2. 指针或引用类型也需要 load，才能得到其指向的值。

                let needs_load = local_info.kind == LocalKind::User

                    || matches!(src_ty, MIRType::Ptr(_) | MIRType::Ref(_));



                if needs_load {

                    let src = self.local_name(*source);

                    let llvm_ty = self.mir_type_to_llvm_cached(src_ty);

                    // load 的类型取决于源操作数实际指向的元素类型。

                    let load_ty = match src_ty {

                        MIRType::Ptr(inner) | MIRType::Ref(inner) => {

                            self.mir_type_to_llvm_cached(inner)

                        }

                        _ => llvm_ty,

                    };

                    self.ir.push_str(&format!(

                        "{} = load {}, {}* {}\n",

                        dest, load_ty, load_ty, src

                    ));

                } else {

                    // 若源值已经是 SSA 临时值，则用 `add 0, value` 模拟 move。
                    let src = self.local_name(*source);

                    self.ir

                        .push_str(&format!("{} = add i64 0, {}\n", dest, src));

                }

            }

            mir::Instruction::Store { destination, value } => {

                if destination == value {

                    // Redundant self-writeback (`store x -> x`) does not change program state.

                    return Ok(());

                }

                let dest = self.local_name(*destination);

                let val = self.operand_value(*value, mir_fn);

                let ty = self.get_local_type(mir_fn, *value);

                let llvm_ty = self.mir_type_to_llvm_cached(ty);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "store {} {}, {}* {}\n",

                    llvm_ty, val, llvm_ty, dest

                ));

            }

            mir::Instruction::IndexAddr {

                destination,

                base,

                index,

            } => {

                let dest = self.local_name(*destination);

                let base_reg = self.local_name(*base);



                // 根据 index local 的 kind 决定是否需要先 load 索引值。

                let idx_local_info = &mir_fn.locals[index.index()].0;



                self.emit_indent();

                if idx_local_info.kind == LocalKind::User {

                    // 用户索引变量需要先 load。

                    let idx_reg = self.local_name(*index);

                    let idx_temp = format!("%idx.{}", destination.id);

                    self.ir

                        .push_str(&format!("{} = load i64, i64* {}\n", idx_temp, idx_reg));

                    self.emit_indent();

                    self.ir.push_str(&format!(

                        "{} = getelementptr i64, i64* {}, i64 {}\n",

                        dest, base_reg, idx_temp

                    ));

                } else {

                    // 临时索引值可直接作为 getelementptr 偏移。

                    let idx_reg = self.local_name(*index);

                    self.ir.push_str(&format!(

                        "{} = getelementptr i64, i64* {}, i64 {}\n",

                        dest, base_reg, idx_reg

                    ));

                }

            }

            mir::Instruction::Aggregate {

                destination,

                fields,

                ty,

            } => {

                // 处理数组/结构体聚合。

                let dest = self.local_name(*destination);



                match ty {

                    MIRType::Array(elem_ty, _len) => {

                        // 数组聚合按元素逐个写入目标地址，使用 store 完成。

                        let elem_llvm_ty = self.mir_type_to_llvm_cached(elem_ty);

                        for (i, field_local) in fields.iter().enumerate() {

                            // 计算当前元素的地址。

                            let elem_ptr = format!("{}.elem.{}", dest, i);

                            self.emit_indent();

                            self.ir.push_str(&format!(

                                "{} = getelementptr {}, {}* {}, i64 {}\n",

                                elem_ptr, elem_llvm_ty, elem_llvm_ty, dest, i

                            ));



                            // 取出当前元素的值。
                            let field_val = self.operand_value(*field_local, mir_fn);

                            self.emit_indent();

                            self.ir.push_str(&format!(

                                "store {} {}, {}* {}\n",

                                elem_llvm_ty, field_val, elem_llvm_ty, elem_ptr

                            ));

                        }

                    }

                    MIRType::Struct { .. } => {

                        // 结构体聚合使用 insertvalue 逐字段构造。
                        let llvm_ty = self.mir_type_to_llvm_cached(ty);

                        if fields.is_empty() {

                            self.emit_indent();

                            self.ir

                                .push_str(&format!("{} = alloca {}\n", dest, llvm_ty));

                        } else {

                            let mut current = "undef".to_string();

                            for (i, field_local) in fields.iter().enumerate() {

                                let field_val = self.operand_value(*field_local, mir_fn);

                                let field_ty = self.get_local_type(mir_fn, *field_local);

                                let field_llvm = self.mir_type_to_llvm_cached(&field_ty);

                                let temp = if i < fields.len() - 1 {

                                    format!("{}.f{}", dest, i)

                                } else {

                                    dest.clone()

                                };

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = insertvalue {} {}, {} {}, {}\n",

                                    temp, llvm_ty, current, field_llvm, field_val, i

                                ));

                                current = temp;

                            }

                        }

                    }

                    _ => {

                        // 鍏朵粬绫诲瀷鏆傛椂璺宠繃

                    }

                }

            }

            mir::Instruction::AddrOf {

                destination,

                source,

            } => {

                // 将局部变量地址 bitcast 成 i64 句柄。
                let dest = self.local_name(*destination);

                let src = self.local_name(*source);

                self.emit_indent();

                self.ir

                    .push_str(&format!("{} = bitcast i64* {} to i64\n", dest, src));

            }

            mir::Instruction::Call {

                destination,

                func,

                args,

            } => {

                // 生成函数调用。

                let dest = self.local_name(*destination);

                let dest_ty = self.get_local_type(mir_fn, *destination);

                let ret_ty = self.mir_type_to_llvm_cached(&dest_ty);



                // 对 `print` 做特殊处理，实际降到 `puts`。

                let is_print = func == "print";

                let actual_func = if is_print { "puts" } else { func };

                let callee = if actual_func.starts_with('%') || actual_func.starts_with('@') {

                    actual_func.to_string()

                } else {

                    format!("@{}", actual_func)

                };



                // 收集调用参数；参数值通过 operand_value 按需 load。
                let mut arg_strs: Vec<String> = Vec::new();

                for arg in args {

                    let arg_local = *arg;

                    let arg_ty = self.get_local_type(mir_fn, arg_local);

                    let llvm_arg_ty = self.mir_type_to_llvm_cached(&arg_ty);

                    let val = self.operand_value(arg_local, mir_fn);

                    arg_strs.push(format!("{} {}", llvm_arg_ty, val));

                }



                self.emit_indent();

                if is_print {

                    // print 调用实际映射到 puts，返回的 i32 可直接忽略。
                    self.ir

                        .push_str(&format!("call i32 @puts({})\n", arg_strs.join(", ")));

                    // print 在语言层返回 `()`，这里写回一个 unit 值。
                    self.ir.push_str(&format!("{} = add i8 0, 0\n", dest));

                } else if ret_ty == "void" {

                    self.ir.push_str(&format!(

                        "call void {}({})\n",

                        callee,

                        arg_strs.join(", ")

                    ));

                } else {

                    self.ir.push_str(&format!(

                        "{} = call {} {}({})\n",

                        dest,

                        ret_ty,

                        callee,

                        arg_strs.join(", ")

                    ));

                }

            }

            mir::Instruction::Discriminant {

                destination,

                source,

            } => {

                // 读取枚举判别值。
                // 当前 LLVM 中的枚举统一表示为 `{ 判别值, 载荷 }` 结构。

                // 判别值位于结构的第 0 个字段。
                let dest = self.local_name(*destination);

                let src = self.local_name(*source);



                // 使用 extractvalue 取出判别值。
                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = extractvalue {{ i64, i64 }} {}, 0\n",

                    dest, src

                ));

            }

            mir::Instruction::EnumConstruct {

                destination,

                discriminant,

                payload,

                enum_type: _,

            } => {

                // 构造枚举值。
                // 当前 LLVM 中的枚举表示为 `{ 判别值, 载荷 }`。

                let dest = self.local_name(*destination);



                // 先写入判别值字段。
                let discr_value = format!("{}.discr", dest);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = insertvalue {{ i64, i64 }} undef, i64 {}, 0\n",

                    discr_value, discriminant

                ));



                // 若存在 payload，则写入第 1 个字段。
                if let Some(payload_local) = payload {

                    let payload_val = self.operand_value(*payload_local, mir_fn);

                    self.emit_indent();

                    self.ir.push_str(&format!(

                        "{} = insertvalue {{ i64, i64 }} {}, i64 {}, 1\n",

                        dest, discr_value, payload_val

                    ));

                } else {

                    // 无 payload 时将第 1 个字段填为 `undef`。
                    self.emit_indent();

                    self.ir.push_str(&format!(

                        "{} = insertvalue {{ i64, i64 }} {}, i64 undef, 1\n",

                        dest, discr_value

                    ));

                }

            }

            mir::Instruction::ExtractPayload {

                destination,

                source,

            } => {

                // 提取枚举载荷。

                let dest = self.local_name(*destination);

                let src = self.local_name(*source);



                // 载荷位于结构的第 1 个字段。
                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = extractvalue {{ i64, i64 }} {}, 1\n",

                    dest, src

                ));

            }

            mir::Instruction::Cast {

                destination,

                value,

                to,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*value, mir_fn);

                let src_ty = self.get_local_type(mir_fn, *value);

                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);

                let dst_llvm = self.mir_type_to_llvm_cached(to);



                self.emit_indent();

                match (&src_ty, to) {

                    // Int -> Int：扩宽用 sext，缩窄用 trunc。

                    (MIRType::Int(a), MIRType::Int(b)) if a < b => {

                        self.ir.push_str(&format!(

                            "{} = sext {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    (MIRType::Int(a), MIRType::Int(b)) if a > b => {

                        self.ir.push_str(&format!(

                            "{} = trunc {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Float -> Float：扩宽用 fpext，缩窄用 fptrunc。

                    (MIRType::Float(a), MIRType::Float(b)) if a < b => {

                        self.ir.push_str(&format!(

                            "{} = fpext {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    (MIRType::Float(a), MIRType::Float(b)) if a > b => {

                        self.ir.push_str(&format!(

                            "{} = fptrunc {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Int -> Float：使用 sitofp（有符号整数转浮点）。

                    (MIRType::Int(_), MIRType::Float(_)) => {

                        self.ir.push_str(&format!(

                            "{} = sitofp {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Float -> Int：使用 fptosi（浮点转有符号整数）。

                    (MIRType::Float(_), MIRType::Int(_)) => {

                        self.ir.push_str(&format!(

                            "{} = fptosi {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Bool -> Int：使用 zext（i1 扩到 iN）。

                    (MIRType::Bool, MIRType::Int(_)) => {

                        self.ir.push_str(&format!(

                            "{} = zext {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Int -> Bool：使用 trunc（iN 截到 i1）。

                    (MIRType::Int(_), MIRType::Bool) => {

                        self.ir.push_str(&format!(

                            "{} = trunc {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Same type or unsupported: bitcast as fallback

                    _ => {

                        self.ir.push_str(&format!(

                            "{} = bitcast {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                }

            }

            mir::Instruction::FieldAddr {

                destination,

                base,

                field,

            } => {

                let dest = self.local_name(*destination);

                let base_reg = self.local_name(*base);

                let base_ty = self.get_local_type(mir_fn, *base);

                let base_llvm = self.mir_type_to_llvm_cached(&base_ty);

                self.emit_indent();

                // FieldAddr gets a pointer to a field within an aggregate type

                // Use getelementptr to compute the field address

                self.ir.push_str(&format!(

                    "{} = getelementptr inbounds {}, {}* {}, i32 0, i32 {}\n",

                    dest, base_llvm, base_llvm, base_reg, field

                ));

            }

            mir::Instruction::Extract {

                destination,

                value,

                index,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*value, mir_fn);

                let src_ty = self.get_local_type(mir_fn, *value);

                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = extractvalue {} {}, {}\n",

                    dest, src_llvm, src_val, index

                ));

            }

            mir::Instruction::Insert {

                destination,

                value,

                field,

                new_value,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*value, mir_fn);

                let src_ty = self.get_local_type(mir_fn, *value);

                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);

                let new_val = self.operand_value(*new_value, mir_fn);

                let new_ty = self.get_local_type(mir_fn, *new_value);

                let new_llvm = self.mir_type_to_llvm_cached(&new_ty);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = insertvalue {} {}, {} {}, {}\n",

                    dest, src_llvm, src_val, new_llvm, new_val, field

                ));

            }

            mir::Instruction::Intrinsic {

                destination,

                intrinsic,

                args,

            } => {

                // Generate inline code for intrinsic operations

                match intrinsic {

                    mir::IntrinsicOp::AddWithOverflow => {

                        if args.len() >= 2 {

                            let left_val = self.operand_value(args[0], mir_fn);

                            let right_val = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = add i64 {}, {}\n",

                                    dest_name, left_val, right_val

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::SubWithOverflow => {

                        if args.len() >= 2 {

                            let left_val = self.operand_value(args[0], mir_fn);

                            let right_val = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = sub i64 {}, {}\n",

                                    dest_name, left_val, right_val

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::MulWithOverflow => {

                        if args.len() >= 2 {

                            let left_val = self.operand_value(args[0], mir_fn);

                            let right_val = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = mul i64 {}, {}\n",

                                    dest_name, left_val, right_val

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::Copy { size, .. } => {

                        if args.len() >= 2 {

                            let dest_ptr = self.operand_value(args[0], mir_fn);

                            let src_ptr = self.operand_value(args[1], mir_fn);

                            self.emit_indent();

                            self.ir.push_str(&format!("call void @llvm.memcpy.p0i8.p0i8.i64(i8* {}, i8* {}, i64 {}, i1 false)\n", dest_ptr, src_ptr, size));

                        }

                    }

                    mir::IntrinsicOp::Compare { size, .. } => {

                        if args.len() >= 2 {

                            let left_ptr = self.operand_value(args[0], mir_fn);

                            let right_ptr = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = call i32 @memcmp(i8* {}, i8* {}, i64 {})\n",

                                    dest_name, left_ptr, right_ptr, size

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::MemMove { size, .. } => {

                        if args.len() >= 2 {

                            let dest_ptr = self.operand_value(args[0], mir_fn);

                            let src_ptr = self.operand_value(args[1], mir_fn);

                            self.emit_indent();

                            self.ir.push_str(&format!("call void @llvm.memmove.p0i8.p0i8.i64(i8* {}, i8* {}, i64 {}, i1 false)\n", dest_ptr, src_ptr, size));

                        }

                    }

                }

            }

            mir::Instruction::Phi {

                destination,

                incoming,

            } => {

                let dest = self.local_name(*destination);

                let ty = self.get_local_type(mir_fn, *destination);

                let is_void_like = match &ty {

                    MIRType::Unit | MIRType::Never => true,

                    MIRType::Tuple(fields) if fields.is_empty() => true,

                    _ => false,

                };

                if is_void_like {

                    // LLVM does not allow `phi void`.

                    return Ok(());

                }

                let llvm_ty = self.mir_type_to_llvm_cached(&ty);



                let entries: Vec<String> = incoming

                    .iter()

                    .map(|(local, block_idx)| {

                        let val = self.local_name(*local);

                        format!("[ {}, %bb_{} ]", val, block_idx)

                    })

                    .collect();



                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = phi {} {}\n",

                    dest,

                    llvm_ty,

                    entries.join(", ")

                ));

            }

        }

        Ok(())

    }



    fn codegen_terminator(

        &mut self,

        terminator: &mir::Terminator,

        mir_fn: &MirFunction,

    ) -> Result<(), String> {

        match terminator {

            mir::Terminator::Return(value) => {

                if let Some(v) = value {

                    let ty = self.get_local_type(mir_fn, *v);

                    // 特判 `main` 返回 unit 的情况，按约定返回整数 0。
                    let is_main_returning_unit =

                        mir_fn.name == "main" && matches!(ty, MIRType::Unit);



                    if is_main_returning_unit {

                        self.emit_indent();

                        self.ir.push_str("ret i64 0\n");

                    } else {

                        // 返回非 unit 值时，通过 operand_value 按需加载返回寄存器。

                        let reg = self.operand_value(*v, mir_fn);

                        // unit 在 LLVM 中用 i8 0 表示，而不是 void。

                        let llvm_ty = if matches!(ty, MIRType::Unit) {

                            "i8".to_string()

                        } else {

                            self.mir_type_to_llvm_cached(&ty)

                        };

                        self.emit_indent();

                        self.ir.push_str(&format!("ret {} {}\n", llvm_ty, reg));

                    }

                } else {

                    // 无显式返回值时，`main` 默认返回 0。

                    if mir_fn.name == "main" {

                        self.emit_indent();

                        self.ir.push_str("ret i64 0\n");

                    } else {

                        self.emit_indent();

                        self.ir.push_str("ret void\n");

                    }

                }

            }

            mir::Terminator::Goto(target) => {

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::If {

                cond: condition,

                then_block,

                else_block,

            } => {

                self.emit_indent();

                let cond_reg = self.operand_value(*condition, mir_fn);

                self.ir.push_str(&format!(

                    "br i1 {}, label %bb_{}, label %bb_{}\n",

                    cond_reg, then_block, else_block

                ));

            }

            mir::Terminator::Switch {

                discr,

                targets,

                otherwise,

            } => {

                self.emit_indent();

                let discr_reg = self.operand_value(*discr, mir_fn);



                // 鐢熸垚 switch 鎸囦护

                self.ir.push_str(&format!(

                    "switch i64 {}, label %bb_{} [",

                    discr_reg, otherwise

                ));



                // 娣诲姞姣忎釜 case

                for (value, target) in targets {

                    self.ir.push_str(&format!("\n"));

                    self.emit_indent();

                    self.ir

                        .push_str(&format!("  i64 {}, label %bb_{}", value, target));

                }



                self.ir.push_str(&format!("\n"));

                self.emit_indent();

                self.ir.push_str("]\n");

            }

            mir::Terminator::Break { target } => {

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::Continue { target } => {

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::Unreachable => {

                self.emit_indent();

                self.ir.push_str("unreachable\n");

            }

            mir::Terminator::Call {

                func,

                args,

                destination,

                target,

            } => {

                let dest = self.local_name(*destination);

                let dest_ty = self.get_local_type(mir_fn, *destination);

                let ret_ty = self.mir_type_to_llvm_cached(&dest_ty);



                let arg_strs: Vec<String> = args

                    .iter()

                    .map(|arg| match arg {

                        mir::CallArg::Local(local) => {

                            let arg_ty = self.get_local_type(mir_fn, *local);

                            let llvm_arg_ty = self.mir_type_to_llvm_cached(&arg_ty);

                            let val = self.operand_value(*local, mir_fn);

                            format!("{} {}", llvm_arg_ty, val)

                        }

                        mir::CallArg::Constant(constant) => match constant {

                            MirConstant::Int(n) => format!("i64 {}", n),

                            MirConstant::Bool(b) => format!("i1 {}", if *b { 1 } else { 0 }),

                            MirConstant::Float(f) => format!("double {}", f),

                            MirConstant::String(s) => format!(

                                "i8* @.str.{}",

                                self.strings.iter().position(|x| x == s).unwrap_or(0)

                            ),

                            _ => "i64 0".to_string(),

                        },

                    })

                    .collect();



                self.emit_indent();

                if ret_ty == "void" {

                    self.ir

                        .push_str(&format!("call void @{}({})\n", func, arg_strs.join(", ")));

                } else {

                    self.ir.push_str(&format!(

                        "{} = call {} @{}({})\n",

                        dest,

                        ret_ty,

                        func,

                        arg_strs.join(", ")

                    ));

                }

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::Suspend {
                poll_func,
                future_handle,
                destination,
                ready_block,
                pending_block,
            } => {
                let handle_val = self.operand_value(*future_handle, mir_fn);
                let dest = self.local_name(*destination);

                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = call i64 @{}(i64 {})\n",
                    dest, poll_func, handle_val
                ));

                let cmp = format!("{}_cmp", dest);
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = icmp eq i64 {}, 1\n",
                    cmp, dest
                ));

                self.emit_indent();
                self.ir.push_str(&format!(
                    "br i1 {}, label %bb_{}, label %bb_{}\n",
                    cmp, ready_block, pending_block
                ));
            }

        }

        Ok(())

    }



    /// 为 `codegen_function` 预先构建 local 名称缓存。
    pub(crate) fn build_name_cache(&mut self, mir_fn: &MirFunction) {

        self.name_cache.clear();

        // Find the maximum local id to size the cache

        let max_id = mir_fn

            .locals

            .iter()

            .map(|(l, _)| l.index())

            .max()

            .unwrap_or(0);

        // Pre-fill with empty strings up to max_id + 1

        self.name_cache.resize(max_id + 1, String::new());

        for (local, _ty) in &mir_fn.locals {

            // Delegate to shared utility for name generation

            self.name_cache[local.index()] = common::local_name(*local);

        }

    }



    fn local_name(&self, local: Local) -> String {

        let idx = local.index();

        if idx < self.name_cache.len() && !self.name_cache[idx].is_empty() {

            self.name_cache[idx].clone()

        } else {

            common::local_name(local)

        }

    }



    fn emit_indent(&mut self) {

        common::emit_indent(&mut self.ir, self.indent);

    }



    /// 缓存 MIR 类型到 LLVM 类型字符串，避免重复分配与递归转换。

    fn mir_type_to_llvm_cached(&mut self, ty: &MIRType) -> String {

        if let Some(cached) = self.type_str_cache.get(ty) {

            return cached.clone();

        }

        // Delegate to shared utility for cache misses

        let result = common::mir_type_to_llvm_str(ty);

        self.type_str_cache.insert(ty.clone(), result.clone());

        result

    }



    fn get_local_type<'a>(&self, mir_fn: &'a MirFunction, local: Local) -> &'a MIRType {

        // 根据 `local.id` 从 locals 表中取类型，缺省回退到 `MIR_I64`。

        mir_fn

            .locals

            .get(local.index())

            .map(|(_, ty)| ty)

            .unwrap_or(&MIR_I64)

    }



    /// 获取操作数对应的 SSA 值表示。

    /// 对用户变量会先从 alloca 中发出 `load`，再返回临时寄存器名。
    /// 其余情况直接返回局部变量名。

    fn operand_value(&mut self, local: Local, mir_fn: &MirFunction) -> String {

        // 根据 `local.id` 读取该 local 的元信息。
        let local_info = &mir_fn.locals[local.index()].0;



        match local_info.kind {

            LocalKind::User => {

                // 用户变量需要先 load，因为 MIR 中它们通常表示为地址值。

                let ty = self.get_local_type(mir_fn, local);

                let llvm_ty = self.mir_type_to_llvm_cached(ty);

                let temp_reg = format!("%load.{}", self.load_counter);

                self.load_counter += 1;

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = load {}, {}* {}\n",

                    temp_reg,

                    llvm_ty,

                    llvm_ty,

                    self.local_name(local)

                ));

                temp_reg

            }

            _ => {

                // 鍙傛暟銆佷复鏃跺彉閲忕瓑鐩存帴浣跨敤瀵勫瓨鍣ㄥ悕

                self.local_name(local)

            }

        }

    }

}



