pub mod common;

pub mod jit;
mod declaration_helpers;



pub use jit::JITCodegen;



use crate::mir::{self, Local, LocalKind, MIRType, MirConstant, MirFunction, MIR_I64};

use std::collections::{HashMap, HashSet};

use std::io::Write;



#[derive(Debug, Clone)]

pub struct ExternDecl {

    pub name: String,

    pub abi: String,

    pub link_name: Option<String>,

    pub params: Vec<MIRType>,

    pub ret: MIRType,

}



#[derive(Debug, Clone)]

pub struct ExportSymbol {

    pub internal_name: String,

    pub export_name: String,

}



#[derive(Debug, Clone, Default)]

pub struct FfiCodegenConfig {

    pub extern_decls: Vec<ExternDecl>,

    pub export_symbols: Vec<ExportSymbol>,

}



pub struct Codegen {

    ir: String,

    indent: usize,

    declarations: String,

    ffi: FfiCodegenConfig,

    /// Collected string literals emitted for the current module.
    strings: Vec<String>,

    /// 闁诲孩绋掗〃鍫ヮ敄娴ｅ湱鈻旈柟缁樺笧閸╂姊洪幓鎺旂妞ゆ挻鎮傚顐﹀级閹稿海褰滈梺?
    string_counter: usize,

    /// Cache local names for O(1) lookup during code generation.
    pub(crate) name_cache: Vec<String>,

    /// 缂傚倸鍊归幐鎼佹偤?MIR 缂備緡鍋夐褔鎮楅悜钘夌?LLVM 缂備緡鍋夐褔鎮楁搴樺亾濞戞瑯娈樻い鎴滅劍缁嬪鎳犻浣烘殸闂佸搫瀚慨鎾儍閻樿违?
    type_str_cache: HashMap<MIRType, String>,

    /// 婵?`load` 闂佸湱顭堝ú锝夊箮閵堝鍋ㄩ柣鏃傤焾閻忓洭鏌涢悜鍡楃仧缂佹梹鎸抽幆?SSA 婵炴垶鎸搁悺銊ヮ渻閸屾壕鍋撻棃娑橆仼闁宦板姂瀹曟娊濡搁妷锕€鈧娊鏌?
    load_counter: usize,

}



impl Codegen {

    pub fn new() -> Self {

        Self::with_ffi(FfiCodegenConfig::default())

    }



    pub fn with_ffi(ffi: FfiCodegenConfig) -> Self {

        let mut cg = Self {

            ir: String::new(),

            indent: 0,

            declarations: String::new(),

            ffi,

            strings: Vec::new(),

            string_counter: 0,

            name_cache: Vec::new(),

            type_str_cache: HashMap::new(),

            load_counter: 0,

        };

        cg.emit_header();

        cg.declare_runtime_functions();

        cg

    }



    fn emit_header(&mut self) {

        // Start module output with a stable banner used by snapshots.
        self.declarations.push_str("; Sengoo LLVM IR\n");

        self.declarations

            .push_str("; Generated by Sengoo Compiler\n\n");



        // 闂佸搫绉烽～澶婄暤娓氣偓閹嫰顢欓悾灞界伇濡ょ姷鍋涢崯鑳亹鐎靛憡濯奸柛鎾楀懏鐎?target triple闂佹寧绋戦惌鍌涘閳哄懎绀?clang 闂?`-Woverride-module`闂?
        if cfg!(target_os = "windows") {

            self.declarations

                .push_str("target triple = \"x86_64-pc-windows-msvc\"\n\n");

        } else if cfg!(target_os = "macos") {

            self.declarations

                .push_str("target triple = \"x86_64-apple-macosx\"\n\n");

        } else {

            self.declarations

                .push_str("target triple = \"x86_64-unknown-linux-gnu\"\n\n");

        }

    }



    fn emit_string_constants(&mut self) {

        if !self.strings.is_empty() {

            self.declarations.push_str("; String Constants\n");

            for (i, s) in self.strings.iter().enumerate() {

                // Escape string contents before emitting LLVM string constants.
                let escaped = s.replace("\\", "\\\\").replace("\"", "\\\"");

                self.declarations.push_str(&format!(

                    "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\"\n",

                    i,

                    s.len() + 1,

                    escaped

                ));

            }

            self.declarations.push_str("\n");

        }

    }



    /// 濠电偛顦崝宀勫船閻ｅ备鍋撳☉娆樻畼妞ゆ垳鐒︾粙澶愬箵閹烘柨鐓戦梻浣瑰絻缁绘劙鎳熼悢鍛婁氦闁哄倹瀵х粈鈧梺绋跨箺濞夋盯宕ｈ箛鏇氭勃闁逞屽墰缁參鏁冮埀顒冦亹閸ф瑙︾€广儱鍟犻崑?
    fn add_string(&mut self, s: &str) -> String {

        let idx = self.string_counter;

        self.string_counter += 1;

        self.strings.push(s.to_string());

        format!("@.str.{}", idx)

    }



    /// 闂佽顔栭崑鍛嚕?MIR 婵炴垶鎼╅崢濂稿吹椤撱垺鍋濋柟娈垮枟閻ｈ京绱撴担瑙勫鞍闁诲寒鍨遍幏鍛村箻閹偊娼堕梺鎼炲妼椤戞垹妲愬┑瀣祦闁割偅娲﹂弳鏇㈡煕韫囨挾澧㈤柡浣规崌楠?LLVM named struct type闂?
    fn emit_struct_types(&mut self, mir_fns: &[MirFunction]) {

        let mut seen = HashSet::new();

        for func in mir_fns {

            for (_, ty) in &func.locals {

                self.collect_struct_types(ty, &mut seen);

            }

        }

    }



    /// 闂備緡鍋呯敮鎺旂礊婵犲洤缁╅柛顐ｆ礃閼茬姷绱撴担瑙勫鞍闁诲寒鍨遍幏鍛村箻瀹曞洦鎲诲┑鐐茬墕閸氣偓闁煎灚鍨甸悾鐢典沪缁涘顔囬梺?LLVM named type闂?
    fn collect_struct_types(&mut self, ty: &MIRType, seen: &mut HashSet<String>) {

        match ty {

            MIRType::Struct { name, fields } => {

                if seen.insert(name.clone()) {

                    // 闂佺绻愰悧鎾诲焵椤掍礁绗掔紓宥咃攻瀵板嫰宕熼鐔封偓鐐烘倵濞戞瑯娈曟い鏂跨焸閺屽苯鐣濋埀顒€鈻撻幋婵堟殼閻忕偟鐡斿▓鎵磽娴ｈ灏伴柣搴灡閹峰懘骞橀幆閭︽蕉闂佹悶鍔岄鍐焵?
                    for (_, ft) in fields {

                        self.collect_struct_types(ft, seen);

                    }

                    let field_types: Vec<String> = fields

                        .iter()

                        .map(|(_, ft)| self.mir_type_to_llvm_cached(ft))

                        .collect();

                    self.declarations.push_str(&format!(

                        "%{} = type {{ {} }}\n",

                        name,

                        field_types.join(", ")

                    ));

                }

            }

            // Recurse into composite types that may contain structs

            MIRType::Array(elem, _) | MIRType::Ptr(elem) | MIRType::Ref(elem) => {

                self.collect_struct_types(elem, seen);

            }

            MIRType::Tuple(types) => {

                for t in types {

                    self.collect_struct_types(t, seen);

                }

            }

            _ => {}

        }

    }



    /// Estimate the IR buffer capacity based on MIR function metrics.

    /// This avoids repeated reallocations during IR generation.

    fn estimate_ir_capacity(mir_fns: &[MirFunction]) -> usize {

        let mut estimate = 1024; // Base overhead for header, runtime declarations, etc.

        for func in mir_fns {

            // Each local ~30 bytes (alloca declaration)

            estimate += func.locals.len() * 30;

            // Each basic block ~20 bytes (label)

            estimate += func.basic_blocks.len() * 20;

            // Each instruction ~60 bytes of IR text

            for bb in &func.basic_blocks {

                estimate += bb.instructions.len() * 60;

                // Terminator ~40 bytes

                if bb.terminator.is_some() {

                    estimate += 40;

                }

            }

            // Function header/footer overhead (~80 bytes for define, params, closing brace)

            estimate += 80;

        }

        estimate

    }



    fn prepare_codegen_buffers(&mut self) {

        self.ir.clear();

        self.declarations.clear();

        self.strings.clear();

        self.string_counter = 0;

        self.name_cache.clear();

        self.type_str_cache.clear();

        self.load_counter = 0;

        self.emit_header();

        self.declare_runtime_functions();

    }



    fn emit_module_ir(&mut self, mir_fns: &[MirFunction]) -> Result<(), String> {

        self.prepare_codegen_buffers();

        // Pre-allocate IR buffer based on MIR size estimate to reduce reallocations

        let capacity = Self::estimate_ir_capacity(mir_fns);

        self.ir.reserve(capacity);



        // 濠碘槅鍋撶徊楣冩偋閺囥垹鍌ㄦ繛鎴欏灩缂佲晠鏌涢锝嗙闁艰尙濞€閺岀喓鍠婂Ο杞板闂備礁鎼悧鍡浰囬鐐村仱鐟滃繒鍒掗銏℃櫆闁兼剚鍨煎ú顒勬煟閵忊晛鐏￠柟顔煎€垮畷?
        for mir_fn in mir_fns {

            self.collect_string_constants(mir_fn);

        }

        // collect string constants declarations
        self.maybe_declare_spawn_runtime_function(mir_fns);
        self.maybe_declare_select_runtime_function(mir_fns);
        self.maybe_declare_sleep_runtime_functions(mir_fns);
        self.maybe_declare_timeout_runtime_functions(mir_fns);
        self.maybe_declare_async_task_runtime_functions(mir_fns);
        self.emit_string_constants();



        // Emit aggregate type declarations before function bodies.
        self.emit_struct_types(mir_fns);



        // 婵炴垶鎸鹃崕銈堝暞闂佺鍕╀沪闁煎灚鍨块幆鍐礋椤掑倹袞婵炴垶鎼╂禍婊堝吹闁秴鏋侀柟娈垮枟閺呮悂鏌?LLVM IR闂?
        for mir_fn in mir_fns {

            self.codegen_function(mir_fn)?;

        }

        self.emit_export_symbol_wrappers(mir_fns);

        Ok(())

    }



    fn emit_export_symbol_wrappers(&mut self, mir_fns: &[MirFunction]) {

        if self.ffi.export_symbols.is_empty() {

            return;

        }



        let mut emitted = HashSet::new();

        let export_symbols = self.ffi.export_symbols.clone();

        for export in export_symbols {

            if export.export_name == export.internal_name {

                continue;

            }

            if !emitted.insert(export.export_name.clone()) {

                continue;

            }



            let Some(target) = mir_fns.iter().find(|f| f.name == export.internal_name) else {

                continue;

            };



            let ret_ty = self.mir_type_to_llvm_cached(&target.return_type);

            let params = target

                .params

                .iter()

                .enumerate()

                .map(|(idx, ty)| {

                    let llvm = self.mir_type_to_llvm_cached(ty);

                    format!("{} %arg_{}", llvm, idx)

                })

                .collect::<Vec<_>>();

            let args = target

                .params

                .iter()

                .enumerate()

                .map(|(idx, ty)| {

                    let llvm = self.mir_type_to_llvm_cached(ty);

                    format!("{} %arg_{}", llvm, idx)

                })

                .collect::<Vec<_>>();



            self.ir.push_str("\n");

            self.ir.push_str(&format!(

                "; Export wrapper: {} -> {}\n",

                export.internal_name, export.export_name

            ));

            self.ir.push_str(&format!(

                "define {} @{}({}) {{\n",

                ret_ty,

                export.export_name,

                params.join(", ")

            ));

            self.indent += 1;

            self.emit_indent();

            if ret_ty == "void" {

                self.ir.push_str(&format!(

                    "call void {}({})\n",

                    export.internal_name,

                    args.join(", ")

                ));

                self.emit_indent();

                self.ir.push_str("ret void\n");

            } else {

                self.ir.push_str(&format!(

                    "%export_ret = call {} @{}({})\n",

                    ret_ty,

                    export.internal_name,

                    args.join(", ")

                ));

                self.emit_indent();

                self.ir.push_str(&format!("ret {} %export_ret\n", ret_ty));

            }

            self.indent -= 1;

            self.ir.push_str("}\n");

        }

    }



    pub fn codegen(&mut self, mir_fns: &[MirFunction]) -> Result<String, String> {

        self.emit_module_ir(mir_fns)?;

        let mut result = String::with_capacity(self.declarations.len() + self.ir.len());

        result.push_str(&self.declarations);

        result.push_str(&self.ir);

        Ok(result)

    }



    pub fn codegen_to_writer<W: Write>(

        &mut self,

        mir_fns: &[MirFunction],

        writer: &mut W,

    ) -> Result<(), String> {

        self.emit_module_ir(mir_fns)?;

        writer

            .write_all(self.declarations.as_bytes())

            .map_err(|e| format!("failed to write declarations: {}", e))?;

        writer

            .write_all(self.ir.as_bytes())

            .map_err(|e| format!("failed to write function IR: {}", e))?;

        writer

            .flush()

            .map_err(|e| format!("failed to flush LLVM IR output: {}", e))?;

        Ok(())

    }



    /// Collect string literals referenced by a MIR function.
    fn collect_string_constants(&mut self, mir_fn: &MirFunction) {

        for bb in &mir_fn.basic_blocks {

            for inst in mir_fn.block_instructions(bb) {

                if let mir::Instruction::Assign {

                    value: mir::MirConstant::String(s),

                    ..

                } = inst

                {

                    self.add_string(s);

                }

            }

        }

    }



    fn codegen_function(&mut self, mir_fn: &MirFunction) -> Result<(), String> {

        // Pre-compute all local names for O(1) lookup

        self.build_name_cache(mir_fn);

        // Reset load counter per function for clean SSA naming

        self.load_counter = 0;



        self.ir.push_str("\n");

        self.ir.push_str(&format!("; Function: {}\n", mir_fn.name));

        let return_type = self.mir_type_to_llvm_cached(&mir_fn.return_type);

        self.ir

            .push_str(&format!("define {} @{}(", return_type, mir_fn.name));

        for (i, ty) in mir_fn.params.iter().enumerate() {

            let param_name = format!("%l_{}", i + 1);

            if i > 0 {

                self.ir.push_str(", ");

            }

            let param_ty = self.mir_type_to_llvm_cached(ty);

            self.ir.push_str(&format!("{} {}", param_ty, param_name));

        }

        self.ir.push_str(") {\n");

        self.indent += 1;



        // Track which locals need alloca (user variables only)

        let user_locals: Vec<_> = mir_fn

            .locals

            .iter()

            .filter(|(l, _)| l.kind == LocalKind::User)

            .collect();



        for bb in &mir_fn.basic_blocks {

            let allocas: Vec<(Local, MIRType)> = if bb.id == 0 {

                user_locals.iter().map(|(l, t)| (*l, t.clone())).collect()

            } else {

                vec![]

            };

            self.codegen_basic_block(mir_fn, bb, &allocas)?;

        }

        self.indent -= 1;

        self.ir.push_str("}\n");

        Ok(())

    }



    fn codegen_basic_block(

        &mut self,

        mir_fn: &MirFunction,

        bb: &mir::BasicBlock,

        allocas: &[(Local, MIRType)],

    ) -> Result<(), String> {

        self.ir.push_str(&format!("bb_{}:\n", bb.id));

        self.indent += 1;



        // Emit allocas at the start of the entry block (before any instructions)

        for (local, ty) in allocas {

            let local_name = self.local_name(*local);

            let llvm_ty = self.mir_type_to_llvm_cached(ty);

            self.emit_indent();

            self.ir

                .push_str(&format!("{} = alloca {}\n", local_name, llvm_ty));

        }



        for inst_id in &bb.instructions {

            let inst = mir_fn.instruction(*inst_id);

            self.codegen_instruction(inst, mir_fn)?;

        }

        if let Some(terminator) = &bb.terminator {

            self.codegen_terminator(terminator, mir_fn)?;

        }

        self.indent -= 1;

        Ok(())

    }



    fn codegen_instruction(

        &mut self,

        inst: &mir::Instruction,

        mir_fn: &MirFunction,

    ) -> Result<(), String> {

        match inst {

            mir::Instruction::Nop => {}

            mir::Instruction::Assign { destination, value } => {

                let dest = self.local_name(*destination);

                self.emit_indent();

                match value {

                    mir::MirConstant::Int(n) => {

                        self.ir.push_str(&format!("{} = add i64 0, {}\n", dest, n));

                    }

                    mir::MirConstant::Uint(n) => {

                        self.ir.push_str(&format!("{} = add i64 0, {}\n", dest, n));

                    }

                    mir::MirConstant::Bool(b) => {

                        self.ir.push_str(&format!(

                            "{} = add i1 0, {}\n",

                            dest,

                            if *b { 1 } else { 0 }

                        ));

                    }

                    mir::MirConstant::Float(f) => {

                        self.ir

                            .push_str(&format!("{} = fadd double 0.0, {}\n", dest, f));

                    }

                    mir::MirConstant::Char(c) => {

                        self.ir

                            .push_str(&format!("{} = add i8 0, {}\n", dest, *c as i8));

                    }

                    mir::MirConstant::String(s) => {

                        // 闁诲繐绻愬Λ妤呮偤瑜忕划顓㈡晜閼愁垼娲柣銏╁灡閹倿宕冲ú顏勫強闁绘灏欏▓鎼佹煕閹烘挻绶查柛鎴斺偓鏂ユ灃闁靛鍎遍弬鈧梺姹囧妼鐎氼剟宕ｈ箛鏇氭勃闁逞屽墰閳ь剚绋掗〃鍫ヮ敄娴ｅ湱鈻旈柤纰卞墻閸庡﹪鏌涘▎鎰粵闁?
                        let str_idx = self.strings.iter().position(|x| x == s).unwrap_or(0);

                        let str_ref = format!("@.str.{}", str_idx);

                        self.ir.push_str(&format!(

                            "{} = bitcast [{} x i8]* {} to i8*\n",

                            dest,

                            s.len() + 1,

                            str_ref

                        ));

                    }

                    mir::MirConstant::Bytes(_) => {

                        self.ir.push_str(&format!("{} = add i64 0, 0\n", dest));

                    }

                    mir::MirConstant::GlobalRef(name) => {
                        let dest_ty = self.get_local_type(mir_fn, *destination);
                        let llvm_dest_ty = self.mir_type_to_llvm_cached(&dest_ty);
                        if matches!(dest_ty, MIRType::Fn { .. }) {
                            self.ir.push_str(&format!(
                                "{} = bitcast {} @{} to {}
",
                                dest, llvm_dest_ty, name, llvm_dest_ty
                            ));
                        } else {
                            self.ir
                                .push_str(&format!("{} = bitcast i64* @{} to i64
", dest, name));
                        }
                    }

                    mir::MirConstant::Unit => {

                        self.ir.push_str(&format!("{} = add i8 0, 0\n", dest));

                    }

                }

            }

            mir::Instruction::Unary {

                destination,

                op,

                operand,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*operand, mir_fn);

                self.emit_indent();

                match op {

                    mir::MirUnOp::Neg => {

                        self.ir

                            .push_str(&format!("{} = sub i64 0, {}\n", dest, src_val));

                    }

                    mir::MirUnOp::Not => {

                        self.ir

                            .push_str(&format!("{} = xor i1 {}, true\n", dest, src_val));

                    }

                    mir::MirUnOp::BitNot => {

                        self.ir

                            .push_str(&format!("{} = xor i64 {}, -1\n", dest, src_val));

                    }

                }

            }

            mir::Instruction::Binary {

                destination,

                op,

                left,

                right,

            } => {

                let dest = self.local_name(*destination);

                // 婵犵鈧啿鈧綊鎮樻径鎰鐎广儱瀚粙濠囨煛娴ｅ搫顣兼俊鍙夋倐閹粙濡搁敃鈧悡鏇㈡煕濞嗘劧鑰块柛锝嗘そ閺佸秴鐣濋崟顑跨帛闁荤喐娲戠粈渚€宕?load

                let left_val = self.operand_value(*left, mir_fn);

                let right_val = self.operand_value(*right, mir_fn);

                self.emit_indent();

                match op {

                    mir::MirBinOp::Add => {

                        self.ir

                            .push_str(&format!("{} = add i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Sub => {

                        self.ir

                            .push_str(&format!("{} = sub i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Mul => {

                        self.ir

                            .push_str(&format!("{} = mul i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Div => {

                        self.ir.push_str(&format!(

                            "{} = sdiv i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Rem => {

                        self.ir.push_str(&format!(

                            "{} = srem i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Eq => {

                        self.ir.push_str(&format!(

                            "{} = icmp eq i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Ne => {

                        self.ir.push_str(&format!(

                            "{} = icmp ne i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Lt => {

                        self.ir.push_str(&format!(

                            "{} = icmp slt i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Le => {

                        self.ir.push_str(&format!(

                            "{} = icmp sle i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Gt => {

                        self.ir.push_str(&format!(

                            "{} = icmp sgt i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::Ge => {

                        self.ir.push_str(&format!(

                            "{} = icmp sge i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::BitAnd => {

                        self.ir

                            .push_str(&format!("{} = and i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::BitOr => {

                        self.ir

                            .push_str(&format!("{} = or i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::BitXor => {

                        self.ir

                            .push_str(&format!("{} = xor i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Shl => {

                        self.ir

                            .push_str(&format!("{} = shl i64 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::Shr => {

                        self.ir.push_str(&format!(

                            "{} = ashr i64 {}, {}\n",

                            dest, left_val, right_val

                        ));

                    }

                    mir::MirBinOp::LogAnd => {

                        self.ir

                            .push_str(&format!("{} = and i1 {}, {}\n", dest, left_val, right_val));

                    }

                    mir::MirBinOp::LogOr => {

                        self.ir

                            .push_str(&format!("{} = or i1 {}, {}\n", dest, left_val, right_val));

                    }

                }

            }

            mir::Instruction::Load {

                destination,

                source,

            } => {

                let dest = self.local_name(*destination);

                // 婵炶揪缍€濞夋洟寮?id 闂佺儵鏅涢悺銊ф暜鐎靛憡顫曢柕蹇曞Х缁屽潡鏌ㄥ☉姗嗗妺(1) 闂佸搫琚崕鍙夌珶?

                let (local_info, src_ty) = &mir_fn.locals[source.index()];



                self.emit_indent();

                // 闂佸搫绉烽～澶婄暤娴ｇ硶鏀?local 闂?kind 闂佸憡绮岄惉鑲╂偖椤愶箑鍨傞悗锝庝簻閻忔煡鏌￠崒銈呭绩缂佺粯鐗楃粙澶愬焵椤掑嫬绾ч柍鈺佸暞绗戦梺鍛婄啲缁犳挸銆掗崜浣瑰暫濞达絿鍎ら崺鍌涙叏濠垫挾鍒扮憸鏉垮€垮畷?load闂?                // 1. 闂佹椿娼块崝宥夊春濞戙垹鐭楁慨妞诲亾闁革絾妞介弻鍛潩椤掑倸鐓戦柣搴ｆ暩閹虫挾鑺?alloca闂佹寧绋戦惌渚€顢氭导鏉戠煑闁哄秲鍔嶉ˇ褔姊婚崶锝呬壕闁?load闂?
                // 2. 闂佸湱顭堝ú顓㈠箯閿熺姴绠ｉ柡宓懐鈹涢梺娲绘娇閸斿海鎮锕€鍨傞悗锝傛櫇閻﹀秹姊婚崶锝呬壕闁?load闂佹寧绋戦張顒佹櫠閻樼粯鍤勯柦妯侯槺缁讳線鏌涢幒鎾寸凡闁告瑩绠栭獮鎰板炊瑜庨崐濠氭煟閵娿儱顏╅柍褜鍓涢鏇㈠焵?
                let needs_load = local_info.kind == LocalKind::User

                    || matches!(src_ty, MIRType::Ptr(_) | MIRType::Ref(_));



                if needs_load {

                    let src = self.local_name(*source);

                    let llvm_ty = self.mir_type_to_llvm_cached(src_ty);

                    // load 闂佹眹鍔岀€氼喚鎮锕€鍨傞悗锝庝簻缁插潡鏌涢幇顒€甯犵紒顭戝墮閳瑰啴骞囬鐔稿劌婵炶揪绲剧划宥夊汲閻旇　鍋撻崷顓炰槐婵＄虎鍨堕獮鎰板炊瑜庨崐濠氭煟閵娿儱顏╅柛妯绘尵濡叉劙鎮╂担鍐炬蕉闂佹悶鍔岄鍐焵?
                    let load_ty = match src_ty {

                        MIRType::Ptr(inner) | MIRType::Ref(inner) => {

                            self.mir_type_to_llvm_cached(inner)

                        }

                        _ => llvm_ty,

                    };

                    self.ir.push_str(&format!(

                        "{} = load {}, {}* {}\n",

                        dest, load_ty, load_ty, src

                    ));

                } else {

                    // Materialize a move by forwarding the SSA name directly.
                    let src = self.local_name(*source);

                    self.ir

                        .push_str(&format!("{} = add i64 0, {}\n", dest, src));

                }

            }

            mir::Instruction::Store { destination, value } => {

                if destination == value {

                    // Redundant self-writeback (`store x -> x`) does not change program state.

                    return Ok(());

                }

                let dest = self.local_name(*destination);

                let val = self.operand_value(*value, mir_fn);

                let ty = self.get_local_type(mir_fn, *value);

                let llvm_ty = self.mir_type_to_llvm_cached(ty);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "store {} {}, {}* {}\n",

                    llvm_ty, val, llvm_ty, dest

                ));

            }

            mir::Instruction::IndexAddr {

                destination,

                base,

                index,

            } => {

                let dest = self.local_name(*destination);

                let base_reg = self.local_name(*base);



                // 闂佸搫绉烽～澶婄暤?index local 闂?kind 闂佸憡鍔曢崯鍧楁偩妤ｅ啫鍙婃い鏍ㄧ閸庡﹪姊婚崶锝呬壕闁荤喐娲戠粈渚€宕?load 缂備椒绌堕崹鍦閳哄懎纾圭紒妤勩€€閸?
                let idx_local_info = &mir_fn.locals[index.index()].0;



                self.emit_indent();

                if idx_local_info.kind == LocalKind::User {

                    // 闂佹椿娼块崝宥夊春濞戞碍顫曢柕蹇曞Х缁屽潡鏌涘▎鎰惰€块柛锝嗘そ濡線鍩€椤掑倹鍟哄ù锝囶焾鐢?load闂?
                    let idx_reg = self.local_name(*index);

                    let idx_temp = format!("%idx.{}", destination.id);

                    self.ir

                        .push_str(&format!("{} = load i64, i64* {}\n", idx_temp, idx_reg));

                    self.emit_indent();

                    self.ir.push_str(&format!(

                        "{} = getelementptr i64, i64* {}, i64 {}\n",

                        dest, base_reg, idx_temp

                    ));

                } else {

                    // 婵炴垶鎸搁悺銊ヮ渻閸屾粍顫曢柕蹇曞Х缁屽潡鏌涙繝鍕付鐟滅増鐓￠幆鍕偓娑櫭径宥吤归敐鍡欑焼閻?getelementptr 闂佺顑呯换鎺嶇昂闂?
                    let idx_reg = self.local_name(*index);

                    self.ir.push_str(&format!(

                        "{} = getelementptr i64, i64* {}, i64 {}\n",

                        dest, base_reg, idx_reg

                    ));

                }

            }

            mir::Instruction::Aggregate {

                destination,

                fields,

                ty,

            } => {

                // 婵犮垼娉涚€氼噣骞冩繝鍥ф瀬闁规鍠氶惌?缂傚倷鐒﹂幐濠氭倵椤栨稒濯撮柟楣冣偓娑氶┏闂佸憡鑹鹃悧鍕焵?
                let dest = self.local_name(*destination);



                match ty {

                    MIRType::Array(elem_ty, _len) => {

                        // 闂佽桨鐒︽竟鍡欏垝瀹ュ鍤傛慨姗嗗墯閸娿倝鏌熺粙娆炬Ц闁告ɑ鎸惧Σ鎰版偐閻戔晛浜鹃柟閭︿邯閸ゅ鏌涢幇顓犳噧闁告瑥妫濋幆鍕敊閻ｅ苯鐏遍梺闈╅檮濠㈡ê顭囬崘顔芥櫖閻忕偟鍘ч埢蹇涙煟?store 闁诲海鎳撻張顒勫垂濮樿泛违?
                        let elem_llvm_ty = self.mir_type_to_llvm_cached(elem_ty);

                        for (i, field_local) in fields.iter().enumerate() {

                            // 闁荤姳绶ょ槐鏇㈡偩閺勫繈浜归柟鎯у暱椤ゅ懘鏌涜箛鎾虫殶缂佲偓瀹€鍕剭闁告洦鍋呴崟楣冩煕瑜夐崑鎾绘煏?
                            let elem_ptr = format!("{}.elem.{}", dest, i);

                            self.emit_indent();

                            self.ir.push_str(&format!(

                                "{} = getelementptr {}, {}* {}, i64 {}\n",

                                elem_ptr, elem_llvm_ty, elem_llvm_ty, dest, i

                            ));



                            // Evaluate each field value before storing it into the aggregate slot.
                            let field_val = self.operand_value(*field_local, mir_fn);

                            self.emit_indent();

                            self.ir.push_str(&format!(

                                "store {} {}, {}* {}\n",

                                elem_llvm_ty, field_val, elem_llvm_ty, elem_ptr

                            ));

                        }

                    }

                    MIRType::Struct { .. } => {

                        // Build struct values incrementally with insertvalue.
                        let llvm_ty = self.mir_type_to_llvm_cached(ty);

                        if fields.is_empty() {

                            self.emit_indent();

                            self.ir

                                .push_str(&format!("{} = alloca {}\n", dest, llvm_ty));

                        } else {

                            let mut current = "undef".to_string();

                            for (i, field_local) in fields.iter().enumerate() {

                                let field_val = self.operand_value(*field_local, mir_fn);

                                let field_ty = self.get_local_type(mir_fn, *field_local);

                                let field_llvm = self.mir_type_to_llvm_cached(&field_ty);

                                let temp = if i < fields.len() - 1 {

                                    format!("{}.f{}", dest, i)

                                } else {

                                    dest.clone()

                                };

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = insertvalue {} {}, {} {}, {}\n",

                                    temp, llvm_ty, current, field_llvm, field_val, i

                                ));

                                current = temp;

                            }

                        }

                    }

                    MIRType::Enum { .. } => {

                        let llvm_ty = self.mir_type_to_llvm_cached(ty);
                        let discr_local = fields
                            .first()
                            .copied()
                            .ok_or_else(|| "enum aggregate missing discriminant field".to_string())?;
                        let discr_val = self.operand_value(discr_local, mir_fn);
                        let discr_temp = format!("{}.discr", dest);

                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = insertvalue {} undef, i64 {}, 0\n",
                            discr_temp, llvm_ty, discr_val
                        ));

                        let payload_val = if let Some(payload_local) = fields.get(1).copied() {
                            self.operand_value(payload_local, mir_fn)
                        } else {
                            "0".to_string()
                        };

                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = insertvalue {} {}, i64 {}, 1\n",
                            dest, llvm_ty, discr_temp, payload_val
                        ));

                    }

                    _ => {

                        // 闂佺绻戝﹢鍦垝椤掑倻灏甸悹鍥皺閳ь剛鍏樺鎶藉磼濞戞瑯妲柣鐘叉惈閻ゅ洨鎹?

                    }

                }

            }

            mir::Instruction::AddrOf {

                destination,

                source,

            } => {

                // Bitcast keeps the same bits while changing only the LLVM view of the value.
                let dest = self.local_name(*destination);

                let src = self.local_name(*source);

                self.emit_indent();

                self.ir

                    .push_str(&format!("{} = bitcast i64* {} to i64\n", dest, src));

            }

            mir::Instruction::Call {

                destination,

                func,

                args,

            } => {

                // 闂佹眹鍨婚崰鎰板垂濮樿泛绀勯柤鎭掑劜濞堝爼鎮圭€ｎ亜鏆熼柡浣靛€濇俊?
                let dest = self.local_name(*destination);

                let dest_ty = self.get_local_type(mir_fn, *destination);

                let ret_ty = self.mir_type_to_llvm_cached(&dest_ty);



                // 闁?`print` 闂佺顑嗗銊︾珶閹烘垟鏋斿┑鐘插亞濡查亶鏌ｉ悙鍙夛紨缂佽鲸绻勯埀顒€婀遍崑銈咁瀶椤栫偞鈷旂€广儱鎳庨悡?`puts`闂?
                let is_print = func == "print";

                let actual_func = if is_print { "puts" } else { func };

                let callee = if actual_func.starts_with('%') || actual_func.starts_with('@') {

                    actual_func.to_string()

                } else {

                    format!("@{}", actual_func)

                };



                // Resolve call operands through operand_value so loads happen consistently.
                let mut arg_strs: Vec<String> = Vec::new();

                for arg in args {

                    let arg_local = *arg;

                    let arg_ty = self.get_local_type(mir_fn, arg_local);

                    let llvm_arg_ty = self.mir_type_to_llvm_cached(&arg_ty);

                    let val = self.operand_value(arg_local, mir_fn);

                    arg_strs.push(format!("{} {}", llvm_arg_ty, val));

                }



                self.emit_indent();

                if is_print {

                    // print lowers to puts and discards the C return code.
                    self.ir

                        .push_str(&format!("call i32 @puts({})\n", arg_strs.join(", ")));

                    // Model print as returning unit in Sengoo.
                    self.ir.push_str(&format!("{} = add i8 0, 0\n", dest));

                } else if ret_ty == "void" {

                    self.ir.push_str(&format!(

                        "call void {}({})\n",

                        callee,

                        arg_strs.join(", ")

                    ));

                } else {

                    self.ir.push_str(&format!(

                        "{} = call {} {}({})\n",

                        dest,

                        ret_ty,

                        callee,

                        arg_strs.join(", ")

                    ));

                }

            }

            mir::Instruction::Discriminant {

                destination,

                source,

            } => {

                // Construct an enum as `{ discr, payload }`, leaving payload undef when absent.
                let dest = self.local_name(*destination);

                let src = self.local_name(*source);



                // 婵炶揪缍€濞夋洟寮?extractvalue 闂佸憡鐟﹂悧鏇㈠吹椤撱垹绀嗛柕鍫濇噹閻掑ジ鏌涙繝鍕靛劆闁?                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = extractvalue {{ i64, i64 }} {}, 0\n",

                    dest, src

                ));

            }

            mir::Instruction::EnumConstruct {

                destination,

                discriminant,

                payload,

                enum_type: _,

            } => {

                // 闂佸搫顑呯€氫即鍩€椤掑倸校闁诲繐娲︾粙澶愬箚瑜夐崑鎾剁箔鐞涒€充壕?                // 閻熸粎澧楅幐鍛婃櫠?LLVM 婵炴垶鎼╅崢鎯р枔閹达箑鍑犳慨姗嗗亜椤╊剟鎮跺☉鏍у闁靛洦纰嶇粙?`{ 闂佸憡甯囬崐鏇㈠春閸℃稑纾? 闁哄鍋涢埀顒傚枎缁?}`闂?
                let dest = self.local_name(*destination);



                // Materialize the discriminant first.
                let discr_value = format!("{}.discr", dest);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = insertvalue {{ i64, i64 }} undef, i64 {}, 0\n",

                    discr_value, discriminant

                ));



                // Fill payload slot 1 when the enum variant carries data.
                if let Some(payload_local) = payload {

                    let payload_val = self.operand_value(*payload_local, mir_fn);

                    self.emit_indent();

                    self.ir.push_str(&format!(

                        "{} = insertvalue {{ i64, i64 }} {}, i64 {}, 1\n",

                        dest, discr_value, payload_val

                    ));

                } else {

                    // Keep payload slot 1 as undef for payloadless variants.
                    self.emit_indent();

                    self.ir.push_str(&format!(

                        "{} = insertvalue {{ i64, i64 }} {}, i64 undef, 1\n",

                        dest, discr_value

                    ));

                }

            }

            mir::Instruction::ExtractPayload {

                destination,

                source,

            } => {

                // 闂佸湱绮崝鏇°亹閸ヮ剙鍑犳慨姗嗗亜椤╊剟寮堕悙娴嬪亾閻旈銈归梺?
                let dest = self.local_name(*destination);

                let src = self.local_name(*source);



                // 闁哄鍋涢埀顒傚枎缁佺懓霉閿濆懐小缂侇煈鍓涚槐鎺楀箻鐎电硶鍋撻鐐村剭闁告洦鍙庨崕?1 婵炴垶鎼╂禍婊堟偤瑜嶉埢鎾绘倷閸忓浜?                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = extractvalue {{ i64, i64 }} {}, 1\n",

                    dest, src

                ));

            }

            mir::Instruction::Cast {

                destination,

                value,

                to,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*value, mir_fn);

                let src_ty = self.get_local_type(mir_fn, *value);

                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);

                let dst_llvm = self.mir_type_to_llvm_cached(to);



                self.emit_indent();

                match (&src_ty, to) {

                    // Int -> Int闂佹寧绋掔喊宥嗘櫠鐠恒劉鍋撻崷顓熸珪闁?sext闂佹寧绋戦惉鑲╃磽婢跺瞼鐜婚柛鏇ㄥ幗閺?trunc闂?
                    (MIRType::Int(a), MIRType::Int(b)) if a < b => {

                        self.ir.push_str(&format!(

                            "{} = sext {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    (MIRType::Int(a), MIRType::Int(b)) if a > b => {

                        self.ir.push_str(&format!(

                            "{} = trunc {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Float -> Float闂佹寧绋掔喊宥嗘櫠鐠恒劉鍋撻崷顓熸珪闁?fpext闂佹寧绋戦惉鑲╃磽婢跺瞼鐜婚柛鏇ㄥ幗閺?fptrunc闂?
                    (MIRType::Float(a), MIRType::Float(b)) if a < b => {

                        self.ir.push_str(&format!(

                            "{} = fpext {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    (MIRType::Float(a), MIRType::Float(b)) if a > b => {

                        self.ir.push_str(&format!(

                            "{} = fptrunc {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Int -> Float闂佹寧绋掗惌顔界箾閸ヮ剚鍋?sitofp闂佹寧绋戦悧濠傦耿娴ｈ櫣绠旈柨鏇楀亾鐟滄澘娼″顐も偓娑櫳戝▓鍫曞级閻戝棗澧悹鍥╁仱閹瑩鎯傞崫銉ь槴闂?
                    (MIRType::Int(_), MIRType::Float(_)) => {

                        self.ir.push_str(&format!(

                            "{} = sitofp {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Float -> Int闂佹寧绋掗惌顔界箾閸ヮ剚鍋?fptosi闂佹寧绋戦悧濠勬嫚閻愮儤鍊风痪顓炴噺缁侇噣鏌￠崼婵愭Ш妞ゆ垳绶氬畷锝夋煥鐎ｎ偅顔掗梺杞扮鎼存粎妲愬璺何?
                    (MIRType::Float(_), MIRType::Int(_)) => {

                        self.ir.push_str(&format!(

                            "{} = fptosi {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Bool -> Int闂佹寧绋掗惌顔界箾閸ヮ剚鍋?zext闂佹寧绋戝? 闂佸湱顣介弲娑㈠春?iN闂佹寧绋戦ˇ顓㈠焵?
                    (MIRType::Bool, MIRType::Int(_)) => {

                        self.ir.push_str(&format!(

                            "{} = zext {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Int -> Bool闂佹寧绋掗惌顔界箾閸ヮ剚鍋?trunc闂佹寧绋戝鐑?闂佽鎯屾禍婊堝春?i1闂佹寧绋戦ˇ顓㈠焵?
                    (MIRType::Int(_), MIRType::Bool) => {

                        self.ir.push_str(&format!(

                            "{} = trunc {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                    // Same type or unsupported: bitcast as fallback

                    _ => {

                        self.ir.push_str(&format!(

                            "{} = bitcast {} {} to {}\n",

                            dest, src_llvm, src_val, dst_llvm

                        ));

                    }

                }

            }

            mir::Instruction::Bitcast {

                destination,

                value,

                to,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*value, mir_fn);

                let src_ty = self.get_local_type(mir_fn, *value);

                if !common::supports_mir_bitcast(src_ty, to) {

                    return Err(format!(

                        "invalid MIR bitcast from {} to {}",

                        self.mir_type_to_llvm_cached(src_ty),

                        self.mir_type_to_llvm_cached(to)

                    ));

                }

                let src_llvm = self.mir_type_to_llvm_cached(src_ty);

                let dst_llvm = self.mir_type_to_llvm_cached(to);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = bitcast {} {} to {}\n",

                    dest, src_llvm, src_val, dst_llvm

                ));

            }

            mir::Instruction::FieldAddr {

                destination,

                base,

                field,

            } => {

                let dest = self.local_name(*destination);

                let base_reg = self.local_name(*base);

                let base_ty = self.get_local_type(mir_fn, *base);

                let base_llvm = self.mir_type_to_llvm_cached(&base_ty);

                self.emit_indent();

                // FieldAddr gets a pointer to a field within an aggregate type

                // Use getelementptr to compute the field address

                self.ir.push_str(&format!(

                    "{} = getelementptr inbounds {}, {}* {}, i32 0, i32 {}\n",

                    dest, base_llvm, base_llvm, base_reg, field

                ));

            }

            mir::Instruction::Extract {

                destination,

                value,

                index,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*value, mir_fn);

                let src_ty = self.get_local_type(mir_fn, *value);

                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = extractvalue {} {}, {}\n",

                    dest, src_llvm, src_val, index

                ));

            }

            mir::Instruction::Insert {

                destination,

                value,

                field,

                new_value,

            } => {

                let dest = self.local_name(*destination);

                let src_val = self.operand_value(*value, mir_fn);

                let src_ty = self.get_local_type(mir_fn, *value);

                let src_llvm = self.mir_type_to_llvm_cached(&src_ty);

                let new_val = self.operand_value(*new_value, mir_fn);

                let new_ty = self.get_local_type(mir_fn, *new_value);

                let new_llvm = self.mir_type_to_llvm_cached(&new_ty);

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = insertvalue {} {}, {} {}, {}\n",

                    dest, src_llvm, src_val, new_llvm, new_val, field

                ));

            }

            mir::Instruction::Intrinsic {

                destination,

                intrinsic,

                args,

            } => {

                // Generate inline code for intrinsic operations

                match intrinsic {

                    mir::IntrinsicOp::AddWithOverflow => {

                        if args.len() >= 2 {

                            let left_val = self.operand_value(args[0], mir_fn);

                            let right_val = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = add i64 {}, {}\n",

                                    dest_name, left_val, right_val

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::SubWithOverflow => {

                        if args.len() >= 2 {

                            let left_val = self.operand_value(args[0], mir_fn);

                            let right_val = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = sub i64 {}, {}\n",

                                    dest_name, left_val, right_val

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::MulWithOverflow => {

                        if args.len() >= 2 {

                            let left_val = self.operand_value(args[0], mir_fn);

                            let right_val = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = mul i64 {}, {}\n",

                                    dest_name, left_val, right_val

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::Copy { size, .. } => {

                        if args.len() >= 2 {

                            let dest_ptr = self.operand_value(args[0], mir_fn);

                            let src_ptr = self.operand_value(args[1], mir_fn);

                            self.emit_indent();

                            self.ir.push_str(&format!("call void @llvm.memcpy.p0i8.p0i8.i64(i8* {}, i8* {}, i64 {}, i1 false)\n", dest_ptr, src_ptr, size));

                        }

                    }

                    mir::IntrinsicOp::Compare { size, .. } => {

                        if args.len() >= 2 {

                            let left_ptr = self.operand_value(args[0], mir_fn);

                            let right_ptr = self.operand_value(args[1], mir_fn);

                            if let Some(dest) = destination {

                                let dest_name = self.local_name(*dest);

                                self.emit_indent();

                                self.ir.push_str(&format!(

                                    "{} = call i32 @memcmp(i8* {}, i8* {}, i64 {})\n",

                                    dest_name, left_ptr, right_ptr, size

                                ));

                            }

                        }

                    }

                    mir::IntrinsicOp::MemMove { size, .. } => {

                        if args.len() >= 2 {

                            let dest_ptr = self.operand_value(args[0], mir_fn);

                            let src_ptr = self.operand_value(args[1], mir_fn);

                            self.emit_indent();

                            self.ir.push_str(&format!("call void @llvm.memmove.p0i8.p0i8.i64(i8* {}, i8* {}, i64 {}, i1 false)\n", dest_ptr, src_ptr, size));

                        }

                    }

                }

            }

            mir::Instruction::Phi {

                destination,

                incoming,

            } => {

                let dest = self.local_name(*destination);

                let ty = self.get_local_type(mir_fn, *destination);

                let is_void_like = match &ty {

                    MIRType::Unit | MIRType::Never => true,

                    MIRType::Tuple(fields) if fields.is_empty() => true,

                    _ => false,

                };

                if is_void_like {

                    // LLVM does not allow `phi void`.

                    return Ok(());

                }

                let llvm_ty = self.mir_type_to_llvm_cached(&ty);



                let entries: Vec<String> = incoming

                    .iter()

                    .map(|(local, block_idx)| {

                        let val = self.local_name(*local);

                        format!("[ {}, %bb_{} ]", val, block_idx)

                    })

                    .collect();



                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = phi {} {}\n",

                    dest,

                    llvm_ty,

                    entries.join(", ")

                ));

            }

        }

        Ok(())

    }



    fn codegen_terminator(

        &mut self,

        terminator: &mir::Terminator,

        mir_fn: &MirFunction,

    ) -> Result<(), String> {

        match terminator {

            mir::Terminator::Return(value) => {

                if let Some(v) = value {

                    let ty = self.get_local_type(mir_fn, *v);

                    // `main` returning unit still lowers to exit code 0.
                    let is_main_returning_unit =

                        mir_fn.name == "main" && matches!(ty, MIRType::Unit);



                    if is_main_returning_unit {

                        self.emit_indent();

                        self.ir.push_str("ret i64 0\n");

                    } else {

                        // 闁哄鏅滈弻銊ッ洪弽顓燁棃?unit 闂佺锕ら崥瀣渻閸岀偞鏅€光偓閸曘劌浜炬慨妯虹－缁?operand_value 闂佸湱顭堥ˇ闈涖€掗崼鏇炵闁绘鍎ょ粊浼村级閳哄倹鐓ユ繛鍙夌墱閳ь剟娼х€氼剟鎮洪妸鈺侀棷闁靛绲洪崑?
                        let reg = self.operand_value(*v, mir_fn);

                        // unit 闂?LLVM 婵炴垶鎼╅崢楣冨极?i8 0 闁荤偞绋忛崝搴ㄥΦ濮樿埖鏅€光偓閸愶絽浜鹃悘鐐跺亹閻熸繈鏌?void闂?
                        let llvm_ty = if matches!(ty, MIRType::Unit) {

                            "i8".to_string()

                        } else {

                            self.mir_type_to_llvm_cached(&ty)

                        };

                        self.emit_indent();

                        self.ir.push_str(&format!("ret {} {}\n", llvm_ty, reg));

                    }

                } else {

                    // 闂佸搫鍟版慨闈浳熸径濠庡殨闊洦姘ㄧ粻鏌ユ煕閵壯冧粶闁逞屽墮閸氬顪冮崒鐐存櫖閻庣懓瓒卆in` 婵帗绋掗…鍫ヮ敇缂佹ɑ浜ら柡鍌涘缁€鈧?0闂?
                    if mir_fn.name == "main" {

                        self.emit_indent();

                        self.ir.push_str("ret i64 0\n");

                    } else {

                        self.emit_indent();

                        self.ir.push_str("ret void\n");

                    }

                }

            }

            mir::Terminator::Goto(target) => {

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::If {

                cond: condition,

                then_block,

                else_block,

            } => {

                self.emit_indent();

                let cond_reg = self.operand_value(*condition, mir_fn);

                self.ir.push_str(&format!(

                    "br i1 {}, label %bb_{}, label %bb_{}\n",

                    cond_reg, then_block, else_block

                ));

            }

            mir::Terminator::Switch {

                discr,

                targets,

                otherwise,

            } => {

                self.emit_indent();

                let discr_reg = self.operand_value(*discr, mir_fn);



                // 闂佹眹鍨婚崰鎰板垂?switch 闂佸湱顭堝ú锝夊箮?

                self.ir.push_str(&format!(

                    "switch i64 {}, label %bb_{} [",

                    discr_reg, otherwise

                ));



                // 濠电儑缍€椤曆勬叏閻愭畫鎺曠疀鎼淬劌娈?case

                for (value, target) in targets {

                    self.ir.push_str(&format!("\n"));

                    self.emit_indent();

                    self.ir

                        .push_str(&format!("  i64 {}, label %bb_{}", value, target));

                }



                self.ir.push_str(&format!("\n"));

                self.emit_indent();

                self.ir.push_str("]\n");

            }

            mir::Terminator::Break { target } => {

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::Continue { target } => {

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::Unreachable => {

                self.emit_indent();

                self.ir.push_str("unreachable\n");

            }

            mir::Terminator::Call {

                func,

                args,

                destination,

                target,

            } => {

                let dest = self.local_name(*destination);

                let dest_ty = self.get_local_type(mir_fn, *destination);

                let ret_ty = self.mir_type_to_llvm_cached(&dest_ty);



                let arg_strs: Vec<String> = args

                    .iter()

                    .map(|arg| match arg {

                        mir::CallArg::Local(local) => {

                            let arg_ty = self.get_local_type(mir_fn, *local);

                            let llvm_arg_ty = self.mir_type_to_llvm_cached(&arg_ty);

                            let val = self.operand_value(*local, mir_fn);

                            format!("{} {}", llvm_arg_ty, val)

                        }

                        mir::CallArg::Constant(constant) => match constant {

                            MirConstant::Int(n) => format!("i64 {}", n),

                            MirConstant::Bool(b) => format!("i1 {}", if *b { 1 } else { 0 }),

                            MirConstant::Float(f) => format!("double {}", f),

                            MirConstant::String(s) => format!(

                                "i8* @.str.{}",

                                self.strings.iter().position(|x| x == s).unwrap_or(0)

                            ),

                            _ => "i64 0".to_string(),

                        },

                    })

                    .collect();



                self.emit_indent();

                if ret_ty == "void" {

                    self.ir

                        .push_str(&format!("call void @{}({})\n", func, arg_strs.join(", ")));

                } else {

                    self.ir.push_str(&format!(

                        "{} = call {} @{}({})\n",

                        dest,

                        ret_ty,

                        func,

                        arg_strs.join(", ")

                    ));

                }

                self.emit_indent();

                self.ir.push_str(&format!("br label %bb_{}\n", target));

            }

            mir::Terminator::Suspend {
                poll_func,
                future_handle,
                destination,
                ready_block,
                pending_block,
            } => {
                let handle_val = self.operand_value(*future_handle, mir_fn);
                let dest = self.local_name(*destination);

                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = call i64 @{}(i64 {})\n",
                    dest, poll_func, handle_val
                ));

                let cmp = format!("{}_cmp", dest);
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = icmp eq i64 {}, 1\n",
                    cmp, dest
                ));

                self.emit_indent();
                self.ir.push_str(&format!(
                    "br i1 {}, label %bb_{}, label %bb_{}\n",
                    cmp, ready_block, pending_block
                ));
            }

        }

        Ok(())

    }



    /// Build the local-name cache used during code generation.
    pub(crate) fn build_name_cache(&mut self, mir_fn: &MirFunction) {

        self.name_cache.clear();

        // Find the maximum local id to size the cache

        let max_id = mir_fn

            .locals

            .iter()

            .map(|(l, _)| l.index())

            .max()

            .unwrap_or(0);

        // Pre-fill with empty strings up to max_id + 1

        self.name_cache.resize(max_id + 1, String::new());

        for (local, _ty) in &mir_fn.locals {

            // Delegate to shared utility for name generation

            self.name_cache[local.index()] = common::local_name(*local);

        }

    }



    fn local_name(&self, local: Local) -> String {

        let idx = local.index();

        if idx < self.name_cache.len() && !self.name_cache[idx].is_empty() {

            self.name_cache[idx].clone()

        } else {

            common::local_name(local)

        }

    }



    fn emit_indent(&mut self) {

        common::emit_indent(&mut self.ir, self.indent);

    }



    /// 缂傚倸鍊归幐鎼佹偤?MIR 缂備緡鍋夐褔鎮楅悜钘夌?LLVM 缂備緡鍋夐褔鎮楁搴樺亾濞戞瑯娈樻い鎴滅劍缁嬪鎷犺缁€澶愭⒑椤掆偓閻忔繈宕㈤妶澶嬬厒鐎广儱鎷嬪Σ濠氭煕閹烘垶顥㈤柛妯稿€栫粙澶嬫償閵娿垹浜鹃柟鐑樺灩缁夋椽寮堕悜鍡楀鐎规洘鐓℃俊?
    fn mir_type_to_llvm_cached(&mut self, ty: &MIRType) -> String {

        if let Some(cached) = self.type_str_cache.get(ty) {

            return cached.clone();

        }

        // Delegate to shared utility for cache misses

        let result = common::mir_type_to_llvm_str(ty);

        self.type_str_cache.insert(ty.clone(), result.clone());

        result

    }



    fn get_local_type<'a>(&self, mir_fn: &'a MirFunction, local: Local) -> &'a MIRType {

        // 闂佸搫绉烽～澶婄暤?`local.id` 婵?locals 闁荤偞绋忛崝瀣嚈閹达箑鐭楅柡宥庡亯椤箓鏌涢妸銉劀缂佽鲸绻勭槐鎾绘惞鐟欏嫰妲ｉ梺鎼炲劤閸嬨倝鍩€椤戣棄浜鹃梺?`MIR_I64`闂?
        mir_fn

            .locals

            .get(local.index())

            .map(|(_, ty)| ty)

            .unwrap_or(&MIR_I64)

    }



    /// 闂佸吋鍎抽崲鑼躲亹閸ヮ剙绠肩€广儱瀚粙濠囨煛娴ｈ绶叉い鏇ㄥ枟閹棃寮崒娑氭殸 SSA 闂佺锕ㄦ竟鍫ュΥ閸愵亞鐭嗛柟顓熷坊閸?
    /// Resolve an operand to an LLVM value, loading from stack slots when needed.
    fn operand_value(&mut self, local: Local, mir_fn: &MirFunction) -> String {

        // Look up the local metadata before choosing the lowering path.
        let local_info = &mir_fn.locals[local.index()].0;



        match local_info.kind {

            LocalKind::User => {

                // 闂佹椿娼块崝宥夊春濞戙垹鐭楁慨妞诲亾闁革絾妞藉Λ渚€鍩€椤掑倹鍟哄ù锝囶焾鐢?load闂佹寧绋戦懟顖毭哄鍕枖?MIR 婵炴垶鎼╅崢濂告偩閻樺磭顩锋い鎺戝閸嬫挸顫濋鍌氱厬闁荤偞绋忛崝搴ㄥΦ濮橆厾鈻旈柛婵嗗閸曢箖鏌涜閸嬫捇鏌涙繝鍕靛劆闁?
                let ty = self.get_local_type(mir_fn, local);

                let llvm_ty = self.mir_type_to_llvm_cached(ty);

                let temp_reg = format!("%load.{}", self.load_counter);

                self.load_counter += 1;

                self.emit_indent();

                self.ir.push_str(&format!(

                    "{} = load {}, {}* {}\n",

                    temp_reg,

                    llvm_ty,

                    llvm_ty,

                    self.local_name(local)

                ));

                temp_reg

            }

            _ => {

                // 闂佸憡鐟ラ崐褰掑汲閻旂厧违濞达絽鍢查ˇ鏌ユ煛閸愵厽纭剧憸鏉款樀閺屽矁绠涢弴鐘虫儯闂佺儵鏅涢悺銊ф暜鐎涙ɑ濯撮悹鎭掑妽閺嗗繘鎮楅棃娑橆仼闁宦板姂瀹曟娊濡搁妷锕€鈧?

                self.local_name(local)

            }

        }

    }

}

