use super::*;

fn default_host_target_triple() -> &'static str {
    if cfg!(target_os = "windows") {
        "x86_64-pc-windows-msvc"
    } else if cfg!(target_os = "macos") {
        "x86_64-apple-macosx"
    } else {
        "x86_64-unknown-linux-gnu"
    }
}

impl Codegen {
    pub(super) fn emit_header(&mut self) {
        // Start module output with a stable banner used by snapshots.
        self.declarations.push_str("; Sengoo LLVM IR\n");
        self.declarations
            .push_str("; Generated by Sengoo Compiler\n\n");

        // Keep the target triple aligned with the selected build target so clang does not warn.
        let triple = self
            .target_triple
            .clone()
            .unwrap_or_else(|| default_host_target_triple().to_string());
        self.declarations
            .push_str(&format!("target triple = \"{triple}\"\n\n"));
    }

    fn estimate_ir_capacity(mir_fns: &[MirFunction]) -> usize {
        let mut estimate = 1024;

        for func in mir_fns {
            estimate += func.locals.len() * 30;
            estimate += func.basic_blocks.len() * 20;

            for bb in &func.basic_blocks {
                estimate += bb.instructions.len() * 60;
                if bb.terminator.is_some() {
                    estimate += 40;
                }
            }

            estimate += 80;
        }

        estimate
    }

    fn prepare_codegen_buffers(&mut self) {
        self.ir.clear();
        self.declarations.clear();
        self.strings.clear();
        self.string_counter = 0;
        self.name_cache.clear();
        self.type_str_cache.clear();
        self.load_counter = 0;
        self.emit_args_main_wrapper = false;
        self.emit_header();
        self.declare_runtime_functions();
    }

    pub(super) fn emit_module_ir(&mut self, mir_fns: &[MirFunction]) -> Result<(), String> {
        self.prepare_codegen_buffers();
        self.emit_args_main_wrapper = Self::module_uses_args_runtime(mir_fns);
        self.maybe_declare_args_runtime_functions();

        let capacity = Self::estimate_ir_capacity(mir_fns);
        self.ir.reserve(capacity);

        for mir_fn in mir_fns {
            self.collect_string_constants(mir_fn);
        }

        self.maybe_declare_spawn_runtime_function(mir_fns);
        self.maybe_declare_select_runtime_function(mir_fns);
        self.maybe_declare_sleep_runtime_functions(mir_fns);
        self.maybe_declare_timeout_runtime_functions(mir_fns);
        self.maybe_declare_timeout_cancel_runtime_functions(mir_fns);
        self.maybe_declare_concurrent_async_runtime_functions(mir_fns);
        self.maybe_declare_async_task_runtime_functions(mir_fns);
        self.emit_string_constants();
        self.emit_struct_types(mir_fns);

        for mir_fn in mir_fns {
            self.codegen_function(mir_fn)?;
        }

        self.emit_args_main_wrapper(mir_fns)?;
        self.emit_export_symbol_wrappers(mir_fns);
        Ok(())
    }

    pub(super) fn emitted_function_name<'a>(&self, name: &'a str) -> &'a str {
        if self.emit_args_main_wrapper && name == "main" {
            "sengoo_user_main"
        } else {
            name
        }
    }

    fn args_runtime_function_name(func: &str) -> bool {
        matches!(
            func,
            "sengoo_args_len" | "sengoo_arg_len" | "sengoo_arg_copy"
        )
    }

    fn module_uses_args_runtime(mir_fns: &[MirFunction]) -> bool {
        mir_fns.iter().any(|mir_fn| {
            mir_fn.instructions.iter().any(|inst| {
                matches!(
                    inst,
                    mir::Instruction::Call { func, .. }
                        if Self::args_runtime_function_name(func)
                )
            }) || mir_fn.basic_blocks.iter().any(|bb| {
                matches!(
                    &bb.terminator,
                    Some(mir::Terminator::Call { func, .. })
                        if Self::args_runtime_function_name(func)
                )
            })
        })
    }

    fn maybe_declare_args_runtime_functions(&mut self) {
        if !self.emit_args_main_wrapper {
            return;
        }

        for decl in [
            "declare void @sengoo_args_init(i64, i64)\n",
            "declare i64 @sengoo_args_len()\n",
            "declare i64 @sengoo_arg_len(i64)\n",
            "declare i64 @sengoo_arg_copy(i64, i64, i64)\n",
        ] {
            if !self.declarations.contains(decl) {
                self.declarations.push_str(decl);
            }
        }
    }

    fn emit_args_main_wrapper(&mut self, mir_fns: &[MirFunction]) -> Result<(), String> {
        if !self.emit_args_main_wrapper {
            return Ok(());
        }

        let Some(main_fn) = mir_fns.iter().find(|f| f.name == "main") else {
            return Err("std::args requires a source-level main function".to_string());
        };
        if !main_fn.params.is_empty() {
            return Err("std::args requires a zero-argument source-level main".to_string());
        }

        let ret_ty = self.mir_type_to_llvm_cached(&main_fn.return_type);

        self.ir.push_str("\n; Args runtime entry wrapper\n");
        self.ir
            .push_str("define i32 @main(i32 %argc, i8** %argv) {\n");
        self.indent += 1;
        self.ir.push_str("bb_0:\n");
        self.indent += 1;
        self.emit_indent();
        self.ir.push_str("%argc64 = sext i32 %argc to i64\n");
        self.emit_indent();
        self.ir.push_str("%argv64 = ptrtoint i8** %argv to i64\n");
        self.emit_indent();
        self.ir
            .push_str("call void @sengoo_args_init(i64 %argc64, i64 %argv64)\n");

        match ret_ty.as_str() {
            "void" => {
                self.emit_indent();
                self.ir.push_str("call void @sengoo_user_main()\n");
                self.emit_indent();
                self.ir.push_str("ret i32 0\n");
            }
            "i64" => {
                self.emit_indent();
                self.ir.push_str("%result = call i64 @sengoo_user_main()\n");
                self.emit_indent();
                self.ir.push_str("%exit_code = trunc i64 %result to i32\n");
                self.emit_indent();
                self.ir.push_str("ret i32 %exit_code\n");
            }
            "i32" => {
                self.emit_indent();
                self.ir.push_str("%result = call i32 @sengoo_user_main()\n");
                self.emit_indent();
                self.ir.push_str("ret i32 %result\n");
            }
            _ => {
                self.emit_indent();
                self.ir
                    .push_str(&format!("call {} @sengoo_user_main()\n", ret_ty));
                self.emit_indent();
                self.ir.push_str("ret i32 0\n");
            }
        }

        self.indent -= 1;
        self.indent -= 1;
        self.ir.push_str("}\n");
        Ok(())
    }

    fn emit_export_symbol_wrappers(&mut self, mir_fns: &[MirFunction]) {
        if self.ffi.export_symbols.is_empty() {
            return;
        }

        let mut emitted = HashSet::new();
        let export_symbols = self.ffi.export_symbols.clone();

        for export in export_symbols {
            if export.export_name == export.internal_name {
                continue;
            }
            if !emitted.insert(export.export_name.clone()) {
                continue;
            }

            let Some(target) = mir_fns.iter().find(|f| f.name == export.internal_name) else {
                continue;
            };

            let ret_ty = self.mir_type_to_llvm_cached(&target.return_type);
            let params = target
                .params
                .iter()
                .enumerate()
                .map(|(idx, ty)| {
                    let llvm = self.mir_type_to_llvm_cached(ty);
                    format!("{} %arg_{}", llvm, idx)
                })
                .collect::<Vec<_>>();
            let args = target
                .params
                .iter()
                .enumerate()
                .map(|(idx, ty)| {
                    let llvm = self.mir_type_to_llvm_cached(ty);
                    format!("{} %arg_{}", llvm, idx)
                })
                .collect::<Vec<_>>();

            self.ir.push('\n');
            self.ir.push_str(&format!(
                "; Export wrapper: {} -> {}\n",
                export.internal_name, export.export_name
            ));
            self.ir.push_str(&format!(
                "define {} @{}({}) {{\n",
                ret_ty,
                export.export_name,
                params.join(", ")
            ));

            self.indent += 1;
            self.emit_indent();

            let target_name = self.emitted_function_name(&export.internal_name);
            if ret_ty == "void" {
                self.ir.push_str(&format!(
                    "call void @{}({})\n",
                    target_name,
                    args.join(", ")
                ));
                self.emit_indent();
                self.ir.push_str("ret void\n");
            } else {
                self.ir.push_str(&format!(
                    "%export_ret = call {} @{}({})\n",
                    ret_ty,
                    target_name,
                    args.join(", ")
                ));
                self.emit_indent();
                self.ir.push_str(&format!("ret {} %export_ret\n", ret_ty));
            }

            self.indent -= 1;
            self.ir.push_str("}\n");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_export_symbol_wrappers_skips_duplicates_and_self_exports() {
        let ffi = FfiCodegenConfig {
            export_symbols: vec![
                ExportSymbol {
                    internal_name: "foo".to_string(),
                    export_name: "foo_alias".to_string(),
                },
                ExportSymbol {
                    internal_name: "foo".to_string(),
                    export_name: "foo_alias".to_string(),
                },
                ExportSymbol {
                    internal_name: "foo".to_string(),
                    export_name: "foo".to_string(),
                },
            ],
            ..FfiCodegenConfig::default()
        };
        let mut cg = Codegen::with_ffi(ffi);
        let mir_fn = MirFunction::new("foo".to_string(), vec![MIRType::Int(64)], MIRType::Int(64));

        cg.emit_export_symbol_wrappers(&[mir_fn]);

        assert_eq!(cg.ir.matches("define i64 @foo_alias(").count(), 1);
        assert!(cg.ir.contains("; Export wrapper: foo -> foo_alias"));
        assert!(!cg.ir.contains("define i64 @foo(i64 %arg_0)"));
    }
}
