use std::fmt;

/// 关键字枚举（Python 风格）
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Keyword {
    Def, // def 函数名() -> type （Python 风格函数定义）
    Fn,  // fn(A, B) -> C （函数类型语法）
    Class,
    Struct,
    Enum,
    Impl,
    Trait,
    Type,
    Const,
    Static,
    Let,
    If,
    Elif, // Python 风格的 else if
    Else,
    Match,
    Case,
    Default,
    For,
    While,
    Loop,
    Break,
    Continue,
    Return,
    Yield,
    Await,
    Async,
    Parallel,
    Import,
    From,
    As,
    Export,
    Extern,
    Unsafe,
    Try,
    Except, // Python 风格的 catch
    Finally,
    Raise, // Python 风格的 throw
    Throw,
    Pub,
    Priv,
    Where,
    Requires,
    Ensures,
    SelfKw,
    SelfLower,
    True,
    False,
    None, // Python 风格的 null
    In,
    Is,
    NotIn,
    IsNot,
    Pass, // Python 的空语句
    Not,  // Python 风格的 !
    And,  // Python 风格的 &&
    Or,   // Python 风格的 ||
}

impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Keyword::Def => "def",
            Keyword::Fn => "fn",
            Keyword::Class => "class",
            Keyword::Struct => "struct",
            Keyword::Enum => "enum",
            Keyword::Impl => "impl",
            Keyword::Trait => "trait",
            Keyword::Type => "type",
            Keyword::Const => "const",
            Keyword::Static => "static",
            Keyword::Let => "let",
            Keyword::If => "if",
            Keyword::Elif => "elif",
            Keyword::Else => "else",
            Keyword::Match => "match",
            Keyword::Case => "case",
            Keyword::Default => "default",
            Keyword::For => "for",
            Keyword::While => "while",
            Keyword::Loop => "loop",
            Keyword::Break => "break",
            Keyword::Continue => "continue",
            Keyword::Return => "return",
            Keyword::Yield => "yield",
            Keyword::Await => "await",
            Keyword::Async => "async",
            Keyword::Parallel => "parallel",
            Keyword::Import => "import",
            Keyword::From => "from",
            Keyword::As => "as",
            Keyword::Export => "export",
            Keyword::Extern => "extern",
            Keyword::Unsafe => "unsafe",
            Keyword::Try => "try",
            Keyword::Except => "except",
            Keyword::Finally => "finally",
            Keyword::Raise => "raise",
            Keyword::Throw => "throw",
            Keyword::Pub => "pub",
            Keyword::Priv => "priv",
            Keyword::Where => "where",
            Keyword::Requires => "requires",
            Keyword::Ensures => "ensures",
            Keyword::SelfKw => "Self",
            Keyword::SelfLower => "self",
            Keyword::True => "true",
            Keyword::False => "false",
            Keyword::None => "none",
            Keyword::In => "in",
            Keyword::Is => "is",
            Keyword::NotIn => "not in",
            Keyword::IsNot => "is not",
            Keyword::Pass => "pass",
            Keyword::Not => "not",
            Keyword::And => "and",
            Keyword::Or => "or",
        };
        write!(f, "{}", s)
    }
}

impl Keyword {
    /// 从字符串解析关键字
    pub fn lookup(s: &str) -> Option<Self> {
        match s {
            "def" => Some(Keyword::Def),
            "fn" => Some(Keyword::Fn), // 函数类型
            "class" => Some(Keyword::Class),
            "struct" => Some(Keyword::Struct),
            "enum" => Some(Keyword::Enum),
            "impl" => Some(Keyword::Impl),
            "trait" => Some(Keyword::Trait),
            "type" => Some(Keyword::Type),
            "const" => Some(Keyword::Const),
            "static" => Some(Keyword::Static),
            "let" => Some(Keyword::Let),
            "if" => Some(Keyword::If),
            "elif" => Some(Keyword::Elif),
            "else" => Some(Keyword::Else),
            "match" => Some(Keyword::Match),
            "case" => Some(Keyword::Case),
            "default" => Some(Keyword::Default),
            "for" => Some(Keyword::For),
            "while" => Some(Keyword::While),
            "loop" => Some(Keyword::Loop),
            "break" => Some(Keyword::Break),
            "continue" => Some(Keyword::Continue),
            "return" => Some(Keyword::Return),
            "yield" => Some(Keyword::Yield),
            "await" => Some(Keyword::Await),
            "async" => Some(Keyword::Async),
            "parallel" => Some(Keyword::Parallel),
            "import" => Some(Keyword::Import),
            "from" => Some(Keyword::From),
            "as" => Some(Keyword::As),
            "export" => Some(Keyword::Export),
            "extern" => Some(Keyword::Extern),
            "unsafe" => Some(Keyword::Unsafe),
            "try" => Some(Keyword::Try),
            "except" => Some(Keyword::Except),
            "finally" => Some(Keyword::Finally),
            "raise" => Some(Keyword::Raise),
            "throw" => Some(Keyword::Throw),
            "pub" => Some(Keyword::Pub),
            "priv" => Some(Keyword::Priv),
            "where" => Some(Keyword::Where),
            "requires" => Some(Keyword::Requires),
            "ensures" => Some(Keyword::Ensures),
            "Self" => Some(Keyword::SelfKw),
            "self" => Some(Keyword::SelfLower),
            "true" => Some(Keyword::True),
            "false" => Some(Keyword::False),
            "none" => Some(Keyword::None),
            "null" => Some(Keyword::None), // 兼容
            "in" => Some(Keyword::In),
            "is" => Some(Keyword::Is),
            "pass" => Some(Keyword::Pass),
            "not" => Some(Keyword::Not),
            "and" => Some(Keyword::And),
            "or" => Some(Keyword::Or),
            _ => None,
        }
    }
}
