; Sengoo LLVM IR
; Generated by Sengoo Compiler

target triple = "x86_64-pc-windows-msvc"

; External C library functions
declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)

; Sengoo runtime print functions
declare void @sengoo_print_i64(i64)
declare void @sengoo_print_bool(i64)
declare void @sengoo_print_f64(double)
declare void @sengoo_print_str(i8*)

; Sengoo runtime string functions
declare i64 @sengoo_str_len(i8*)
declare i8* @sengoo_str_concat(i8*, i8*)
declare i64 @sengoo_str_eq(i8*, i8*)
declare i64 @sengoo_str_compare(i8*, i8*)

; Sengoo async runtime functions
declare i64 @sengoo_async_frame_alloc(i64)
declare void @sengoo_async_frame_free(i64)
declare void @sengoo_async_frame_store(i64, i64, i64)
declare i64 @sengoo_async_frame_load(i64, i64)
declare i64 @sengoo_async_run_main_i64()

; LLVM integer overflow check intrinsics
declare { i8, i1 } @llvm.sadd.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.ssub.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.smul.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.uadd.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.usub.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.umul.with.overflow.i8(i8, i8)
declare { i16, i1 } @llvm.sadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.ssub.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.smul.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.uadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.usub.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.umul.with.overflow.i16(i16, i16)
declare { i32, i1 } @llvm.sadd.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.ssub.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.smul.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.uadd.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.usub.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.umul.with.overflow.i32(i32, i32)
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.uadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.usub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.umul.with.overflow.i64(i64, i64)
declare void @sengoo_panic_integer_overflow(i64)
declare void @sengoo_panic_division_by_zero(i64)

declare i64 @sengoo_async_sleep__start(i64)
declare i64 @sengoo_async_sleep__poll(i64)
declare void @sengoo_async_sleep__result(i64)
declare i1 @sengoo_async_sleep__cancel(i64)
declare void @sengoo_async_sleep__drop(i64)
declare i64 @sengoo_async_timeout_bool__start(i64, i64, i64)
declare i64 @sengoo_async_timeout_bool__poll(i64)
declare i1 @sengoo_async_timeout_bool__result(i64)
declare i1 @sengoo_async_timeout_bool__cancel(i64)
declare void @sengoo_async_timeout_bool__drop(i64)

; Function: step
define i64 @step(i64 %l_1) {
bb_0:
    %t_2 = add i64 0, 1
    %ov.check.0 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %l_1, i64 %t_2)
    %t_3 = extractvalue { i64, i1 } %ov.check.0, 0
    %ov.flag.0 = extractvalue { i64, i1 } %ov.check.0, 1
    %ov.flag.i64.0 = zext i1 %ov.flag.0 to i64
    call void @sengoo_panic_integer_overflow(i64 %ov.flag.i64.0)
    ret i64 %t_3
}

; Function: step__start
define i64 @step__start(i64 %l_1) {
bb_0:
    %t_2 = add i64 0, 3
    %t_3 = call i64 @sengoo_async_frame_alloc(i64 %t_2)
    %t_4 = add i64 0, 0
    call void @sengoo_async_frame_store(i64 %t_3, i64 %t_4, i64 %t_4)
    %t_6 = add i64 0, 2
    call void @sengoo_async_frame_store(i64 %t_3, i64 %t_6, i64 %l_1)
    ret i64 %t_3
}

; Function: step__poll
define i64 @step__poll(i64 %l_1) {
bb_0:
    %t_2 = add i64 0, 0
    %t_3 = call i64 @sengoo_async_frame_load(i64 %l_1, i64 %t_2)
    switch i64 %t_3, label %bb_2 [
      i64 0, label %bb_1
    ]
bb_1:
    %t_6 = add i64 0, 2
    %t_5 = call i64 @sengoo_async_frame_load(i64 %l_1, i64 %t_6)
    %t_4 = call i64 @step(i64 %t_5)
    %t_7 = add i64 0, 1
    %t_8 = add i64 0, 1
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_8, i64 %t_4)
    %t_10 = add i64 0, 1
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_2, i64 %t_10)
    br label %bb_2
bb_2:
    %t_12 = add i64 0, 1
    ret i64 %t_12
}

; Function: step__result
define i64 @step__result(i64 %l_1) {
bb_0:
    %t_3 = add i64 0, 1
    %t_2 = call i64 @sengoo_async_frame_load(i64 %l_1, i64 %t_3)
    call void @sengoo_async_frame_free(i64 %l_1)
    ret i64 %t_2
}

; Function: main__start
define i64 @main__start() {
bb_0:
    %t_1 = add i64 0, 3
    %t_2 = call i64 @sengoo_async_frame_alloc(i64 %t_1)
    %t_3 = add i64 0, 0
    call void @sengoo_async_frame_store(i64 %t_2, i64 %t_3, i64 %t_3)
    ret i64 %t_2
}

; Function: main__poll
define i64 @main__poll(i64 %l_1) {
bb_0:
    %u_6 = alloca i64
    %t_12 = add i64 0, 0
    %t_11 = call i64 @sengoo_async_frame_load(i64 %l_1, i64 %t_12)
    switch i64 %t_11, label %bb_10 [
      i64 0, label %bb_1
      i64 1, label %bb_6
    ]
bb_1:
    %t_2 = add i64 0, 40
    %t_3 = call i64 @step__start(i64 %t_2)
    %t_15 = call i64 @step__poll(i64 %t_3)
    switch i64 %t_15, label %bb_7 [
      i64 1, label %bb_9
    ]
bb_2:
    %t_4 = call i64 @step__result(i64 %t_14)
    store i64 %t_4, i64* %u_6
    %t_7 = add i64 0, 41
    %load.0 = load i64, i64* %u_6
    %t_8 = icmp eq i64 %load.0, %t_7
    br i1 %t_8, label %bb_4, label %bb_3
bb_3:
    %t_9 = add i64 0, 0
    br label %bb_5
bb_4:
    %phi.load.10.4.6 = load i64, i64* %u_6
    br label %bb_5
bb_5:
    %t_10 = phi i64 [ %phi.load.10.4.6, %bb_4 ], [ %t_9, %bb_3 ]
    %t_22 = add i64 0, 1
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_22, i64 %t_10)
    %t_24 = add i64 0, 2
    %t_25 = add i64 0, 0
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_25, i64 %t_24)
    %t_27 = add i64 0, 1
    ret i64 %t_27
bb_6:
    %t_29 = add i64 0, 2
    %t_28 = call i64 @sengoo_async_frame_load(i64 %l_1, i64 %t_29)
    %t_30 = call i64 @step__poll(i64 %t_28)
    switch i64 %t_30, label %bb_8 [
      i64 1, label %bb_9
    ]
bb_7:
    %t_16 = add i64 0, 2
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_16, i64 %t_3)
    %t_18 = add i64 0, 1
    %t_19 = add i64 0, 0
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_19, i64 %t_18)
    %t_21 = add i64 0, 0
    ret i64 %t_21
bb_8:
    %t_31 = add i64 0, 2
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_31, i64 %t_28)
    %t_33 = add i64 0, 1
    %t_34 = add i64 0, 0
    call void @sengoo_async_frame_store(i64 %l_1, i64 %t_34, i64 %t_33)
    %t_36 = add i64 0, 0
    ret i64 %t_36
bb_9:
    %t_14 = phi i64 [ %t_3, %bb_1 ], [ %t_28, %bb_6 ]
    br label %bb_2
bb_10:
    %t_13 = add i64 0, 1
    ret i64 %t_13
}

; Function: main__result
define i64 @main__result(i64 %l_1) {
bb_0:
    %t_3 = add i64 0, 1
    %t_2 = call i64 @sengoo_async_frame_load(i64 %l_1, i64 %t_3)
    call void @sengoo_async_frame_free(i64 %l_1)
    ret i64 %t_2
}

; Function: sengoo_async_poll_dispatch
define i64 @sengoo_async_poll_dispatch(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
      i64 4, label %bb_2
      i64 3, label %bb_3
      i64 1, label %bb_4
      i64 2, label %bb_5
    ]
bb_1:
    %t_7 = add i64 0, 1
    ret i64 %t_7
bb_2:
    %t_3 = call i64 @step__poll(i64 %l_2)
    ret i64 %t_3
bb_3:
    %t_4 = call i64 @main__poll(i64 %l_2)
    ret i64 %t_4
bb_4:
    %t_5 = call i64 @sengoo_async_sleep__poll(i64 %l_2)
    ret i64 %t_5
bb_5:
    %t_6 = call i64 @sengoo_async_timeout_bool__poll(i64 %l_2)
    ret i64 %t_6
}

; Function: sengoo_async_cancel_dispatch
define i1 @sengoo_async_cancel_dispatch(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
      i64 4, label %bb_2
      i64 3, label %bb_3
      i64 1, label %bb_4
      i64 2, label %bb_5
    ]
bb_1:
    %t_9 = add i1 0, 0
    ret i1 %t_9
bb_2:
    call void @sengoo_async_frame_free(i64 %l_2)
    %t_4 = add i1 0, 1
    ret i1 %t_4
bb_3:
    call void @sengoo_async_frame_free(i64 %l_2)
    %t_6 = add i1 0, 1
    ret i1 %t_6
bb_4:
    %t_7 = call i1 @sengoo_async_sleep__cancel(i64 %l_2)
    ret i1 %t_7
bb_5:
    %t_8 = call i1 @sengoo_async_timeout_bool__cancel(i64 %l_2)
    ret i1 %t_8
}

; Function: sengoo_async_drop_dispatch
define void @sengoo_async_drop_dispatch(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
      i64 4, label %bb_2
      i64 3, label %bb_3
      i64 1, label %bb_4
      i64 2, label %bb_5
    ]
bb_1:
    ret void
bb_2:
    call void @sengoo_async_frame_free(i64 %l_2)
    ret void
bb_3:
    call void @sengoo_async_frame_free(i64 %l_2)
    ret void
bb_4:
    call void @sengoo_async_sleep__drop(i64 %l_2)
    ret void
bb_5:
    call void @sengoo_async_timeout_bool__drop(i64 %l_2)
    ret void
}

; Function: sengoo_async_result_dispatch_bool
define i1 @sengoo_async_result_dispatch_bool(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
    ]
bb_1:
    %t_3 = add i1 0, 0
    ret i1 %t_3
}

; Function: sengoo_async_result_dispatch_f32
define float @sengoo_async_result_dispatch_f32(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
    ]
bb_1:
    %t_3 = fadd float 0.0, 0.0
    ret float %t_3
}

; Function: sengoo_async_result_dispatch_f64
define double @sengoo_async_result_dispatch_f64(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
    ]
bb_1:
    %t_3 = fadd double 0.0, 0.0
    ret double %t_3
}

; Function: sengoo_async_result_dispatch_i16
define i16 @sengoo_async_result_dispatch_i16(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
    ]
bb_1:
    %t_3 = add i16 0, 0
    ret i16 %t_3
}

; Function: sengoo_async_result_dispatch_i32
define i32 @sengoo_async_result_dispatch_i32(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
    ]
bb_1:
    %t_3 = add i32 0, 0
    ret i32 %t_3
}

; Function: sengoo_async_result_dispatch_i64
define i64 @sengoo_async_result_dispatch_i64(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
      i64 4, label %bb_2
      i64 3, label %bb_3
    ]
bb_1:
    %t_5 = add i64 0, 0
    ret i64 %t_5
bb_2:
    %t_3 = call i64 @step__result(i64 %l_2)
    ret i64 %t_3
bb_3:
    %t_4 = call i64 @main__result(i64 %l_2)
    ret i64 %t_4
}

; Function: sengoo_async_result_dispatch_i8
define i8 @sengoo_async_result_dispatch_i8(i64 %l_1, i64 %l_2) {
bb_0:
    switch i64 %l_1, label %bb_1 [
    ]
bb_1:
    %t_3 = add i8 0, 0
    ret i8 %t_3
}

; Function: main
define i64 @main() {
bb_0:
    %t_1 = call i64 @sengoo_async_run_main_i64()
    ret i64 %t_1
}
