; Sengoo LLVM IR
; Generated by Sengoo Compiler

target triple = "x86_64-pc-windows-msvc"

; External C library functions
declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)

; Sengoo runtime print functions
declare void @sengoo_print_i64(i64)
declare void @sengoo_print_bool(i64)
declare void @sengoo_print_f64(double)
declare void @sengoo_print_str(i8*)

; Sengoo runtime string functions
declare i64 @sengoo_str_len(i8*)
declare i8* @sengoo_str_concat(i8*, i8*)
declare i64 @sengoo_str_eq(i8*, i8*)
declare i64 @sengoo_str_compare(i8*, i8*)

; Sengoo async runtime functions
declare i64 @sengoo_async_frame_alloc(i64)
declare void @sengoo_async_frame_free(i64)
declare void @sengoo_async_frame_store(i64, i64, i64)
declare i64 @sengoo_async_frame_load(i64, i64)
declare i64 @sengoo_async_run_main_i64()

; LLVM integer overflow check intrinsics
declare { i8, i1 } @llvm.sadd.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.ssub.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.smul.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.uadd.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.usub.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.umul.with.overflow.i8(i8, i8)
declare { i16, i1 } @llvm.sadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.ssub.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.smul.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.uadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.usub.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.umul.with.overflow.i16(i16, i16)
declare { i32, i1 } @llvm.sadd.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.ssub.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.smul.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.uadd.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.usub.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.umul.with.overflow.i32(i32, i32)
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.uadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.usub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.umul.with.overflow.i64(i64, i64)
declare void @sengoo_panic_integer_overflow(i64)
declare void @sengoo_panic_division_by_zero(i64)


; Function: classify
define i64 @classify(i64 %l_1) {
bb_0:
    %u_4 = alloca i64
    %t_2 = add i64 0, 1
    %ov.check.0 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %l_1, i64 %t_2)
    %t_3 = extractvalue { i64, i1 } %ov.check.0, 0
    %ov.flag.0 = extractvalue { i64, i1 } %ov.check.0, 1
    %ov.flag.i64.0 = zext i1 %ov.flag.0 to i64
    call void @sengoo_panic_integer_overflow(i64 %ov.flag.i64.0)
    store i64 %t_3, i64* %u_4
    %t_5 = add i64 0, 10
    %load.0 = load i64, i64* %u_4
    %t_6 = icmp sgt i64 %load.0, %t_5
    br i1 %t_6, label %bb_1, label %bb_2
bb_1:
    %t_7 = add i64 0, 2
    %load.1 = load i64, i64* %u_4
    %ov.check.1 = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %load.1, i64 %t_7)
    %t_8 = extractvalue { i64, i1 } %ov.check.1, 0
    %ov.flag.1 = extractvalue { i64, i1 } %ov.check.1, 1
    %ov.flag.i64.1 = zext i1 %ov.flag.1 to i64
    call void @sengoo_panic_integer_overflow(i64 %ov.flag.i64.1)
    br label %bb_3
bb_2:
    %t_9 = add i64 0, 3
    %load.2 = load i64, i64* %u_4
    %ov.check.2 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %load.2, i64 %t_9)
    %t_10 = extractvalue { i64, i1 } %ov.check.2, 0
    %ov.flag.2 = extractvalue { i64, i1 } %ov.check.2, 1
    %ov.flag.i64.2 = zext i1 %ov.flag.2 to i64
    call void @sengoo_panic_integer_overflow(i64 %ov.flag.i64.2)
    br label %bb_3
bb_3:
    %t_11 = phi i64 [ %t_8, %bb_1 ], [ %t_10, %bb_2 ]
    ret i64 %t_11
}

; Function: main
define i64 @main() {
bb_0:
    %t_1 = add i64 0, 9
    %t_2 = call i64 @classify(i64 %t_1)
    ret i64 %t_2
}
