; Sengoo LLVM IR
; Generated by Sengoo Compiler

target triple = "x86_64-pc-windows-msvc"

; External C library functions
declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)

; Sengoo runtime print functions
declare void @sengoo_print_i64(i64)
declare void @sengoo_print_bool(i64)
declare void @sengoo_print_f64(double)
declare void @sengoo_print_str(i8*)

; Sengoo runtime string functions
declare i64 @sengoo_str_len(i8*)
declare i8* @sengoo_str_concat(i8*, i8*)
declare i64 @sengoo_str_eq(i8*, i8*)
declare i64 @sengoo_str_compare(i8*, i8*)

; Sengoo async runtime functions
declare i64 @sengoo_async_frame_alloc(i64)
declare void @sengoo_async_frame_free(i64)
declare void @sengoo_async_frame_store(i64, i64, i64)
declare i64 @sengoo_async_frame_load(i64, i64)
declare i64 @sengoo_async_run_main_i64()

; LLVM integer overflow check intrinsics
declare { i8, i1 } @llvm.sadd.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.ssub.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.smul.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.uadd.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.usub.with.overflow.i8(i8, i8)
declare { i8, i1 } @llvm.umul.with.overflow.i8(i8, i8)
declare { i16, i1 } @llvm.sadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.ssub.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.smul.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.uadd.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.usub.with.overflow.i16(i16, i16)
declare { i16, i1 } @llvm.umul.with.overflow.i16(i16, i16)
declare { i32, i1 } @llvm.sadd.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.ssub.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.smul.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.uadd.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.usub.with.overflow.i32(i32, i32)
declare { i32, i1 } @llvm.umul.with.overflow.i32(i32, i32)
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.uadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.usub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.umul.with.overflow.i64(i64, i64)
declare void @sengoo_panic_integer_overflow(i64)
declare void @sengoo_panic_division_by_zero(i64)

%Point = type { i64, i64 }

; Function: Point_sum
define i64 @Point_sum(%Point %l_1) {
bb_0:
    %t_2 = extractvalue %Point %l_1, 0
    %t_3 = extractvalue %Point %l_1, 1
    %ov.check.0 = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %t_2, i64 %t_3)
    %t_4 = extractvalue { i64, i1 } %ov.check.0, 0
    %ov.flag.0 = extractvalue { i64, i1 } %ov.check.0, 1
    %ov.flag.i64.0 = zext i1 %ov.flag.0 to i64
    call void @sengoo_panic_integer_overflow(i64 %ov.flag.i64.0)
    ret i64 %t_4
}

; Function: main
define i64 @main() {
bb_0:
    %u_4 = alloca %Point
    %t_1 = add i64 0, 3
    %t_2 = add i64 0, 4
    %t_3.f0 = insertvalue %Point undef, i64 %t_1, 0
    %t_3 = insertvalue %Point %t_3.f0, i64 %t_2, 1
    store %Point %t_3, %Point* %u_4
    %load.0 = load %Point, %Point* %u_4
    %t_5 = call i64 @Point_sum(%Point %load.0)
    ret i64 %t_5
}
