//! Shared helpers for `dyn Trait` dynamic dispatch (vtable) lowering.
//!
//! A `&dyn Trait` value is represented at runtime as a two-word fat pointer
//! struct `{ data: i8*, vtable: i8* }`:
//! - `data` points at the concrete receiver value.
//! - `vtable` points at a per-`(Trait, ConcreteType)` global table of function
//!   pointers, one slot per object-safe trait method (in declaration order).
//!
//! Because concrete `&self` methods take the receiver *by value* in the current
//! calling convention, each vtable slot points at a generated *shim* function
//! that takes the receiver by pointer, loads the concrete value, and forwards to
//! the real method. This keeps dynamic dispatch ABI-compatible with the existing
//! monomorphic call path.

use crate::hir::{HIRType, HIRTypeKind};
use crate::mir::MIRType;

/// Prefix marking a MIR struct type as a `dyn Trait` fat pointer.
pub(crate) const DYN_STRUCT_PREFIX: &str = "__dyn_";

/// Field separator for generated vtable/shim symbol names. `$` is a valid
/// unquoted LLVM identifier character and never appears in Sengoo identifiers,
/// so it keeps trait/type/method components unambiguous when parsed back.
const SEP: char = '$';

/// Name of the fat-pointer struct type for `&dyn Trait`.
pub(crate) fn dyn_struct_name(trait_name: &str) -> String {
    format!("{DYN_STRUCT_PREFIX}{trait_name}")
}

/// Recover the trait name from a `dyn` fat-pointer struct type name.
pub(crate) fn trait_name_from_dyn_struct(name: &str) -> Option<&str> {
    name.strip_prefix(DYN_STRUCT_PREFIX)
}

/// The MIR type used for a `&dyn Trait` fat pointer.
pub(crate) fn dyn_fat_ptr_type(trait_name: &str) -> MIRType {
    MIRType::Struct {
        name: dyn_struct_name(trait_name),
        fields: vec![
            ("data".to_string(), MIRType::Ptr(Box::new(MIRType::Int(8)))),
            (
                "vtable".to_string(),
                MIRType::Ptr(Box::new(MIRType::Int(8))),
            ),
        ],
    }
}

/// Returns `Some(trait_name)` if `ty` is a `dyn Trait` fat-pointer struct.
pub(crate) fn dyn_trait_of_type(ty: &MIRType) -> Option<&str> {
    match ty {
        MIRType::Struct { name, .. } => trait_name_from_dyn_struct(name),
        _ => None,
    }
}

/// Global symbol name of the vtable for `(trait, concrete_type)`.
pub(crate) fn vtable_global_name(trait_name: &str, type_prefix: &str) -> String {
    format!("__vtable{SEP}{trait_name}{SEP}{type_prefix}")
}

/// Name of the generated by-pointer shim for one vtable slot.
pub(crate) fn vtable_shim_name(
    trait_name: &str,
    type_prefix: &str,
    slot: usize,
    method: &str,
) -> String {
    format!("__dynshim{SEP}{trait_name}{SEP}{type_prefix}{SEP}{slot}{SEP}{method}")
}

/// One vtable slot of a trait: the method name and its MIR return type. The
/// slot index (position in the per-trait vector) is the vtable index used by
/// both the dispatch site and shim/vtable synthesis.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct DynMethodSlot {
    pub(crate) name: String,
    pub(crate) ret: MIRType,
}

/// If a parameter HIR type is `&dyn Trait` (or `dyn Trait`), return the trait name.
pub(crate) fn dyn_trait_of_hir_param(ty: &HIRType) -> Option<String> {
    fn from_kind(kind: &HIRTypeKind) -> Option<String> {
        match kind {
            HIRTypeKind::TraitObject(traits) if !traits.is_empty() => Some(traits[0].clone()),
            _ => None,
        }
    }
    match &ty.kind {
        HIRTypeKind::Ref(_, inner) => from_kind(&inner.kind),
        other => from_kind(other),
    }
}

/// Prefix used to recognize generated vtable shim functions in codegen.
pub const VTABLE_SHIM_PREFIX: &str = "__dynshim";

/// Parsed components of a vtable shim function name.
pub(crate) struct ParsedShimName {
    pub trait_name: String,
    pub type_prefix: String,
    pub slot: usize,
}

/// Parse a shim function name produced by [`vtable_shim_name`].
pub(crate) fn parse_shim_name(name: &str) -> Option<ParsedShimName> {
    let mut parts = name.split(SEP);
    if parts.next()? != VTABLE_SHIM_PREFIX {
        return None;
    }
    let trait_name = parts.next()?.to_string();
    let type_prefix = parts.next()?.to_string();
    let slot = parts.next()?.parse::<usize>().ok()?;
    // Remaining field is the method name; presence confirms a well-formed shim.
    parts.next()?;
    Some(ParsedShimName {
        trait_name,
        type_prefix,
        slot,
    })
}
