use super::FunctionSignatureInfo;

#[allow(dead_code)]
fn escape_html(raw: &str) -> String {
    raw.chars()
        .map(|ch| match ch {
            '&' => "&amp;".to_string(),
            '<' => "&lt;".to_string(),
            '>' => "&gt;".to_string(),
            '"' => "&quot;".to_string(),
            '\'' => "&#39;".to_string(),
            _ => ch.to_string(),
        })
        .collect::<String>()
}

#[allow(dead_code)]
pub(super) fn sanitize_doc_name(raw: &str) -> String {
    let mut out = String::new();
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push_str("module");
    }
    out
}

#[allow(dead_code)]
pub(super) fn render_doc_index(module_id: &str, module_page_name: &str, fn_count: usize) -> String {
    let module_id = escape_html(module_id);
    let module_page_name = escape_html(module_page_name);
    format!(
        "<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>Sengoo API Docs</title>
  <style>
    body {{ margin: 0; font-family: \"Segoe UI\", sans-serif; background: #f4f7fb; color: #162335; }}
    main {{ max-width: 980px; margin: 0 auto; padding: 24px; }}
    h1 {{ margin: 0 0 12px; font-size: 28px; }}
    p {{ line-height: 1.6; color: #354960; }}
    .panel {{ background: #fff; border: 1px solid #d9e1ec; border-radius: 12px; padding: 16px; }}
    a {{ color: #0f4c81; text-decoration: none; font-weight: 600; }}
    a:hover {{ text-decoration: underline; }}
    code {{ background: #edf3fb; padding: 2px 6px; border-radius: 6px; }}
  </style>
</head>
<body>
  <main>
    <h1>Sengoo API Docs</h1>
    <p>Generated by <code>sgc doc</code>. Layout is rustdoc-like: index page + module page.</p>
    <div class=\"panel\">
      <p><strong>Module:</strong> <code>{}</code></p>
      <p><strong>Functions indexed:</strong> {}</p>
      <p><a href=\"{}\">Open module page</a></p>
      <p><a href=\"search-index.json\">Open search-index.json</a></p>
    </div>
  </main>
</body>
</html>
",
        module_id, fn_count, module_page_name
    )
}

#[allow(dead_code)]
pub(super) fn render_doc_module(module_id: &str, signatures: &[FunctionSignatureInfo]) -> String {
    let mut items = String::new();
    if signatures.is_empty() {
        items.push_str(
            "<p>No function signatures discovered. Check source syntax or include function declarations.</p>",
        );
    } else {
        for sig in signatures {
            items.push_str("<article class=\"item\">");
            items.push_str(&format!(
                "<h3>{}</h3><pre>{}</pre>",
                escape_html(&sig.symbol),
                escape_html(&sig.signature)
            ));
            items.push_str("</article>");
        }
    }
    format!(
        "<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>Module API - {}</title>
  <style>
    body {{ margin: 0; font-family: \"Segoe UI\", sans-serif; background: #f4f7fb; color: #162335; }}
    main {{ max-width: 980px; margin: 0 auto; padding: 24px; }}
    h1 {{ margin: 0 0 10px; font-size: 28px; }}
    p {{ line-height: 1.6; color: #354960; }}
    .item {{ background: #fff; border: 1px solid #d9e1ec; border-radius: 12px; padding: 14px; margin-bottom: 12px; }}
    .item h3 {{ margin: 0 0 8px; font-size: 18px; color: #113e68; }}
    pre {{ margin: 0; background: #edf3fb; border-radius: 8px; padding: 10px; overflow-x: auto; }}
    a {{ color: #0f4c81; text-decoration: none; font-weight: 600; }}
    a:hover {{ text-decoration: underline; }}
    code {{ background: #edf3fb; padding: 2px 6px; border-radius: 6px; }}
  </style>
</head>
<body>
  <main>
    <h1>Module API</h1>
    <p><strong>Module:</strong> <code>{}</code></p>
    <p><a href=\"index.html\">Back to index</a></p>
    {}
  </main>
</body>
</html>
",
        escape_html(module_id),
        escape_html(module_id),
        items
    )
}
