//! LLVM JIT 浠ｇ爜鐢熸垚鍣?
//!
//! 使用 inkwell 生成真实的 LLVM IR 并可以 JIT 执行

use super::common;
use crate::mir::dyn_dispatch::{
    parse_drop_method_metadata, parse_shim_name, vtable_global_name, VTABLE_ALIGN_SLOT,
    VTABLE_METHOD_BASE, VTABLE_SIZE_SLOT,
};
use crate::mir::{MIRType, MirFunction};
use std::collections::HashMap;

#[derive(Debug, Clone)]
struct PhiIncomingLoad {
    name: String,
    local: crate::mir::Local,
    ty: MIRType,
}

mod aggregate_instructions;
mod casts;
mod declaration_helpers;
mod functions;
mod instructions;
mod memory_instructions;
mod ops;
mod terminators;
mod utils;

/// LLVM JIT 浠ｇ爜鐢熸垚鍣?
pub struct JITCodegen {
    /// 鐢熸垚鐨?LLVM IR
    ir: String,
    /// 褰撳墠缂╄繘
    indent: usize,
    /// 函数声明（外部函数）
    extern_decls: String,
    /// 字符串常量
    strings: Vec<String>,
    /// 字符串计数器
    string_counter: usize,
    /// 褰撳墠鍩烘湰鍧?ID
    current_block_id: usize,
    /// 临时变量计数器（用于生成唯一名称）
    /// 所有函数的签名（用于类型转换）
    function_signatures: HashMap<String, (Vec<MIRType>, MIRType)>,
    global_types: HashMap<String, String>,
    phi_incoming_loads_by_block: HashMap<usize, Vec<PhiIncomingLoad>>,
    phi_incoming_values: HashMap<(usize, usize, usize), String>,
}

impl JITCodegen {
    /// 鍒涘缓鏂扮殑浠ｇ爜鐢熸垚鍣?
    pub fn new() -> Self {
        let mut cg = Self {
            ir: String::new(),
            indent: 0,
            extern_decls: String::new(),
            strings: Vec::new(),
            string_counter: 0,
            current_block_id: 0,
            function_signatures: HashMap::new(),
            global_types: HashMap::new(),
            phi_incoming_loads_by_block: HashMap::new(),
            phi_incoming_values: HashMap::new(),
        };
        cg.emit_header();
        cg
    }

    /// 鍙戝皠鏂囦欢澶?
    fn emit_header(&mut self) {
        self.ir.push_str("; Sengoo LLVM IR\n");
        self.ir.push_str("; Generated by Sengoo Compiler\n\n");

        // 声明外部运行时函数
        self.declare_runtime_functions();
    }

    /// 鐢熸垚瀹屾暣鐨?LLVM IR 妯″潡
    pub fn generate(&mut self, mir_fns: &[MirFunction]) -> Result<String, String> {
        // 收集所有函数的签名（用于类型转换）
        for mir_fn in mir_fns {
            self.function_signatures.insert(
                mir_fn.name.clone(),
                (mir_fn.params.clone(), mir_fn.return_type.clone()),
            );
        }

        // 生成字符串常量
        self.emit_string_constants();

        // 声明运行时函数
        self.ir.push_str(&self.extern_decls);
        self.ir.push('\n');

        self.emit_dyn_vtables(mir_fns);

        // 鐢熸垚鎵€鏈夊嚱鏁?
        for mir_fn in mir_fns {
            self.codegen_function(mir_fn)?;
        }

        // 添加 main 函数入口（如果不存在）
        if !mir_fns.iter().any(|f| f.name == "main") {
            self.emit_main_wrapper();
        }

        Ok(self.ir.clone())
    }

    /// 生成字符串常量
    fn emit_string_constants(&mut self) {
        if !self.strings.is_empty() {
            self.ir.push_str("; String Constants\n");
            for (i, s) in self.strings.iter().enumerate() {
                // 转义字符串
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
                self.ir.push_str(&format!(
                    "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\"\n",
                    i,
                    s.len() + 1,
                    escaped
                ));
            }
            self.ir.push('\n');
        }
    }

    /// 添加字符串常量，返回其引用名
    pub fn add_string(&mut self, s: &str) -> String {
        let idx = self.string_counter;
        self.string_counter += 1;
        self.strings.push(s.to_string());
        format!("@.str.{}", idx)
    }

    /// 鑾峰彇鐢熸垚鐨?LLVM IR
    pub fn to_string(&self) -> &str {
        &self.ir
    }

    fn emit_dyn_vtables(&mut self, mir_fns: &[MirFunction]) {
        let mut tables: HashMap<(String, String), HashMap<usize, (String, String)>> =
            HashMap::new();
        let mut layouts: HashMap<(String, String), (u64, u64)> = HashMap::new();

        for mir_fn in mir_fns {
            let Some(parsed) = parse_shim_name(&mir_fn.name) else {
                continue;
            };
            let ret = self.mir_type_to_llvm_str(&mir_fn.return_type);
            let params: Vec<String> = mir_fn
                .params
                .iter()
                .map(|ty| self.mir_type_to_llvm_str(ty))
                .collect();
            let fn_ptr_ty = format!("{} ({})*", ret, params.join(", "));
            if let Some((size, align)) = parse_drop_method_metadata(&parsed.method) {
                layouts.insert(
                    (parsed.trait_name.clone(), parsed.type_prefix.clone()),
                    (size, align),
                );
            }
            tables
                .entry((parsed.trait_name, parsed.type_prefix))
                .or_default()
                .insert(parsed.slot, (mir_fn.name.clone(), fn_ptr_ty));
        }

        if tables.is_empty() {
            return;
        }

        let mut keys: Vec<(String, String)> = tables.keys().cloned().collect();
        keys.sort();

        self.ir.push_str("; dyn Trait vtables\n");
        for (trait_name, type_prefix) in keys {
            let slots = &tables[&(trait_name.clone(), type_prefix.clone())];
            let slot_count = slots
                .keys()
                .copied()
                .max()
                .map(|slot| slot + 1)
                .unwrap_or(0)
                .max(VTABLE_METHOD_BASE);
            let (size, align) = layouts
                .get(&(trait_name.clone(), type_prefix.clone()))
                .copied()
                .unwrap_or((0, 1));
            let mut elements = Vec::with_capacity(slot_count);

            for slot in 0..slot_count {
                if slot == VTABLE_SIZE_SLOT {
                    elements.push(format!("i64 {size}"));
                } else if slot == VTABLE_ALIGN_SLOT {
                    elements.push(format!("i64 {align}"));
                } else {
                    match slots.get(&slot) {
                        Some((shim_name, fn_ptr_ty)) => elements.push(format!(
                            "i64 ptrtoint ({} @{} to i64)",
                            fn_ptr_ty, shim_name
                        )),
                        None => elements.push("i64 0".to_string()),
                    }
                }
            }

            let global_name = vtable_global_name(&trait_name, &type_prefix);
            let array_ty = format!("[{} x i64]", slot_count);
            self.ir.push_str(&format!(
                "@{} = internal constant {} [{}]\n",
                global_name,
                array_ty,
                elements.join(", ")
            ));
            self.global_types.insert(global_name, array_ty);
        }
        self.ir.push('\n');
    }
}

impl Default for JITCodegen {
    fn default() -> Self {
        Self::new()
    }
}
