//! LLVM JIT 浠ｇ爜鐢熸垚鍣?
//!
//! 使用 inkwell 生成真实的 LLVM IR 并可以 JIT 执行

use super::common;
use crate::mir::{self, MIRType, MirConstant, MirFunction, MirUnOp};
use std::collections::HashMap;

mod casts;
mod declaration_helpers;
mod ops;
mod utils;

/// LLVM JIT 浠ｇ爜鐢熸垚鍣?
pub struct JITCodegen {
    /// 鐢熸垚鐨?LLVM IR
    ir: String,
    /// 褰撳墠缂╄繘
    indent: usize,
    /// 函数声明（外部函数）
    extern_decls: String,
    /// 字符串常量
    strings: Vec<String>,
    /// 字符串计数器
    string_counter: usize,
    /// 褰撳墠鍩烘湰鍧?ID
    current_block_id: usize,
    /// 临时变量计数器（用于生成唯一名称）
    /// 所有函数的签名（用于类型转换）
    function_signatures: HashMap<String, (Vec<MIRType>, MIRType)>,
}

impl JITCodegen {
    /// 鍒涘缓鏂扮殑浠ｇ爜鐢熸垚鍣?
    pub fn new() -> Self {
        let mut cg = Self {
            ir: String::new(),
            indent: 0,
            extern_decls: String::new(),
            strings: Vec::new(),
            string_counter: 0,
            current_block_id: 0,
            function_signatures: HashMap::new(),
        };
        cg.emit_header();
        cg
    }

    /// 鍙戝皠鏂囦欢澶?
    fn emit_header(&mut self) {
        self.ir.push_str("; Sengoo LLVM IR\n");
        self.ir.push_str("; Generated by Sengoo Compiler\n\n");

        // 声明外部运行时函数
        self.declare_runtime_functions();
    }

    /// 鐢熸垚瀹屾暣鐨?LLVM IR 妯″潡
    pub fn generate(&mut self, mir_fns: &[MirFunction]) -> Result<String, String> {
        // 收集所有函数的签名（用于类型转换）
        for mir_fn in mir_fns {
            self.function_signatures.insert(
                mir_fn.name.clone(),
                (mir_fn.params.clone(), mir_fn.return_type.clone()),
            );
        }

        // 生成字符串常量
        self.emit_string_constants();

        // 声明运行时函数
        self.ir.push_str(&self.extern_decls);
        self.ir.push('\n');

        // 鐢熸垚鎵€鏈夊嚱鏁?
        for mir_fn in mir_fns {
            self.codegen_function(mir_fn)?;
        }

        // 添加 main 函数入口（如果不存在）
        if !mir_fns.iter().any(|f| f.name == "main") {
            self.emit_main_wrapper();
        }

        Ok(self.ir.clone())
    }

    /// 生成字符串常量
    fn emit_string_constants(&mut self) {
        if !self.strings.is_empty() {
            self.ir.push_str("; String Constants\n");
            for (i, s) in self.strings.iter().enumerate() {
                // 转义字符串
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
                self.ir.push_str(&format!(
                    "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\"\n",
                    i,
                    s.len() + 1,
                    escaped
                ));
            }
            self.ir.push('\n');
        }
    }

    /// 添加字符串常量，返回其引用名
    pub fn add_string(&mut self, s: &str) -> String {
        let idx = self.string_counter;
        self.string_counter += 1;
        self.strings.push(s.to_string());
        format!("@.str.{}", idx)
    }

    /// 鐢熸垚鍑芥暟瀹氫箟
    fn codegen_function(&mut self, mir_fn: &MirFunction) -> Result<(), String> {
        self.ir.push_str(&format!("; Function: {}\n", mir_fn.name));

        // main 鍑芥暟杩斿洖 i32锛屽叾浠栧嚱鏁颁娇鐢ㄥ疄闄呰繑鍥炵被鍨?
        let return_type = if mir_fn.name == "main" {
            "i32".to_string()
        } else {
            self.mir_type_to_llvm_str(&mir_fn.return_type)
        };

        // 鍑芥暟澶?
        self.ir
            .push_str(&format!("define {} @{}(", return_type, mir_fn.name));

        // 鍙傛暟鍒楄〃
        for (i, ty) in mir_fn.params.iter().enumerate() {
            if i > 0 {
                self.ir.push_str(", ");
            }
            self.ir
                .push_str(&format!("{} %l_{}", self.mir_type_to_llvm_str(ty), i + 1));
        }

        self.ir.push_str(") {\n");
        self.indent += 1;

        // 生成基本块（allocas 将在第一个基本块内生成）
        for (i, bb) in mir_fn.basic_blocks.iter().enumerate() {
            self.codegen_basic_block(mir_fn, bb, i == 0)?;
        }

        self.indent -= 1;
        self.ir.push_str("}\n\n");

        Ok(())
    }

    /// 鐢熸垚鍩烘湰鍧?
    fn codegen_basic_block(
        &mut self,
        mir_fn: &MirFunction,
        bb: &mir::BasicBlock,
        is_first: bool,
    ) -> Result<(), String> {
        // 鏇存柊褰撳墠鍩烘湰鍧?ID
        self.current_block_id = bb.id;

        // LLVM IR 鍩烘湰鍧楁爣绛句笉闇€瑕?% 鍓嶇紑锛屼絾寮曠敤鏃堕渶瑕?
        self.ir.push_str(&format!("bb_{}:\n", bb.id));
        self.indent += 1;

        // 如果是第一个基本块，在这里分配局部变量并存储参数
        if is_first {
            // 棣栧厛鍒嗛厤鎵€鏈夊眬閮ㄥ彉閲忥紙鍖呮嫭 Temp銆丳aram 鍜?Return 妲戒綅锛?
            for (local, ty) in &mir_fn.locals {
                self.emit_indent();
                self.ir.push_str(&format!(
                    "%local_{} = alloca {}\n",
                    local.id,
                    self.mir_type_to_llvm_str(ty)
                ));
            }

            // 存储参数到对应的 alloca
            for (i, ty) in mir_fn.params.iter().enumerate() {
                self.emit_indent();
                self.ir.push_str(&format!(
                    "store {} %l_{}, {}* %local_{}\n",
                    self.mir_type_to_llvm_str(ty),
                    i + 1,
                    self.mir_type_to_llvm_str(ty),
                    i + 1 // 鍙傛暟鐨?local id 浠?1 寮€濮?
                ));
            }
        }

        // 鐢熸垚鎸囦护
        for inst_id in &bb.instructions {
            let inst = mir_fn.instruction(*inst_id);
            self.codegen_instruction(inst, mir_fn)?;
        }

        // 生成终止符
        if let Some(terminator) = &bb.terminator {
            self.codegen_terminator(terminator, mir_fn)?;
        }

        self.indent -= 1;
        Ok(())
    }

    /// 鐢熸垚鎸囦护
    fn codegen_instruction(
        &mut self,
        inst: &mir::Instruction,
        mir_fn: &MirFunction,
    ) -> Result<(), String> {
        match inst {
            mir::Instruction::Assign { destination, value } => {
                self.emit_indent();
                let dest = self.local_name(*destination);
                let ty = self.get_local_type(mir_fn, *destination);
                let llvm_ty = self.mir_type_to_llvm_str(&ty);

                match value {
                    MirConstant::String(s) => {
                        // 创建字符串常量
                        let str_ref = self.add_string(s);
                        let string_ty = format!("[{} x i8]", s.len() + 1);
                        self.ir.push_str(&format!(
                            "{} = bitcast {} {} to i8*\n",
                            dest, string_ty, str_ref
                        ));
                    }
                    _ => {
                        // 甯搁噺璧嬪€?
                        self.ir.push_str(&format!(
                            "store {} {}, {}* %local_{}\n",
                            llvm_ty,
                            self.mir_constant_to_llvm_str(value),
                            llvm_ty,
                            destination.id
                        ));
                    }
                }
            }
            mir::Instruction::AddrOf {
                destination,
                source,
            } => {
                self.emit_indent();
                let dest = self.local_name(*destination);
                let src = self.local_reg(*source);
                let src_ty = self.get_local_type(mir_fn, *source);
                let llvm_ty = self.mir_type_to_llvm_str(&src_ty);

                // AddrOf 鑾峰彇鍙橀噺鐨勫湴鍧€
                // 1. 浣跨敤 getelementptr 鑾峰彇鍦板潃
                let temp = format!("{}.addr", dest);
                self.ir.push_str(&format!(
                    "{} = getelementptr {}, {}* {}, i64 0\n",
                    temp, llvm_ty, llvm_ty, src
                ));

                // 2. 灏嗗湴鍧€瀛樺偍鍒?destination
                self.emit_indent();
                let dest_ty = self.get_local_type(mir_fn, *destination);
                let dest_llvm_ty = self.mir_type_to_llvm_str(&dest_ty);
                // store 鎸囦护鏍煎紡: store <type> <value>, <type>* <pointer>
                // alloca 杩斿洖鐨勭被鍨嬫槸 <type>*锛屾墍浠ヨ繖閲岄渶瑕?<type>**
                let dest_ptr_ty = format!("{}*", dest_llvm_ty);
                self.ir.push_str(&format!(
                    "store {} {}, {} {}\n",
                    dest_llvm_ty, temp, dest_ptr_ty, dest
                ));
            }
            mir::Instruction::Load {
                destination,
                source,
            } => {
                // Load 鎸囦护锛氫粠 source 鍔犺浇鍊煎埌 destination
                let dest = self.local_name(*destination);
                let dest_ty = self.get_local_type(mir_fn, *destination);
                let src = self.local_reg(*source);
                let src_ty = self.get_local_type(mir_fn, *source);

                // 鍔犺浇鐨勫€肩被鍨嬪簲璇ヤ娇鐢?destination 鐨勭被鍨?
                let llvm_value_ty = self.mir_type_to_llvm_str(&dest_ty);

                // 瀵逛簬 Ptr 绫诲瀷鐨?source锛岄渶瑕佸弻閲嶅姞杞?
                match &src_ty {
                    MIRType::Ptr(inner) => {
                        // source 是 Ptr(T)，在 LLVM 中会：
                        // - alloca 杩斿洖 T**
                        // - 第一次加载得到 T*
                        // - 第二次加载得到 T
                        let inner_ty = self.mir_type_to_llvm_str(inner);
                        let ptr_ty = format!("{}*", inner_ty);
                        let ptr_ptr_ty = format!("{}*", ptr_ty);

                        // 第一次加载：从 alloca 加载指针值
                        self.emit_indent();
                        let temp_ptr = format!("{}.ptr", dest);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            temp_ptr, ptr_ty, ptr_ptr_ty, src
                        ));

                        // 第二次加载：从指针加载实际值
                        self.emit_indent();
                        let temp_val = format!("{}.val", dest);
                        self.ir.push_str(&format!(
                            "{} = load {}, {}* {}\n",
                            temp_val, llvm_value_ty, inner_ty, temp_ptr
                        ));

                        // 灏嗗€煎瓨鍌ㄥ埌 destination锛坅lloca锛?
                        self.emit_indent();
                        let dest_ptr_ty = format!("{}*", llvm_value_ty);
                        self.ir.push_str(&format!(
                            "store {} {}, {} {}\n",
                            llvm_value_ty, temp_val, dest_ptr_ty, dest
                        ));
                    }
                    MIRType::Ref(inner) => {
                        // Ref 类型的处理类似 Ptr
                        let inner_ty = self.mir_type_to_llvm_str(inner);
                        let ptr_ty = format!("{}*", inner_ty);
                        let ptr_ptr_ty = format!("{}*", ptr_ty);

                        self.emit_indent();
                        let temp_ptr = format!("{}.ptr", dest);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            temp_ptr, ptr_ty, ptr_ptr_ty, src
                        ));

                        self.emit_indent();
                        let temp_val = format!("{}.val", dest);
                        self.ir.push_str(&format!(
                            "{} = load {}, {}* {}\n",
                            temp_val, llvm_value_ty, inner_ty, temp_ptr
                        ));

                        self.emit_indent();
                        let dest_ptr_ty = format!("{}*", llvm_value_ty);
                        self.ir.push_str(&format!(
                            "store {} {}, {} {}\n",
                            llvm_value_ty, temp_val, dest_ptr_ty, dest
                        ));
                    }
                    _ => {
                        // 普通类型，需要额外的指针层级（alloca 返回指针）
                        let llvm_ptr_ty = self.mir_type_to_llvm_str(&src_ty);
                        let llvm_src_ptr_ty = format!("{}*", llvm_ptr_ty);

                        // 鍔犺浇鍊煎埌涓存椂鍙橀噺
                        self.emit_indent();
                        let temp_val = format!("{}.val", dest);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            temp_val, llvm_value_ty, llvm_src_ptr_ty, src
                        ));

                        // 灏嗗€煎瓨鍌ㄥ埌 destination锛坅lloca锛?
                        self.emit_indent();
                        let dest_ptr_ty = format!("{}*", llvm_value_ty);
                        self.ir.push_str(&format!(
                            "store {} {}, {} {}\n",
                            llvm_value_ty, temp_val, dest_ptr_ty, dest
                        ));
                    }
                }
            }
            mir::Instruction::Unary {
                destination,
                op,
                operand,
            } => {
                self.emit_indent();
                let _operand_name = self.local_name(*operand);
                let dest = self.local_name(*destination);
                let ty = self.get_local_type(mir_fn, *destination);
                let llvm_ty = self.mir_type_to_llvm_str(&ty);

                // 鍔犺浇鎿嶄綔鏁?
                let temp = format!("{}.temp", dest);
                self.ir.push_str(&format!(
                    "{} = load {}, {}* {}\n",
                    temp,
                    llvm_ty,
                    llvm_ty,
                    self.local_reg(*operand)
                ));

                // 执行一元操作
                let op_inst = match op {
                    MirUnOp::Neg => {
                        if matches!(ty, MIRType::Float(_)) {
                            format!("{}.neg = fneg float {}", dest, temp)
                        } else {
                            format!("{}.neg = sub {} 0, {}", dest, llvm_ty, temp)
                        }
                    }
                    MirUnOp::Not => {
                        format!(
                            "{}.not = xor {} {}, {}",
                            dest,
                            llvm_ty,
                            temp,
                            self.mir_constant_to_llvm_str(&MirConstant::Bool(true))
                        )
                    }
                    MirUnOp::BitNot => {
                        format!(
                            "{}.bitnot = xor {} {}, {}",
                            dest,
                            llvm_ty,
                            temp,
                            self.mir_constant_to_llvm_str(&MirConstant::Int(-1))
                        )
                    }
                };
                self.ir.push_str(&format!("{}\n", op_inst));

                // 瀛樺偍缁撴灉
                self.emit_indent();
                let result_reg = format!("{dest}.res");
                self.ir.push_str(&format!(
                    "store {} {}, {}* {}\n",
                    llvm_ty,
                    result_reg,
                    llvm_ty,
                    self.local_reg(*destination)
                ));
            }
            mir::Instruction::Cast {
                destination,
                value,
                to,
            } => {
                let dest = self.local_name(*destination);
                let src_ty = self.get_local_type(mir_fn, *value);
                let src_llvm = self.mir_type_to_llvm_str(&src_ty);
                let dst_llvm = self.mir_type_to_llvm_str(to);
                let src_reg = self.local_reg(*value);

                self.emit_indent();
                let src_temp = format!("{}.cast.in", dest);
                self.ir.push_str(&format!(
                    "{} = load {}, {}* {}\n",
                    src_temp, src_llvm, src_llvm, src_reg
                ));

                if src_ty == *to {
                    self.emit_indent();
                    self.ir.push_str(&format!(
                        "store {} {}, {}* {}\n",
                        dst_llvm, src_temp, dst_llvm, dest
                    ));
                } else {
                    self.emit_indent();
                    let casted = format!("{}.cast.out", dest);
                    self.emit_cast_value(&casted, &src_temp, &src_ty, to);
                    self.emit_indent();
                    self.ir.push_str(&format!(
                        "store {} {}, {}* {}\n",
                        dst_llvm, casted, dst_llvm, dest
                    ));
                }
            }
            mir::Instruction::Bitcast {
                destination,
                value,
                to,
            } => {
                let dest = self.local_name(*destination);
                let src_ty = self.get_local_type(mir_fn, *value);
                let src_llvm = self.mir_type_to_llvm_str(&src_ty);
                let dst_llvm = self.mir_type_to_llvm_str(to);
                let src_reg = self.local_reg(*value);

                if !common::supports_mir_bitcast(&src_ty, to) {
                    return Err(format!(
                        "invalid MIR bitcast from {} to {}",
                        src_llvm, dst_llvm
                    ));
                }

                self.emit_indent();
                let src_temp = format!("{}.bitcast.in", dest);
                self.ir.push_str(&format!(
                    "{} = load {}, {}* {}\n",
                    src_temp, src_llvm, src_llvm, src_reg
                ));

                self.emit_indent();
                let casted = format!("{}.bitcast.out", dest);
                self.ir.push_str(&format!(
                    "{} = bitcast {} {} to {}\n",
                    casted, src_llvm, src_temp, dst_llvm
                ));

                self.emit_indent();
                self.ir.push_str(&format!(
                    "store {} {}, {}* {}\n",
                    dst_llvm, casted, dst_llvm, dest
                ));
            }
            mir::Instruction::Binary {
                destination,
                op,
                left,
                right,
            } => {
                self.emit_indent();
                let left_reg = self.local_reg(*left);
                let right_reg = self.local_reg(*right);
                let dest = self.local_name(*destination);
                let ty = self.get_local_type(mir_fn, *left);
                let llvm_ty = self.mir_type_to_llvm_str(&ty);

                // 鍔犺浇鎿嶄綔鏁?
                let left_temp = format!("{}.l", dest);
                let right_temp = format!("{}.r", dest);
                self.ir.push_str(&format!(
                    "{} = load {}, {}* {}\n",
                    left_temp, llvm_ty, llvm_ty, left_reg
                ));
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = load {}, {}* {}\n",
                    right_temp, llvm_ty, llvm_ty, right_reg
                ));

                // 执行二元操作
                let op_inst = self.binary_op_to_llvm(*op, &ty, &left_temp, &right_temp);
                self.ir.push_str(&format!("{}\n", op_inst));

                // 瀛樺偍缁撴灉 - 姣旇緝鎿嶄綔杩斿洖 i1锛屽叾浠栨搷浣滆繑鍥炴搷浣滄暟绫诲瀷
                self.emit_indent();
                let dest_ty = self.get_local_type(mir_fn, *destination);
                let llvm_dest_ty = self.mir_type_to_llvm_str(&dest_ty);
                self.ir.push_str(&format!(
                    "store {} %result, {}* {}\n",
                    llvm_dest_ty,
                    llvm_dest_ty,
                    self.local_reg(*destination)
                ));
            }
            mir::Instruction::Store { destination, value } => {
                // 瀛樺偍 local 鍒?local (let 璧嬪€?
                let dest_ty = self.get_local_type(mir_fn, *destination);
                let src_ty = self.get_local_type(mir_fn, *value);
                let llvm_dest_ty = self.mir_type_to_llvm_str(&dest_ty);
                let llvm_src_ty = self.mir_type_to_llvm_str(&src_ty);
                let src_reg = self.local_reg(*value);
                let dest_reg = self.local_reg(*destination);

                match &dest_ty {
                    MIRType::Ptr(inner) => {
                        // destination 是 Ptr(T)，表示我们想存储到指针指向的位置
                        let inner_ty = self.mir_type_to_llvm_str(inner);

                        // 1. 浠?destination alloca 鍔犺浇鎸囬拡鍊?
                        self.emit_indent();
                        let ptr_temp = format!("{}.destptr", dest_reg);
                        let ptr_ptr_ty = format!("{inner_ty}**");
                        let ptr_ty = format!("{}*", inner_ty);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            ptr_temp, ptr_ty, ptr_ptr_ty, dest_reg
                        ));

                        // 2. 鍔犺浇婧愬€?
                        self.emit_indent();
                        let val_temp = format!("{}.srcval", dest_reg);
                        let src_ptr_ty = format!("{}*", llvm_src_ty);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            val_temp, llvm_src_ty, src_ptr_ty, src_reg
                        ));

                        // 3. 瀛樺偍鍒版寚閽堟寚鍚戠殑浣嶇疆
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "store {} {}, {}* {}\n",
                            llvm_src_ty, val_temp, inner_ty, ptr_temp
                        ));
                    }
                    MIRType::Ref(inner) => {
                        // Ref 类型的处理类似 Ptr
                        let inner_ty = self.mir_type_to_llvm_str(inner);

                        self.emit_indent();
                        let ptr_temp = format!("{}.destptr", dest_reg);
                        let ptr_ptr_ty = format!("{inner_ty}**");
                        let ptr_ty = format!("{}*", inner_ty);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            ptr_temp, ptr_ty, ptr_ptr_ty, dest_reg
                        ));

                        self.emit_indent();
                        let val_temp = format!("{}.srcval", dest_reg);
                        let src_ptr_ty = format!("{}*", llvm_src_ty);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            val_temp, llvm_src_ty, src_ptr_ty, src_reg
                        ));

                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "store {} {}, {}* {}\n",
                            llvm_src_ty, val_temp, inner_ty, ptr_temp
                        ));
                    }
                    MIRType::Tuple(_) => {
                        // 结构体类型：使用逐字段复制
                        if let MIRType::Tuple(field_tys) = &dest_ty {
                            for (i, field_ty) in field_tys.iter().enumerate() {
                                let llvm_field_ty = self.mir_type_to_llvm_str(field_ty);

                                // 鑾峰彇婧愬瓧娈靛湴鍧€
                                self.emit_indent();
                                let src_gep = format!("%.src_gep.{}.{}", destination.id, i);
                                self.ir.push_str(&format!(
                                    "{} = getelementptr {}, {}* {}, i32 0, i32 {}\n",
                                    src_gep, llvm_src_ty, llvm_src_ty, src_reg, i
                                ));

                                // 鍔犺浇婧愬瓧娈?
                                self.emit_indent();
                                let src_field = format!("%.src_field.{}.{}", destination.id, i);
                                self.ir.push_str(&format!(
                                    "{} = load {}, {}* {}\n",
                                    src_field, llvm_field_ty, llvm_field_ty, src_gep
                                ));

                                // 获取目标字段地址
                                self.emit_indent();
                                let dest_gep = format!("%.dest_gep.{}.{}", destination.id, i);
                                self.ir.push_str(&format!(
                                    "{} = getelementptr {}, {}* {}, i32 0, i32 {}\n",
                                    dest_gep, llvm_dest_ty, llvm_dest_ty, dest_reg, i
                                ));

                                // 瀛樺偍鍒扮洰鏍囧瓧娈?
                                self.emit_indent();
                                self.ir.push_str(&format!(
                                    "store {} {}, {}* {}\n",
                                    llvm_field_ty, src_field, llvm_field_ty, dest_gep
                                ));
                            }
                        }
                    }
                    MIRType::Array(elem_ty, len) => {
                        // 鏁扮粍绫诲瀷锛氫娇鐢?memcpy
                        let _llvm_elem_ty = self.mir_type_to_llvm_str(elem_ty);
                        let size = self.get_type_size(elem_ty) * len;

                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "call void @llvm.memcpy.p0i8.p0i8.i64(i8* bitcast {}* {} to i8*), i8* bitcast {}* {} to i8*, i64 {}, i32 8, i1 false)\n",
                            llvm_dest_ty, dest_reg, llvm_src_ty, src_reg, size
                        ));
                    }
                    _ => {
                        // 鏍囬噺绫诲瀷锛氱洿鎺ュ姞杞藉拰瀛樺偍
                        self.emit_indent();
                        let src_temp = format!("%.src.{}", destination.id);
                        // 娉ㄦ剰锛歴rc_reg 鏄?alloca 杩斿洖鐨勬寚閽堬紝闇€瑕佸姞 *
                        let src_ptr_ty = format!("{}*", llvm_src_ty);
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            src_temp, llvm_src_ty, src_ptr_ty, src_reg
                        ));

                        self.emit_indent();
                        // dest_reg 涔熸槸鎸囬拡绫诲瀷锛岄渶瑕佸姞 *
                        let dest_ptr_ty = format!("{}*", llvm_dest_ty);
                        self.ir.push_str(&format!(
                            "store {} {}, {} {}\n",
                            llvm_dest_ty, src_temp, dest_ptr_ty, dest_reg
                        ));
                    }
                }
            }
            mir::Instruction::FieldAddr {
                destination,
                base,
                field,
            } => {
                // 结构体字段地址计算: ptr = &base.field（字段索引是常量）
                let base_ty = self.get_local_type(mir_fn, *base);
                let llvm_base_ty = self.mir_type_to_llvm_str(&base_ty);
                let dest = self.local_name(*destination);
                let base_reg = self.local_reg(*base);

                // 使用 getelementptr 获取字段地址
                self.emit_indent();
                self.ir.push_str(&format!(
                    "{} = getelementptr {}, {}* {}, i32 0, i32 {}\n",
                    dest, llvm_base_ty, llvm_base_ty, base_reg, field
                ));
            }
            mir::Instruction::IndexAddr {
                destination,
                base,
                index,
            } => {
                // 鏁扮粍绱㈠紩鍦板潃璁＄畻: ptr = &base[index]
                let base_ty = self.get_local_type(mir_fn, *base);
                let elem_ty = match &base_ty {
                    MIRType::Array(elem, _) => (*elem).clone(),
                    MIRType::Ptr(inner) | MIRType::Ref(inner) => (*inner).clone(),
                    _ => Box::new(MIRType::Int(64)),
                };

                let llvm_elem_ty = self.mir_type_to_llvm_str(&elem_ty);
                let llvm_base_ty = self.mir_type_to_llvm_str(&base_ty);
                let dest = self.local_name(*destination);
                let base_reg = self.local_reg(*base);
                let index_reg = self.local_reg(*index);

                // 鍔犺浇绱㈠紩鍊?
                self.emit_indent();
                let index_temp = format!("{}.idx", dest);
                self.ir
                    .push_str(&format!("{} = load i64, i64* {}\n", index_temp, index_reg));

                // 澶勭悊鍩哄潃
                match &base_ty {
                    MIRType::Array(_, _) => {
                        // 数组类型：首先将数组退化为指向首元素的指针（C 语言行为）
                        // base_ptr = &base[0]
                        self.emit_indent();
                        let base_ptr = format!("{}.decay", dest);
                        self.ir.push_str(&format!(
                            "{} = getelementptr {}, {}* {}, i64 0, i64 0\n",
                            base_ptr, llvm_base_ty, llvm_elem_ty, base_reg
                        ));

                        // 鐒跺悗璁＄畻鍏冪礌鍦板潃: ptr = &base_ptr[index]
                        self.emit_indent();
                        let addr_temp = format!("{}.addr", dest);
                        self.ir.push_str(&format!(
                            "{} = getelementptr {}, {}* {}, i64 {}\n",
                            addr_temp, llvm_elem_ty, llvm_elem_ty, base_ptr, index_temp
                        ));

                        // 将地址存储到 destination local（destination 是指针类型）
                        // destination 是 Ptr(T)，在 LLVM 中是 T**
                        // addr_temp 鏄?T*锛岄渶瑕佸瓨鍌ㄥ埌 T**
                        self.emit_indent();
                        let dest_ptr_ptr_ty = format!("{llvm_elem_ty}**");
                        let addr_ptr_ty = format!("{}*", llvm_elem_ty); // addr_temp 鐨勭被鍨嬫槸 T*
                        self.ir.push_str(&format!(
                            "store {} {}, {} {}\n",
                            addr_ptr_ty, addr_temp, dest_ptr_ptr_ty, dest
                        ));
                    }
                    MIRType::Ptr(_) | MIRType::Ref(_) => {
                        // 鎸囬拡/寮曠敤绫诲瀷锛氱洿鎺ュ姞杞芥寚閽堬紝鐒跺悗璁＄畻鍏冪礌鍦板潃
                        self.emit_indent();
                        let loaded_ptr = format!("{}.ptr", dest);
                        self.ir.push_str(&format!(
                            "{} = load {}, {}* {}\n",
                            loaded_ptr, llvm_base_ty, llvm_elem_ty, base_reg
                        ));

                        // 璁＄畻鍏冪礌鍦板潃
                        self.emit_indent();
                        let addr_temp = format!("{}.addr", dest);
                        self.ir.push_str(&format!(
                            "{} = getelementptr {}, {}* {}, i64 {}\n",
                            addr_temp, llvm_elem_ty, llvm_elem_ty, loaded_ptr, index_temp
                        ));

                        // 将地址存储到 destination local（destination 是指针类型）
                        // destination 是 Ptr(T)，在 LLVM 中是 T**
                        // addr_temp 鏄?T*锛岄渶瑕佸瓨鍌ㄥ埌 T**
                        self.emit_indent();
                        let dest_ptr_ptr_ty = format!("{llvm_elem_ty}**");
                        let addr_ptr_ty = format!("{}*", llvm_elem_ty); // addr_temp 鐨勭被鍨嬫槸 T*
                        self.ir.push_str(&format!(
                            "store {} {}, {} {}\n",
                            addr_ptr_ty, addr_temp, dest_ptr_ptr_ty, dest
                        ));
                    }
                    MIRType::Tuple(field_tys) => {
                        // 元组/结构体类型：使用 getelementptr 访问字段
                        // 字段索引是常量，不需要动态索引
                        let struct_fields: Vec<String> = field_tys
                            .iter()
                            .map(|ty| self.mir_type_to_llvm_str(ty))
                            .collect();
                        let llvm_struct_ty = format!("{{{}}}", struct_fields.join(", "));

                        // 直接使用 getelementptr 获取字段地址
                        // 娉ㄦ剰锛氱储寮曞€煎簲璇ユ槸缂栬瘧鏃跺父閲?
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = getelementptr {}, {}* {}, i32 0, i32 {}\n",
                            dest, llvm_struct_ty, llvm_elem_ty, base_reg, index_temp
                        ));
                    }
                    _ => {
                        // 其他类型：错误处理
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "; IndexAddr: unsupported base type {:?}\n",
                            base_ty
                        ));
                    }
                }
            }
            mir::Instruction::Call {
                destination,
                func,
                args,
            } => {
                self.emit_indent();

                // 鐗规畩澶勭悊鍐呯疆鍑芥暟
                if func == "print" || func == "println" {
                    // print 鍑芥暟
                    let arg = args.first();
                    if let Some(arg_local) = arg {
                        let arg_ty = self.get_local_type(mir_fn, *arg_local);
                        let arg_val = self.local_reg(*arg_local);

                        match &arg_ty {
                            MIRType::Int(_) => {
                                self.ir.push_str(&format!(
                                    "call void @puts(i8* bitcast i64* inttoptr i64 {} to i8*)\n",
                                    arg_val
                                ));
                            }
                            MIRType::Ptr(inner) | MIRType::Ref(inner) => {
                                if matches!(inner.as_ref(), MIRType::Int(8)) {
                                    // 字符串指针
                                    self.ir
                                        .push_str(&format!("call void @puts(i8* {})\n", arg_val));
                                }
                            }
                            _ => {}
                        }
                    }
                } else {
                    // 普通函数调用
                    // 获取目标函数的签名（如果存在）
                    let target_param_tys = self
                        .function_signatures
                        .get(func)
                        .map(|(params, _)| params.clone())
                        .unwrap_or_default();

                    let mut args_codegen = Vec::new();

                    for (i, local) in args.iter().enumerate() {
                        let ty = self.get_local_type(mir_fn, *local);
                        let llvm_ty = self.mir_type_to_llvm_str(&ty);
                        let reg = self.local_reg(*local);

                        // 鍔犺浇鍙傛暟鍊?
                        let arg_temp = format!("%.arg.{}.{}", func, i);
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = load {}, {}* {}\n",
                            arg_temp, llvm_ty, llvm_ty, reg
                        ));

                        // 如果目标函数参数类型与当前类型不同，进行转换
                        let final_arg = if let Some(target_ty) = target_param_tys.get(i) {
                            let llvm_target_ty = self.mir_type_to_llvm_str(target_ty);
                            if llvm_ty != llvm_target_ty {
                                let converted = format!("%.arg.{}.{}.conv", func, i);
                                self.emit_indent();
                                self.emit_cast_value(&converted, &arg_temp, &ty, target_ty);
                                format!("{} {}", llvm_target_ty, converted)
                            } else {
                                format!("{} {}", llvm_ty, arg_temp)
                            }
                        } else {
                            format!("{} {}", llvm_ty, arg_temp)
                        };

                        args_codegen.push(final_arg);
                    }

                    let dest = self.local_name(*destination);
                    // 获取被调用函数的返回类型
                    let return_ty = self
                        .function_signatures
                        .get(func)
                        .map(|(_, ret)| self.mir_type_to_llvm_str(ret))
                        .unwrap_or_else(|| self.mir_type_to_llvm_str(&mir_fn.return_type));

                    self.emit_indent();
                    if return_ty != "void" {
                        // 浣跨敤涓存椂鍚嶇О浣滀负 call 鐨勭粨鏋滐紝鐒跺悗瀛樺偍鍒?destination
                        let call_result = format!("{}.call", dest);
                        self.ir.push_str(&format!(
                            "{} = call {} @{}({})\n",
                            call_result,
                            return_ty,
                            func,
                            args_codegen.join(", ")
                        ));

                        // 灏嗙粨鏋滃瓨鍌ㄥ埌 destination锛坅lloca锛?
                        self.emit_indent();
                        let dest_ptr_ty = format!("{}*", return_ty);
                        self.ir.push_str(&format!(
                            "store {} {}, {} {}\n",
                            return_ty, call_result, dest_ptr_ty, dest
                        ));
                    } else {
                        self.ir.push_str(&format!(
                            "call void @{}({})\n",
                            func,
                            args_codegen.join(", ")
                        ));
                    }
                }
            }
            mir::Instruction::Nop => {}
            mir::Instruction::Aggregate {
                destination,
                fields,
                ty,
            } => {
                // 鑱氬悎鍊煎垵濮嬪寲锛堟暟缁勫瓧闈㈤噺銆佺粨鏋勪綋瀛楅潰閲忥級
                match ty {
                    MIRType::Array(elem_ty, len) => {
                        // 数组初始化
                        let llvm_elem_ty = self.mir_type_to_llvm_str(elem_ty);
                        let llvm_array_ty = format!("[{} x {}]", len, llvm_elem_ty);
                        let dest = self.local_name(*destination);

                        // 首先为每个元素加载值
                        let mut elem_values = Vec::new();
                        for (i, field_local) in fields.iter().enumerate() {
                            let field_ty = self.get_local_type(mir_fn, *field_local);
                            let llvm_field_ty = self.mir_type_to_llvm_str(&field_ty);
                            let reg = self.local_reg(*field_local);
                            let loaded = format!("%.elem.{}.{}", destination.id, i);
                            self.emit_indent();
                            self.ir.push_str(&format!(
                                "{} = load {}, {}* {}\n",
                                loaded, llvm_field_ty, llvm_field_ty, reg
                            ));
                            elem_values.push((loaded, llvm_field_ty));
                        }

                        // 使用 alloca 初始化数组
                        self.emit_indent();
                        self.ir
                            .push_str(&format!("{} = alloca {}\n", dest, llvm_array_ty));

                        // 瀛樺偍姣忎釜鍏冪礌
                        for (i, (value, _)) in elem_values.iter().enumerate() {
                            self.emit_indent();
                            // 鑾峰彇鍏冪礌鎸囬拡
                            let gep = format!("%.ptr.{}.{}", destination.id, i);
                            self.ir.push_str(&format!(
                                "{} = getelementptr {}, {}* {}, i64 0, i64 {}\n",
                                gep, llvm_array_ty, llvm_elem_ty, dest, i
                            ));
                            self.emit_indent();
                            self.ir.push_str(&format!(
                                "store {} {}, {}* {}\n",
                                llvm_elem_ty, value, llvm_elem_ty, gep
                            ));
                        }
                    }
                    MIRType::Tuple(_field_tys) => {
                        // 鍏冪粍/缁撴瀯浣撳垵濮嬪寲
                        let dest = self.local_name(*destination);

                        // 首先为每个字段加载值
                        let mut field_values = Vec::new();
                        for (i, field_local) in fields.iter().enumerate() {
                            let field_ty = self.get_local_type(mir_fn, *field_local);
                            let llvm_field_ty = self.mir_type_to_llvm_str(&field_ty);
                            let reg = self.local_reg(*field_local);
                            let loaded = format!("%.elem.{}.{}", destination.id, i);
                            self.emit_indent();
                            self.ir.push_str(&format!(
                                "{} = load {}, {}* {}\n",
                                loaded, llvm_field_ty, llvm_field_ty, reg
                            ));
                            field_values.push((loaded, llvm_field_ty));
                        }

                        // 涓哄厓缁勫垎閰嶇┖闂达紙浣跨敤 LLVM 缁撴瀯浣擄級
                        let struct_fields: Vec<&str> =
                            field_values.iter().map(|(_, ty)| ty.as_str()).collect();
                        let llvm_struct_ty = format!("{{{}}}", struct_fields.join(", "));
                        self.emit_indent();
                        self.ir
                            .push_str(&format!("{} = alloca {}\n", dest, llvm_struct_ty));

                        // 存储每个字段
                        for (i, (value, llvm_field_ty)) in field_values.iter().enumerate() {
                            self.emit_indent();
                            // 获取字段指针
                            let gep = format!("%.ptr.{}.{}", destination.id, i);
                            self.ir.push_str(&format!(
                                "{} = getelementptr {}, {}* {}, i32 0, i32 {}\n",
                                gep, llvm_struct_ty, llvm_field_ty, dest, i
                            ));
                            self.emit_indent();
                            self.ir.push_str(&format!(
                                "store {} {}, {}* {}\n",
                                llvm_field_ty, value, llvm_field_ty, gep
                            ));
                        }
                    }
                    MIRType::Enum { .. } => {
                        let llvm_enum_ty = self.mir_type_to_llvm_str(ty);
                        let dest = self.local_name(*destination);

                        let discr_reg = fields
                            .first()
                            .map(|local| self.local_reg(*local))
                            .ok_or_else(|| {
                                "enum aggregate missing discriminant field".to_string()
                            })?;
                        let discr_loaded = format!("%.enum.discr.{}", destination.id);
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = load i64, i64* {}\n",
                            discr_loaded, discr_reg
                        ));

                        let payload_loaded = if let Some(payload_local) = fields.get(1) {
                            let payload_reg = self.local_reg(*payload_local);
                            let payload_loaded = format!("%.enum.payload.{}", destination.id);
                            self.emit_indent();
                            self.ir.push_str(&format!(
                                "{} = load i64, i64* {}\n",
                                payload_loaded, payload_reg
                            ));
                            payload_loaded
                        } else {
                            "0".to_string()
                        };

                        self.emit_indent();
                        self.ir
                            .push_str(&format!("{} = alloca {}\n", dest, llvm_enum_ty));

                        let discr_ptr = format!("%.ptr.{}.0", destination.id);
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = getelementptr {}, {}* {}, i32 0, i32 0\n",
                            discr_ptr, llvm_enum_ty, llvm_enum_ty, dest
                        ));
                        self.emit_indent();
                        self.ir
                            .push_str(&format!("store i64 {}, i64* {}\n", discr_loaded, discr_ptr));

                        let payload_ptr = format!("%.ptr.{}.1", destination.id);
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = getelementptr {}, {}* {}, i32 0, i32 1\n",
                            payload_ptr, llvm_enum_ty, llvm_enum_ty, dest
                        ));
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "store i64 {}, i64* {}\n",
                            payload_loaded, payload_ptr
                        ));
                    }
                    _ => {
                        // 鍏朵粬鑱氬悎绫诲瀷锛堢粨鏋勪綋绛夛級
                        let _dest = self.local_name(*destination);
                        self.emit_indent();
                        self.ir.push_str(&format!("; aggregate: {:?}\n", ty));
                    }
                }
            }
            _ => {
                self.emit_indent();
                self.ir
                    .push_str(&format!("; unhandled instruction: {:?}\n", inst));
            }
        }
        Ok(())
    }

    /// 生成终止符
    fn codegen_terminator(
        &mut self,
        terminator: &mir::Terminator,
        mir_fn: &MirFunction,
    ) -> Result<(), String> {
        self.emit_indent();
        match terminator {
            mir::Terminator::Return(value) => {
                if let Some(local) = value {
                    let ret_ty = &mir_fn.return_type;
                    let llvm_ret_ty = self.mir_type_to_llvm_str(ret_ty);
                    let local_ty = self.get_local_type(mir_fn, *local);
                    let llvm_local_ty = self.mir_type_to_llvm_str(&local_ty);

                    // 鎵€鏈?local 閮芥槸閫氳繃 alloca 鍒嗛厤鐨勶紝閮介渶瑕佸姞杞?
                    let reg = self.local_reg(*local);
                    let ret_temp = format!("%.ret.bb{}", self.current_block_id);
                    let local_ptr_ty = format!("{}*", llvm_local_ty);

                    if llvm_local_ty != llvm_ret_ty {
                        // 类型不匹配，使用 bitcast 转换指针
                        let bitcast_temp = format!("%ptr.{}", local.id);
                        let ret_ptr_ty = format!("{}*", llvm_ret_ty);
                        self.ir.push_str(&format!(
                            "{} = bitcast {} {} to {}\n",
                            bitcast_temp, local_ptr_ty, reg, ret_ptr_ty
                        ));
                        self.emit_indent();
                        self.ir.push_str(&format!(
                            "{} = load {}, {}* {}\n",
                            ret_temp, llvm_ret_ty, llvm_ret_ty, bitcast_temp
                        ));
                    } else {
                        // 绫诲瀷鍖归厤锛岀洿鎺ュ姞杞?
                        self.ir.push_str(&format!(
                            "{} = load {}, {} {}\n",
                            ret_temp, llvm_ret_ty, local_ptr_ty, reg
                        ));
                    }

                    // main 鍑芥暟闇€瑕佽繑鍥?i32
                    if mir_fn.name == "main" && llvm_ret_ty != "i32" {
                        self.emit_indent();
                        let ret_i32 = format!("%.ret.i32.bb{}", self.current_block_id);
                        self.ir.push_str(&format!(
                            "{} = trunc {} {} to i32\n",
                            ret_i32, llvm_ret_ty, ret_temp
                        ));
                        self.emit_indent();
                        self.ir.push_str(&format!("ret i32 {}\n", ret_i32));
                    } else {
                        self.emit_indent();
                        self.ir
                            .push_str(&format!("ret {} {}\n", llvm_ret_ty, ret_temp));
                    }
                } else {
                    self.ir.push_str("ret void\n");
                }
            }
            mir::Terminator::Goto(target) => {
                self.ir.push_str(&format!("br label %bb_{}\n", target));
            }
            mir::Terminator::If {
                cond,
                then_block,
                else_block,
            } => {
                let cond_ty = self.get_local_type(mir_fn, *cond);
                let cond_val = self.local_reg(*cond);
                let cond_temp = format!("{}.cond", self.local_name(*cond));

                // 鍔犺浇鏉′欢鍊?
                self.ir.push_str(&format!(
                    "{} = load {}, {}* {}\n",
                    cond_temp,
                    self.mir_type_to_llvm_str(&cond_ty),
                    self.mir_type_to_llvm_str(&cond_ty),
                    cond_val
                ));

                // 濡傛灉涓嶆槸 i1锛岄渶瑕佽浆鎹?
                let cond_i1 = if self.mir_type_to_llvm_str(&cond_ty) != "i1" {
                    self.emit_indent();
                    let cond_i1_name = format!("{}.i1", cond_temp);
                    self.ir.push_str(&format!(
                        "{} = icmp ne {} {}, 0\n",
                        cond_i1_name,
                        self.mir_type_to_llvm_str(&cond_ty),
                        cond_temp
                    ));
                    Some(cond_i1_name)
                } else {
                    Some(cond_temp.clone())
                };

                self.emit_indent();
                self.ir.push_str(&format!(
                    "br i1 {}, label %bb_{}, label %bb_{}\n",
                    cond_i1.as_ref().unwrap_or(&cond_temp),
                    then_block,
                    else_block
                ));
            }
            mir::Terminator::Break { target } => {
                // break 璺宠浆鍒扮洰鏍囧潡
                self.ir.push_str(&format!("br label %bb_{}\n", target));
            }
            mir::Terminator::Continue { target } => {
                // continue 璺宠浆鍒扮洰鏍囧潡
                self.ir.push_str(&format!("br label %bb_{}\n", target));
            }
            _ => {
                self.ir
                    .push_str(&format!("; unhandled terminator: {:?}\n", terminator));
            }
        }
        Ok(())
    }

    /// 发射 main 包装器
    fn emit_main_wrapper(&mut self) {
        self.ir.push_str("; Main wrapper\n");
        self.ir.push_str("define i32 @main() {\n");
        self.indent += 1;
        self.emit_indent();
        self.ir.push_str("call void @_entry()\n");
        self.emit_indent();
        self.ir.push_str("ret i32 0\n");
        self.indent -= 1;
        self.ir.push_str("}\n\n");
    }

    /// 鑾峰彇鐢熸垚鐨?LLVM IR
    pub fn to_string(&self) -> &str {
        &self.ir
    }
}

impl Default for JITCodegen {
    fn default() -> Self {
        Self::new()
    }
}
