use crate::resolver::{Graph, PackageNode, PackageSource};
use miette::{Context, IntoDiagnostic, Result};
use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

static LOCKFILE_STAGING_COUNTER: AtomicU64 = AtomicU64::new(0);

pub fn write_lockfile(graph: &Graph) -> Result<PathBuf> {
    let root = root_package(graph)?;
    let lockfile_path = lockfile_path(root);
    let content = render_lockfile(graph, root)?;
    write_lockfile_content(&lockfile_path, &content)?;
    Ok(lockfile_path)
}

pub fn check_lockfile(graph: &Graph) -> Result<PathBuf> {
    let root = root_package(graph)?;
    let lockfile_path = lockfile_path(root);
    let expected = render_lockfile(graph, root)?;
    let actual = match fs::read_to_string(&lockfile_path) {
        Ok(actual) => actual,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            miette::bail!("Sengoo.lock is out of date; run sgpm update")
        }
        Err(err) => {
            return Err(err)
                .into_diagnostic()
                .with_context(|| format!("failed to read {}", lockfile_path.display()));
        }
    };
    if actual != expected {
        miette::bail!("Sengoo.lock is out of date; run sgpm update");
    }
    Ok(lockfile_path)
}

pub fn write_workspace_lockfile(workspace_manifest: &Path, graphs: &[Graph]) -> Result<PathBuf> {
    let lockfile_path = workspace_lockfile_path(workspace_manifest)?;
    let content = render_workspace_lockfile(workspace_manifest, graphs)?;
    write_lockfile_content(&lockfile_path, &content)?;
    Ok(lockfile_path)
}

pub fn check_workspace_lockfile(workspace_manifest: &Path, graphs: &[Graph]) -> Result<PathBuf> {
    let lockfile_path = workspace_lockfile_path(workspace_manifest)?;
    let expected = render_workspace_lockfile(workspace_manifest, graphs)?;
    let actual = match fs::read_to_string(&lockfile_path) {
        Ok(actual) => actual,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            miette::bail!("Sengoo.lock is out of date; run sgpm update --workspace")
        }
        Err(err) => {
            return Err(err)
                .into_diagnostic()
                .with_context(|| format!("failed to read {}", lockfile_path.display()));
        }
    };
    if actual != expected {
        miette::bail!("Sengoo.lock is out of date; run sgpm update --workspace");
    }
    Ok(lockfile_path)
}

fn root_package(graph: &Graph) -> Result<&PackageNode> {
    let root = graph
        .root_package()
        .ok_or_else(|| miette::miette!("dependency graph has no root package"))?;
    Ok(root)
}

fn lockfile_path(root: &PackageNode) -> PathBuf {
    root.root_dir.join("Sengoo.lock")
}

fn workspace_lockfile_path(workspace_manifest: &Path) -> Result<PathBuf> {
    let workspace_dir = workspace_manifest.parent().ok_or_else(|| {
        miette::miette!(
            "workspace manifest has no parent directory: {}",
            workspace_manifest.display()
        )
    })?;
    Ok(workspace_dir.join("Sengoo.lock"))
}

fn render_lockfile(graph: &Graph, root: &PackageNode) -> Result<String> {
    let mut out = String::new();
    out.push_str("# This file is generated by sgpm update.\n");
    out.push_str("version = 1\n");
    out.push_str(&format!("root = \"{}\"\n\n", escape(&root.name)));

    for node in &graph.nodes {
        render_package_entry(&mut out, &root.root_dir, node);
    }

    Ok(out)
}

fn render_workspace_lockfile(workspace_manifest: &Path, graphs: &[Graph]) -> Result<String> {
    let workspace_dir = workspace_manifest.parent().ok_or_else(|| {
        miette::miette!(
            "workspace manifest has no parent directory: {}",
            workspace_manifest.display()
        )
    })?;
    let mut out = String::new();
    out.push_str("# This file is generated by sgpm update.\n");
    out.push_str("version = 1\n");
    out.push_str("workspace = true\n");
    let members = graphs
        .iter()
        .filter_map(Graph::root_package)
        .map(|root| format!("\"{}\"", escape(&root.name)))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("members = [{}]\n\n", members));

    let mut seen = BTreeSet::new();
    for graph in graphs {
        for node in &graph.nodes {
            if seen.insert(node.manifest_path.clone()) {
                render_package_entry(&mut out, workspace_dir, node);
            }
        }
    }

    Ok(out)
}

fn render_package_entry(out: &mut String, base_dir: &Path, node: &PackageNode) {
    let manifest_path = relative_path(base_dir, &node.manifest_path);
    out.push_str("[[package]]\n");
    out.push_str(&format!("name = \"{}\"\n", escape(&node.name)));
    out.push_str(&format!(
        "version = \"{}\"\n",
        escape(&node.manifest.package.version)
    ));
    out.push_str(&format!(
        "source = \"{}\"\n",
        escape(&package_source(base_dir, node))
    ));
    out.push_str(&format!(
        "manifest = \"{}\"\n",
        escape(&slash_path(&manifest_path))
    ));
    if !node.manifest.dependencies.is_empty() {
        let deps = node
            .manifest
            .dependencies
            .keys()
            .map(|name| format!("\"{}\"", escape(name)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("dependencies = [{}]\n", deps));
    }
    out.push('\n');
}

fn package_source(base_dir: &Path, node: &PackageNode) -> String {
    match &node.source {
        PackageSource::Path => {
            let source_path = relative_path(base_dir, &node.root_dir);
            format!("path+{}", slash_path(&source_path))
        }
        PackageSource::Git { url, rev } => format!("git+{}#{}", url, rev),
        PackageSource::Registry { registry, version } => {
            format!("registry+{}/{}@{}", registry, node.name, version)
        }
    }
}

fn relative_path(from_dir: &Path, to: &Path) -> PathBuf {
    if from_dir == to {
        return PathBuf::from(".");
    }

    let from = path_parts(from_dir);
    let target = path_parts(to);
    if from.first() != target.first() {
        return to.to_path_buf();
    }

    let common = from
        .iter()
        .zip(target.iter())
        .take_while(|(left, right)| left == right)
        .count();

    let mut result = PathBuf::new();
    for _ in common..from.len() {
        result.push("..");
    }
    for part in &target[common..] {
        result.push(part);
    }
    if result.as_os_str().is_empty() {
        PathBuf::from(".")
    } else {
        result
    }
}

fn path_parts(path: &Path) -> Vec<String> {
    path.components()
        .filter_map(|component| match component {
            Component::Prefix(prefix) => Some(prefix.as_os_str().to_string_lossy().to_string()),
            Component::RootDir => Some("/".to_string()),
            Component::Normal(part) => Some(part.to_string_lossy().to_string()),
            Component::ParentDir => Some("..".to_string()),
            Component::CurDir => None,
        })
        .collect()
}

fn slash_path(path: &Path) -> String {
    path.components()
        .map(|component| match component {
            Component::Prefix(prefix) => prefix.as_os_str().to_string_lossy().to_string(),
            Component::RootDir => "/".to_string(),
            Component::Normal(part) => part.to_string_lossy().to_string(),
            Component::ParentDir => "..".to_string(),
            Component::CurDir => ".".to_string(),
        })
        .collect::<Vec<_>>()
        .join("/")
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn write_lockfile_content(lockfile_path: &Path, content: &str) -> Result<()> {
    let staging_path = lockfile_staging_path(lockfile_path)?;
    let result = (|| {
        fs::write(&staging_path, content)
            .into_diagnostic()
            .with_context(|| format!("failed to stage {}", lockfile_path.display()))?;
        replace_file(&staging_path, lockfile_path)
            .into_diagnostic()
            .with_context(|| format!("failed to replace {}", lockfile_path.display()))
    })();
    if result.is_err() {
        let _ = fs::remove_file(&staging_path);
    }
    result
}

fn lockfile_staging_path(lockfile_path: &Path) -> Result<PathBuf> {
    let parent = lockfile_path.parent().ok_or_else(|| {
        miette::miette!(
            "lockfile has no parent directory: {}",
            lockfile_path.display()
        )
    })?;
    let file_name = lockfile_path
        .file_name()
        .ok_or_else(|| miette::miette!("lockfile has no file name: {}", lockfile_path.display()))?;
    let sequence = LOCKFILE_STAGING_COUNTER.fetch_add(1, Ordering::Relaxed);
    Ok(parent.join(format!(
        ".{}.sgpm-write-{}-{}",
        file_name.to_string_lossy(),
        std::process::id(),
        sequence
    )))
}

#[cfg(not(windows))]
fn replace_file(staging_path: &Path, lockfile_path: &Path) -> io::Result<()> {
    fs::rename(staging_path, lockfile_path)
}

#[cfg(windows)]
fn replace_file(staging_path: &Path, lockfile_path: &Path) -> io::Result<()> {
    if !lockfile_path.exists() {
        return fs::rename(staging_path, lockfile_path);
    }

    let backup_path = staging_path.with_extension("backup");
    fs::rename(lockfile_path, &backup_path)?;
    match fs::rename(staging_path, lockfile_path) {
        Ok(()) => {
            let _ = fs::remove_file(backup_path);
            Ok(())
        }
        Err(err) => match fs::rename(&backup_path, lockfile_path) {
            Ok(()) => Err(err),
            Err(restore_err) => Err(io::Error::new(
                restore_err.kind(),
                format!(
                    "failed to install staged lockfile: {err}; failed to restore {}: {restore_err}",
                    backup_path.display()
                ),
            )),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::write_lockfile_content;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_dir(name: &str) -> PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("sgpm_lockfile_{name}_{stamp}"));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn lockfile_content_replaces_existing_file_without_staging_artifacts() {
        let dir = temp_dir("replace");
        let lockfile = dir.join("Sengoo.lock");
        fs::write(&lockfile, "old lockfile\n").unwrap();

        write_lockfile_content(&lockfile, "new lockfile\n").unwrap();

        assert_eq!(fs::read_to_string(&lockfile).unwrap(), "new lockfile\n");
        let leftovers = fs::read_dir(&dir)
            .unwrap()
            .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
            .filter(|name| name != "Sengoo.lock")
            .collect::<Vec<_>>();
        assert!(
            leftovers.is_empty(),
            "leftover staging files: {leftovers:?}"
        );

        let _ = fs::remove_dir_all(dir);
    }
}
